// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::AccessibleButton -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class AccessibleButton;
    class Element;
    class Value;

    class AccessibleButton
    {
    public:
        struct ACCESSIBLEROLE
        {
            ACCESSIBLEROLE& operator=(ACCESSIBLEROLE const&);
            ACCESSIBLEROLE& operator=(ACCESSIBLEROLE&&);
        };

        AccessibleButton(AccessibleButton&&);
        AccessibleButton(AccessibleButton const&);
        AccessibleButton(void);
        virtual ~AccessibleButton(void);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        virtual IClassInfo* GetClassInfoW(void);
        AccessibleButton& operator=(AccessibleButton&&);
        AccessibleButton& operator=(AccessibleButton const&);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        long Initialize(Element*, unsigned long*);
        void Recalc(void);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);

        private:
        static AccessibleButton::ACCESSIBLEROLE const* FindAccessibleRole(int);
        static AccessibleButton::ACCESSIBLEROLE const c_rgar[1];
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
