// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::AcceleratorBehavior -- declarations derived from the real
// dui70.dll export table + PDB publics.
// NOTE: this class is exported at GLOBAL scope in the real DLL
//       (no @DirectUI@@ component in its decorated names).
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

    class AcceleratorBehavior
    {
    public:
        static long Create(IDuiBehavior**);
    };
