// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::AutoLock -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class AutoLock;

    class AutoLock
    {
    public:
        AutoLock(_RTL_CRITICAL_SECTION*);
        ~AutoLock(void);
        AutoLock& operator=(AutoLock const&);
    };

} // namespace DirectUI
