// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::Bind -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Bind;
    class Element;
    class Value;

    class Bind
    {
    public:
        Bind(Bind&&);
        Bind(Bind const&);
        Bind(void);
        virtual ~Bind(void);
        virtual IClassInfo* GetClassInfoW(void);
        Bind& operator=(Bind&&);
        Bind& operator=(Bind const&);
        static PropertyInfo const* ConnectProp(void);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        unsigned short const* GetConnect(Value**);
        unsigned short const* GetProperty(Value**);
        long Initialize(Element*, unsigned long*);
        static PropertyInfo const* PropertyProp(void);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);
        long SetConnect(unsigned short const*);
        long SetProperty(unsigned short const*);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
