// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::BorderLayout -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class BorderLayout;
    class Element;
    class Layout;
    struct NavReference;
    class Value;

    class BorderLayout
    {
    public:
        virtual void DoLayout(Element*, int, int);
        virtual tagSIZE UpdateDesiredSize(Element*, int, int, Surface*);
        virtual void OnAdd(Element*, Element**, unsigned int);
        virtual void OnRemove(Element*, Element**, unsigned int);
        virtual void OnLayoutPosChanged(Element*, Element*, int, int);
        // ABI placeholder: real slot 5 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_BorderLayout_5(void) = 0;
        // ABI placeholder: real slot 6 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_BorderLayout_6(void) = 0;
        virtual Element* GetAdjacent(Element*, Element*, int, NavReference const*, unsigned long);
        BorderLayout(BorderLayout const&);
        BorderLayout(void);
        virtual ~BorderLayout(void);
        BorderLayout& operator=(BorderLayout const&);
        static long Create(int, int*, Value**);
        static long Create(Layout**);
        void Initialize(void);

        private:
        void SetClient(Element*);
    };

} // namespace DirectUI
