// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::Button -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "Element.h"

namespace DirectUI
{
    class Button;
    class Element;
    class Value;

    class Button
        : public Element
    {
    public:
        Button(Button const&);
        Button(void);
        virtual ~Button(void);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        virtual void OnInput(InputEvent*);
        virtual IClassInfo* GetClassInfoW(void);
        virtual long DefaultAction(void);
        virtual bool OnLostDialogFocus(IDialogElement*);
        virtual bool OnReceivedDialogFocus(IDialogElement*);
        Button& operator=(Button const&);
        static PropertyInfo const* CapturedProp(void);
        static UID Click(void);
        static UID Context(void);
        static long Create(unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        bool GetCaptured(void);
        static IClassInfo* GetClassInfoPtr(void);
        bool GetPressed(void);
        long Initialize(unsigned int, Element*, unsigned long*);
        static PropertyInfo const* PressedProp(void);
        static long Register(void);
        long SetCaptured(bool);
        static void SetClassInfoPtr(IClassInfo*);
        long SetPressed(bool);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
