// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::CCAVI -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class CCAVI;
    class Element;

    class CCAVI
    {
    public:
        CCAVI(CCAVI&&);
        CCAVI(CCAVI const&);
        CCAVI(void);
        virtual ~CCAVI(void);
        virtual IClassInfo* GetClassInfoW(void);

        protected:
        virtual void PostCreate(HWND__*);

        public:
        CCAVI& operator=(CCAVI&&);
        CCAVI& operator=(CCAVI const&);
        static long Create(unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        void Play(HWND__*);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);
        void Stop(void);

        private:
        void OpenAnimation(HWND__*);
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
