// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::CCBaseCheckRadioButton -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "CCBase.h"

namespace DirectUI
{
    class CCBaseCheckRadioButton;
    class Value;

    class CCBaseCheckRadioButton
        : public CCBase
    {
    public:
        CCBaseCheckRadioButton(CCBaseCheckRadioButton&&);
        CCBaseCheckRadioButton(CCBaseCheckRadioButton const&);
        CCBaseCheckRadioButton(unsigned long);
        virtual ~CCBaseCheckRadioButton(void);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        virtual tagSIZE GetContentSize(int, int, Surface*);
        virtual IClassInfo* GetClassInfoW(void);
        virtual bool OnLostDialogFocus(IDialogElement*);
        virtual bool OnReceivedDialogFocus(IDialogElement*);

        protected:
        virtual void PostCreate(HWND__*);

        public:
        // ABI placeholder: real slot 60 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCBaseCheckRadioButton_60(void) = 0;
        // ABI placeholder: real slot 61 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCBaseCheckRadioButton_61(void) = 0;
        // ABI placeholder: real slot 62 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCBaseCheckRadioButton_62(void) = 0;
        CCBaseCheckRadioButton& operator=(CCBaseCheckRadioButton&&);
        CCBaseCheckRadioButton& operator=(CCBaseCheckRadioButton const&);
        static IClassInfo* GetClassInfoPtr(void);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
