// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::CCCommandLink -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class CCCommandLink;
    class Element;
    class Value;

    class CCCommandLink
    {
    public:
        CCCommandLink(CCCommandLink&&);
        CCCommandLink(CCCommandLink const&);
        CCCommandLink(unsigned long);
        virtual ~CCCommandLink(void);
        CCCommandLink& operator=(CCCommandLink&&);
        CCCommandLink& operator=(CCCommandLink const&);
        static long Create(unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        virtual IClassInfo* GetClassInfoW(void);
        virtual tagSIZE GetContentSize(int, int, Surface*);
        unsigned short const* GetNote(Value**);
        static PropertyInfo const* NoteProp(void);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        virtual void OnSelectedPropertyChanged(void);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);
        long SetNote(unsigned short const*);

        protected:
        virtual void PostCreate(HWND__*);
        void SyncNoteAndGlyph(HWND__*);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
