// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::CCCommandLink -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class CCCommandLink;
    class Element;
    class Value;

    class CCCommandLink
    {
    public:
        CCCommandLink(CCCommandLink&&);
        CCCommandLink(CCCommandLink const&);
        CCCommandLink(unsigned long);
        virtual ~CCCommandLink(void);
        // ABI placeholder: real slot 1 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_1(void) = 0;
        // ABI placeholder: real slot 2 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_2(void) = 0;
        // ABI placeholder: real slot 3 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_3(void) = 0;
        // ABI placeholder: real slot 4 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_4(void) = 0;
        // ABI placeholder: real slot 5 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_5(void) = 0;
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        // ABI placeholder: real slot 7 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_7(void) = 0;
        // ABI placeholder: real slot 8 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_8(void) = 0;
        // ABI placeholder: real slot 9 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_9(void) = 0;
        // ABI placeholder: real slot 10 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_10(void) = 0;
        // ABI placeholder: real slot 11 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_11(void) = 0;
        // ABI placeholder: real slot 12 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_12(void) = 0;
        // ABI placeholder: real slot 13 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_13(void) = 0;
        // ABI placeholder: real slot 14 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_14(void) = 0;
        virtual tagSIZE GetContentSize(int, int, Surface*);
        // ABI placeholder: real slot 16 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_16(void) = 0;
        // ABI placeholder: real slot 17 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_17(void) = 0;
        // ABI placeholder: real slot 18 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_18(void) = 0;
        // ABI placeholder: real slot 19 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_19(void) = 0;
        // ABI placeholder: real slot 20 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_20(void) = 0;
        // ABI placeholder: real slot 21 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_21(void) = 0;
        // ABI placeholder: real slot 22 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_22(void) = 0;
        // ABI placeholder: real slot 23 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_23(void) = 0;
        // ABI placeholder: real slot 24 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_24(void) = 0;
        // ABI placeholder: real slot 25 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_25(void) = 0;
        // ABI placeholder: real slot 26 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_26(void) = 0;
        // ABI placeholder: real slot 27 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_27(void) = 0;
        // ABI placeholder: real slot 28 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_28(void) = 0;
        // ABI placeholder: real slot 29 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_29(void) = 0;
        // ABI placeholder: real slot 30 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_30(void) = 0;
        // ABI placeholder: real slot 31 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_31(void) = 0;
        // ABI placeholder: real slot 32 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_32(void) = 0;
        // ABI placeholder: real slot 33 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_33(void) = 0;
        // ABI placeholder: real slot 34 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_34(void) = 0;
        virtual IClassInfo* GetClassInfoW(void);
        // ABI placeholder: real slot 36 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_36(void) = 0;
        // ABI placeholder: real slot 37 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_37(void) = 0;
        // ABI placeholder: real slot 38 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_38(void) = 0;
        // ABI placeholder: real slot 39 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_39(void) = 0;
        // ABI placeholder: real slot 40 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_40(void) = 0;
        // ABI placeholder: real slot 41 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_41(void) = 0;
        // ABI placeholder: real slot 42 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_42(void) = 0;
        // ABI placeholder: real slot 43 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_43(void) = 0;
        // ABI placeholder: real slot 44 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_44(void) = 0;
        // ABI placeholder: real slot 45 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_45(void) = 0;
        // ABI placeholder: real slot 46 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_46(void) = 0;
        // ABI placeholder: real slot 47 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_47(void) = 0;
        // ABI placeholder: real slot 48 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_48(void) = 0;
        // ABI placeholder: real slot 49 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_49(void) = 0;
        // ABI placeholder: real slot 50 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_50(void) = 0;
        // ABI placeholder: real slot 51 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_51(void) = 0;
        // ABI placeholder: real slot 52 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_52(void) = 0;
        // ABI placeholder: real slot 53 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_53(void) = 0;
        // ABI placeholder: real slot 54 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_54(void) = 0;
        // ABI placeholder: real slot 55 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_55(void) = 0;
        // ABI placeholder: real slot 56 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_56(void) = 0;
        // ABI placeholder: real slot 57 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_57(void) = 0;
        // ABI placeholder: real slot 58 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_58(void) = 0;

        protected:
        virtual void PostCreate(HWND__*);

        public:
        // ABI placeholder: real slot 60 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_60(void) = 0;
        virtual void OnSelectedPropertyChanged(void);
        // ABI placeholder: real slot 62 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCCommandLink_62(void) = 0;
        CCCommandLink& operator=(CCCommandLink&&);
        CCCommandLink& operator=(CCCommandLink const&);
        static long Create(unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        unsigned short const* GetNote(Value**);
        static PropertyInfo const* NoteProp(void);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);
        long SetNote(unsigned short const*);

        protected:
        void SyncNoteAndGlyph(HWND__*);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
