// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::CCListView -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class CCListView;
    class Element;

    class CCListView
    {
    public:
        CCListView(CCListView&&);
        CCListView(CCListView const&);
        CCListView(void);
        virtual ~CCListView(void);
        CCListView& operator=(CCListView&&);
        CCListView& operator=(CCListView const&);
        static long Create(unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        virtual IClassInfo* GetClassInfoW(void);
        virtual tagSIZE GetContentSize(int, int, Surface*);
        long Initialize(unsigned int, Element*, unsigned long*);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
