// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::CCProgressBar -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class CCProgressBar;
    class Element;

    class CCProgressBar
    {
    public:
        CCProgressBar(CCProgressBar&&);
        CCProgressBar(CCProgressBar const&);
        CCProgressBar(void);
        virtual ~CCProgressBar(void);
        CCProgressBar& operator=(CCProgressBar&&);
        CCProgressBar& operator=(CCProgressBar const&);
        static long Create(unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        virtual IClassInfo* GetClassInfoW(void);
        long Initialize(unsigned int, Element*, unsigned long*);
        virtual void OnInput(InputEvent*);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
