// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::CCPushButton -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "CCBase.h"

namespace DirectUI
{
    class CCPushButton;
    class Element;
    class Value;

    class CCPushButton
        : public CCBase
    {
    public:
        CCPushButton(CCPushButton&&);
        CCPushButton(CCPushButton const&);
        CCPushButton(unsigned long);
        virtual ~CCPushButton(void);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        virtual void OnInput(InputEvent*);
        virtual tagSIZE GetContentSize(int, int, Surface*);
        virtual IClassInfo* GetClassInfoW(void);
        virtual long DefaultAction(void);
        virtual bool OnNotify(unsigned int, unsigned __int64, __int64, __int64*);
        virtual bool OnMessage(unsigned int, unsigned __int64, __int64, __int64*);
        virtual bool OnLostDialogFocus(IDialogElement*);
        virtual bool OnReceivedDialogFocus(IDialogElement*);
        virtual bool GetButtonColor(HDC__*, HBRUSH__**);
        virtual void OnSelectedPropertyChanged(void);
        virtual tagSIZE EstimateContentSize(int, int, Surface*);
        CCPushButton& operator=(CCPushButton&&);
        CCPushButton& operator=(CCPushButton const&);
        static long Create(unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        bool GetHasShield(void);
        bool GetOverrideButtonBackground(void);
        static PropertyInfo const* HasShieldProp(void);
        static PropertyInfo const* OverrideButtonBackgroundProp(void);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);
        long SetOverrideButtonBackground(bool);

        protected:
        void SetDefaultState(unsigned long, unsigned long);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
