// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::CCTreeView -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "CCBase.h"

namespace DirectUI
{
    class CCTreeView;
    class Element;

    class CCTreeView
        : public CCBase
    {
    public:
        CCTreeView(CCTreeView&&);
        CCTreeView(CCTreeView const&);
        CCTreeView(unsigned long);
        virtual ~CCTreeView(void);
        virtual tagSIZE GetContentSize(int, int, Surface*);
        virtual IClassInfo* GetClassInfoW(void);
        virtual bool OnNotify(unsigned int, unsigned __int64, __int64, __int64*);

        protected:
        virtual long _OnGetInfoTip(tagNMTVGETINFOTIPW const*);
        virtual long _OnItemChanged(tagTVITEMCHANGE const*);

        public:
        CCTreeView& operator=(CCTreeView&&);
        CCTreeView& operator=(CCTreeView const&);
        static long Create(unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        unsigned int GetItemState(_TREEITEM*const);
        unsigned long GetStyle(void);
        _TREEITEM* InsertItem(unsigned short*, unsigned int, _TREEITEM*const, _TREEITEM*const);
        _TREEITEM* InsertItem(tagTVINSERTSTRUCTW const*);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);
        void SetItemState(_TREEITEM*, unsigned int);
        unsigned long SetStyle(unsigned long);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
