// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::CCTreeView -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class CCTreeView;
    class Element;

    class CCTreeView
    {
    public:
        CCTreeView(CCTreeView&&);
        CCTreeView(CCTreeView const&);
        CCTreeView(unsigned long);
        virtual ~CCTreeView(void);
        // ABI placeholder: real slot 1 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_1(void) = 0;
        // ABI placeholder: real slot 2 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_2(void) = 0;
        // ABI placeholder: real slot 3 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_3(void) = 0;
        // ABI placeholder: real slot 4 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_4(void) = 0;
        // ABI placeholder: real slot 5 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_5(void) = 0;
        // ABI placeholder: real slot 6 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_6(void) = 0;
        // ABI placeholder: real slot 7 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_7(void) = 0;
        // ABI placeholder: real slot 8 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_8(void) = 0;
        // ABI placeholder: real slot 9 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_9(void) = 0;
        // ABI placeholder: real slot 10 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_10(void) = 0;
        // ABI placeholder: real slot 11 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_11(void) = 0;
        // ABI placeholder: real slot 12 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_12(void) = 0;
        // ABI placeholder: real slot 13 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_13(void) = 0;
        // ABI placeholder: real slot 14 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_14(void) = 0;
        virtual tagSIZE GetContentSize(int, int, Surface*);
        // ABI placeholder: real slot 16 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_16(void) = 0;
        // ABI placeholder: real slot 17 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_17(void) = 0;
        // ABI placeholder: real slot 18 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_18(void) = 0;
        // ABI placeholder: real slot 19 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_19(void) = 0;
        // ABI placeholder: real slot 20 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_20(void) = 0;
        // ABI placeholder: real slot 21 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_21(void) = 0;
        // ABI placeholder: real slot 22 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_22(void) = 0;
        // ABI placeholder: real slot 23 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_23(void) = 0;
        // ABI placeholder: real slot 24 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_24(void) = 0;

        protected:
        virtual long _OnGetInfoTip(tagNMTVGETINFOTIPW const*);

        public:
        // ABI placeholder: real slot 26 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_26(void) = 0;
        // ABI placeholder: real slot 27 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_27(void) = 0;
        // ABI placeholder: real slot 28 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_28(void) = 0;
        // ABI placeholder: real slot 29 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_29(void) = 0;
        // ABI placeholder: real slot 30 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_30(void) = 0;
        // ABI placeholder: real slot 31 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_31(void) = 0;
        // ABI placeholder: real slot 32 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_32(void) = 0;
        // ABI placeholder: real slot 33 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_33(void) = 0;
        // ABI placeholder: real slot 34 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_34(void) = 0;
        virtual IClassInfo* GetClassInfoW(void);
        // ABI placeholder: real slot 36 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_36(void) = 0;
        // ABI placeholder: real slot 37 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_37(void) = 0;

        protected:
        virtual long _OnItemChanged(tagTVITEMCHANGE const*);

        public:
        // ABI placeholder: real slot 39 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_39(void) = 0;
        // ABI placeholder: real slot 40 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_40(void) = 0;
        // ABI placeholder: real slot 41 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_41(void) = 0;
        // ABI placeholder: real slot 42 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_42(void) = 0;
        // ABI placeholder: real slot 43 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_43(void) = 0;
        // ABI placeholder: real slot 44 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_44(void) = 0;
        // ABI placeholder: real slot 45 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_45(void) = 0;
        virtual bool OnNotify(unsigned int, unsigned __int64, __int64, __int64*);
        // ABI placeholder: real slot 47 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_47(void) = 0;
        // ABI placeholder: real slot 48 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_48(void) = 0;
        // ABI placeholder: real slot 49 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_49(void) = 0;
        // ABI placeholder: real slot 50 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_50(void) = 0;
        // ABI placeholder: real slot 51 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_51(void) = 0;
        // ABI placeholder: real slot 52 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_52(void) = 0;
        // ABI placeholder: real slot 53 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_53(void) = 0;
        // ABI placeholder: real slot 54 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_54(void) = 0;
        // ABI placeholder: real slot 55 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_55(void) = 0;
        // ABI placeholder: real slot 56 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_56(void) = 0;
        // ABI placeholder: real slot 57 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_57(void) = 0;
        // ABI placeholder: real slot 58 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_58(void) = 0;
        // ABI placeholder: real slot 59 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_59(void) = 0;
        // ABI placeholder: real slot 60 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_60(void) = 0;
        // ABI placeholder: real slot 61 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_CCTreeView_61(void) = 0;
        CCTreeView& operator=(CCTreeView&&);
        CCTreeView& operator=(CCTreeView const&);
        static long Create(unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        unsigned int GetItemState(_TREEITEM*const);
        unsigned long GetStyle(void);
        _TREEITEM* InsertItem(unsigned short*, unsigned int, _TREEITEM*const, _TREEITEM*const);
        _TREEITEM* InsertItem(tagTVINSERTSTRUCTW const*);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);
        void SetItemState(_TREEITEM*, unsigned int);
        unsigned long SetStyle(unsigned long);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
