// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::ClassInfoBase -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class ClassInfoBase;

    class ClassInfoBase
    {
    public:
        ClassInfoBase(ClassInfoBase const&);
        ClassInfoBase(void);
        virtual ~ClassInfoBase(void);
        ClassInfoBase& operator=(ClassInfoBase const&);
        virtual void AddChild(void);
        virtual void AddRef(void);
        virtual void AssertPIZeroRef(void) const;
        static bool ClassExist(IClassInfo**, PropertyInfo const*const*, unsigned int, IClassInfo*, HINSTANCE__*, unsigned short const*, bool);
        virtual void Destroy(void);
        virtual PropertyInfo const* EnumPropertyInfo(unsigned int);
        virtual PropertyInfo const* GetByClassIndex(unsigned int);
        virtual int GetChildren(void) const;
        virtual unsigned int GetGlobalIndex(void) const;
        virtual HINSTANCE__* GetModule(void) const;
        virtual unsigned short const* GetName(void) const;
        virtual unsigned int GetPICount(void) const;
        long Initialize(HINSTANCE__*, unsigned short const*, bool, PropertyInfo const*const*, unsigned int);
        virtual bool IsGlobal(void) const;
        virtual bool IsSubclassOf(IClassInfo*) const;
        virtual bool IsValidProperty(PropertyInfo const*) const;
        long Register(void);
        virtual int Release(void);
        virtual void RemoveChild(void);
    };

} // namespace DirectUI
