// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::Clipper -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Clipper;
    class Element;

    class Clipper
    {
    public:
        Clipper(Clipper&&);
        Clipper(Clipper const&);
        Clipper(void);
        virtual ~Clipper(void);
        // ABI placeholder: real slot 1 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_1(void) = 0;
        // ABI placeholder: real slot 2 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_2(void) = 0;
        // ABI placeholder: real slot 3 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_3(void) = 0;
        // ABI placeholder: real slot 4 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_4(void) = 0;
        // ABI placeholder: real slot 5 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_5(void) = 0;
        // ABI placeholder: real slot 6 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_6(void) = 0;
        // ABI placeholder: real slot 7 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_7(void) = 0;
        // ABI placeholder: real slot 8 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_8(void) = 0;
        // ABI placeholder: real slot 9 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_9(void) = 0;
        // ABI placeholder: real slot 10 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_10(void) = 0;
        // ABI placeholder: real slot 11 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_11(void) = 0;
        // ABI placeholder: real slot 12 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_12(void) = 0;
        // ABI placeholder: real slot 13 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_13(void) = 0;
        // ABI placeholder: real slot 14 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_14(void) = 0;
        // ABI placeholder: real slot 15 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_15(void) = 0;
        // ABI placeholder: real slot 16 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_16(void) = 0;
        // ABI placeholder: real slot 17 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_17(void) = 0;
        // ABI placeholder: real slot 18 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_18(void) = 0;
        // ABI placeholder: real slot 19 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_19(void) = 0;
        // ABI placeholder: real slot 20 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_20(void) = 0;
        // ABI placeholder: real slot 21 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_21(void) = 0;
        // ABI placeholder: real slot 22 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_22(void) = 0;
        // ABI placeholder: real slot 23 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_23(void) = 0;
        // ABI placeholder: real slot 24 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_24(void) = 0;
        // ABI placeholder: real slot 25 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_25(void) = 0;
        // ABI placeholder: real slot 26 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_26(void) = 0;
        virtual void _SelfLayoutDoLayout(int, int);
        virtual tagSIZE _SelfLayoutUpdateDesiredSize(int, int, Surface*);
        // ABI placeholder: real slot 29 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_29(void) = 0;
        // ABI placeholder: real slot 30 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_30(void) = 0;
        // ABI placeholder: real slot 31 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_31(void) = 0;
        // ABI placeholder: real slot 32 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_32(void) = 0;
        // ABI placeholder: real slot 33 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_33(void) = 0;
        // ABI placeholder: real slot 34 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_34(void) = 0;
        virtual IClassInfo* GetClassInfoW(void);
        // ABI placeholder: real slot 36 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_36(void) = 0;
        // ABI placeholder: real slot 37 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_37(void) = 0;
        // ABI placeholder: real slot 38 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_38(void) = 0;
        // ABI placeholder: real slot 39 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_39(void) = 0;
        // ABI placeholder: real slot 40 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_40(void) = 0;
        // ABI placeholder: real slot 41 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_41(void) = 0;
        // ABI placeholder: real slot 42 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_42(void) = 0;
        // ABI placeholder: real slot 43 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_43(void) = 0;
        // ABI placeholder: real slot 44 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Clipper_44(void) = 0;
        Clipper& operator=(Clipper&&);
        Clipper& operator=(Clipper const&);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        long Initialize(Element*, unsigned long*);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
