// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::Clipper -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Clipper;
    class Element;

    class Clipper
    {
    public:
        Clipper(Clipper&&);
        Clipper(Clipper const&);
        Clipper(void);
        virtual ~Clipper(void);
        virtual void _SelfLayoutDoLayout(int, int);
        virtual tagSIZE _SelfLayoutUpdateDesiredSize(int, int, Surface*);
        virtual IClassInfo* GetClassInfoW(void);
        Clipper& operator=(Clipper&&);
        Clipper& operator=(Clipper const&);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        long Initialize(Element*, unsigned long*);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
