// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::Combobox -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Combobox;
    class Element;
    class Value;

    class Combobox
    {
    public:
        Combobox(Combobox const&);
        Combobox(void);
        virtual ~Combobox(void);
        Combobox& operator=(Combobox const&);
        int AddString(unsigned short const*);
        static long Create(unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        virtual HWND__* CreateHWND(HWND__*);
        static IClassInfo* GetClassInfoPtr(void);
        virtual IClassInfo* GetClassInfoW(void);
        virtual tagSIZE GetContentSize(int, int, Surface*);
        int GetSelection(void);
        long Initialize(unsigned int, Element*, unsigned long*);
        virtual int OnAdjustWindowSize(int, int, unsigned int);
        virtual void OnHosted(Element*);
        virtual void OnInput(InputEvent*);
        virtual bool OnNotify(unsigned int, unsigned __int64, __int64, __int64*);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        static long Register(void);
        static UID SelectionChange(void);
        static PropertyInfo const* SelectionProp(void);
        static void SetClassInfoPtr(IClassInfo*);
        long SetSelection(int);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
