// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::ContextMenuBehavior -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class ContextMenuBehavior
    {
    public:
        // ABI placeholder: real slot 0 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ContextMenuBehavior_0(void) = 0;
        // ABI placeholder: real slot 1 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ContextMenuBehavior_1(void) = 0;
        // ABI placeholder: real slot 2 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ContextMenuBehavior_2(void) = 0;
        // ABI placeholder: real slot 3 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ContextMenuBehavior_3(void) = 0;
        // ABI placeholder: real slot 4 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ContextMenuBehavior_4(void) = 0;
        // ABI placeholder: real slot 5 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ContextMenuBehavior_5(void) = 0;
        // ABI placeholder: real slot 6 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ContextMenuBehavior_6(void) = 0;
        // ABI placeholder: real slot 7 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ContextMenuBehavior_7(void) = 0;
        // ABI placeholder: real slot 8 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ContextMenuBehavior_8(void) = 0;
        // ABI placeholder: real slot 9 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ContextMenuBehavior_9(void) = 0;
        // ABI placeholder: real slot 10 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ContextMenuBehavior_10(void) = 0;
        // ABI placeholder: real slot 11 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ContextMenuBehavior_11(void) = 0;
        // ABI placeholder: real slot 12 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ContextMenuBehavior_12(void) = 0;
        // ABI placeholder: real slot 13 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ContextMenuBehavior_13(void) = 0;
        // ABI placeholder: real slot 14 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ContextMenuBehavior_14(void) = 0;
        // ABI placeholder: real slot 15 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ContextMenuBehavior_15(void) = 0;
        // ABI placeholder: real slot 16 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ContextMenuBehavior_16(void) = 0;
        // ABI placeholder: real slot 17 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ContextMenuBehavior_17(void) = 0;
        // ABI placeholder: real slot 18 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ContextMenuBehavior_18(void) = 0;
        static UID ContextMenuHintShowing(void);
        static UID ContextMenuRequested(void);
        static long Create(IDuiBehavior**);
    };

} // namespace DirectUI
