// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::CritSecLock -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class CritSecLock;

    class CritSecLock
    {
    public:
        CritSecLock(_RTL_CRITICAL_SECTION*);
        ~CritSecLock(void);
        CritSecLock& operator=(CritSecLock const&);
        void Unlock(void);
    };

} // namespace DirectUI
