// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::DialogElement -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "HWNDElement.h"

#include "Interfaces.h"

#include "dui_abi_types.h"

namespace DirectUI
{
    class DialogElement;
    class Element;
    class Value;

    class DialogElement
        : public HWNDElement, public IElementListener, public IDialogElement
    {
    public:
        DialogElement(DialogElement&&);
        DialogElement(DialogElement const&);
        DialogElement(void);
        virtual ~DialogElement(void);
        DialogElement& operator=(DialogElement&&);
        DialogElement& operator=(DialogElement const&);
        static PropertyInfo const* ButtonClassAcceptsEnterKeyProp(void);
        virtual bool ClickDefaultButton(void);
        static long Create(HWND__*, bool, unsigned int, Element*, unsigned long*, Element**);
        static PropertyInfo const* DefaultButtonTrackingProp(void);
        virtual bool GetButtonClassAcceptsEnterKey(void);
        static IClassInfo* GetClassInfoPtr(void);
        virtual IClassInfo* GetClassInfoW(void);
        virtual Element* GetDefaultButton(void);
        virtual bool GetDefaultButtonTracking(void);
        virtual bool GetHandleEnterKey(void);
        virtual Element* GetKeyFocusedElement(void);
        virtual Element* GetRegisteredDefaultButton(void);
        static PropertyInfo const* HandleEnterKeyProp(void);
        virtual bool OnChildLostFocus(Element*);
        virtual bool OnChildReceivedFocus(Element*);
        virtual void OnDestroy(void);
        virtual void OnGetDlgCode(tagMSG*, __int64*);
        virtual void OnInput(InputEvent*);
        virtual void OnKeyFocusMoved(Element*, Element*);
        virtual void OnListenedEvent(Element*, Event*);
        virtual void OnListenedInput(Element*, InputEvent*);
        virtual void OnListenedPropertyChanged(Element*, PropertyInfo const*, int, Value*, Value*);
        virtual bool OnListenedPropertyChanging(Element*, PropertyInfo const*, int, Value*, Value*);
        virtual void OnListenerAttach(Element*);
        virtual void OnListenerDetach(Element*);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        static long Register(void);
        static PropertyInfo const* RegisteredDefaultButtonProp(void);
        long SetButtonClassAcceptsEnterKey(bool);
        static void SetClassInfoPtr(IClassInfo*);
        virtual long SetDefaultButtonTracking(bool);
        long SetHandleEnterKey(bool);
        long SetRegisteredDefaultButton(Element*);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
