// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Shared ABI prelude for the generated DirectUI headers.
// Contains only what is required to reproduce the exact
// decorated names of the real dui70.dll exports:
//  * global-scope forward declarations (mangled without @2@)
//  * namespace DirectUI forward declarations
//  * minimal complete definitions for by-value types
// NOTE: compiled with /Zc:wchar_t- (the DirectUI ABI), so
//       'const wchar_t*' == 'const unsigned short*' (UCString).
#pragma once

#include <windows.h>
#include <commctrl.h>       // _TREEITEM, tagNMCUSTOMDRAWINFO, _PSP
#include <commdlg.h>        // _PROPSHEETPAGEW
// Option D quarantine (measured, .local/audit/uia-exp): the
// SDK UIA headers are NOT included here anymore. The only
// references in this prelude are comment-level; the real
// consumers include the SDK headers directly: the 13 pattern
// interface headers (UIAutomationCore.h, before their yield
// check), Schema.h (Core+Api for AutomationIdentifierType and
// UiaRaiseAutomationEvent), ElementProxy.h (Core for UiaRect),
// ElementProvider.h / HWNDElementProvider.h (quoted includes,
// unchanged). This keeps SDK UIA types out of provider-only
// TUs that do not use them and out of the CApi collision path.
#include <directmanipulation.h> // IDirectManipulation* interfaces
#include <dwrite.h>         // DWRITE_TEXT_RANGE, IDWriteFactory, ...
#include <oleacc.h>         // IAccessible, IAccIdentity
#include <imagehlp.h>       // STACK_SYMBOL_INFO, API_VERSION, IMGHLPFN_LOAD
#include <inputscope.h>     // inputscope GUIDs (TouchEdit2)
#include <richedit.h>       // CHARRANGE (needed before tom.h)
#include <tom.h>            // ITextDocument (richedit tom)

// UCString: the DirectUI string ABI is 'unsigned short const*'.
// With /Zc:wchar_t- a 'const wchar_t*' parameter mangles
// identically (PEBG), so consumers may use either spelling.
typedef unsigned short const* UCString;

// Global-scope declarations (mangle WITHOUT the DirectUI back-reference)
struct IDuiBehavior;
struct ISharedBitmap;
struct EventMsg;
struct tagGMSG;         // not in windows.h
struct HGADGET__;       // DECLARE_HANDLE(HGADGET) in the real headers
typedef struct HGADGET__* HGADGET;
struct HDCONTEXT__;     // duser opaquely-declared handle type
typedef struct HDCONTEXT__* HDCONTEXT;
struct IXmlReader;      // xmllite reader (fwd suffices: ptr-only ABI)
class ITextServices;    // richedit (PEAV in the real DLL)
class ITextHost;        // richedit text host (PEAV)
struct GMA_ACTIONINFO;  // GraphicMatrixAnimation action (PEAU, GLOBAL)
struct GMA_ACTIONDESC;  // (PEAU, GLOBAL)
struct IDUIRichTextCache;  // RichText cache (PEAU, GLOBAL)
struct IDCompSurface;   // DComp surface (PEAU, GLOBAL)

// DirectUI-private enums that mangle at GLOBAL scope (W4Name@@ without
// the @2@ namespace back-reference).
enum SemanticZoomToggleState { SemanticZoomToggleState_None = 0 };
enum TOUCHTOOLTIP_INPUT { TOUCHTOOLTIP_INPUT_None = 0 };
enum TOUCHTOOLTIP_OPTION_FLAGS { TOUCHTOOLTIP_OPTION_FLAGS_None = 0 };

// UID: returned by value by several static event-id accessors.
// Decorated name in the real DLL is VUID@@ (GLOBAL scope), so it is
// declared here at global scope -- NOT inside namespace DirectUI.
class UID
{
public:
    UID() {}
    void* value;
};

// Compare a UID against an event-id ACCESSOR FUNCTION (called on the
// spot). Lets consumer code write `ev->type == TouchButton::Click`
// without call parentheses (DirectUI types.h idiom).
inline bool operator==(UID id, UID (*ev)(void))
{
    UID p = ev();
    return id.value == p.value;
}

// DynamicScaleValue: GLOBAL-scope enum (W4DynamicScaleValue@@)
enum DynamicScaleValue { DynamicScaleValue_None = 0 };

// ---------------------------------------------------------------------------
// namespace DirectUI
// ---------------------------------------------------------------------------
namespace DirectUI
{
    // ---- forward declarations (IDialogElement's Rule F shape
    //      references Element* params) ----
    class Element;

    // ---- complete definitions required for by-value parameters ----
    struct LINEINFO { unsigned int line; };
    struct ScaledSIZE { int w; int h; };
    struct ScaledRECT { int l; int t; int r; int b; };

    // ---- DirectUI-private enums (by-value ABI; enumerator sets are
    //      not exported -- single-member bodies keep them complete) ----
    enum _DUI_PARSE_STATE { DUI_PARSE_STATE_None = 0 };
    enum DynamicScaleParsing { DynamicScaleParsing_None = 0 };
    enum ActiveState { ActiveState_None = 0 };
    enum ClickDevice { ClickDevice_None = 0 };
    enum IHMState { IHMState_None = 0 };
    enum TouchEditFilteredKeyComboFlags { TouchEditFilteredKeyComboFlags_None = 0 };
    enum TouchEditKeyboardNavigationCapture { TouchEditKeyboardNavigationCapture_None = 0 };
    enum TouchEditPasswordRevealMode { TouchEditPasswordRevealMode_None = 0 };
    enum TouchEditTextMode { TouchEditTextMode_None = 0 };
    enum TouchHWNDElementFlags { TouchHWNDElementFlags_None = 0 };
    enum POPUPCHANGEEVENTTYPE { POPUPCHANGEEVENTTYPE_None = 0 };
    enum POPUPFIREEVENTTYPE { POPUPFIREEVENTTYPE_None = 0 };
    enum FUNCMODE { FUNCMODE_None = 0 };
    enum CheckedStateFlags { CheckedStateFlags_None = 0 };

    // ---- DirectUI-private structs (pointer-only ABI: fwd suffices) ----

    // IDialogElement: abstract mixin interface (real header: DialogElement
    // idiom); needs a definition because DialogElement/XBaby DERIVE from
    // it. Pure virtual so the derived class emits the base-subobject
    // vftable symbol (??_7D@...6BIDialogElement@@).
    // Rule F: full 9-slot shape pinned from the DLL interface tables
    // (DialogElement/XBaby secondaries agree slot-for-slot, every slot
    // a singleton); signatures harvested from DialogElement exports.
    // OnDialogEvent was a stub artifact: no IDialogElement table in
    // the DLL carries it.
    struct __declspec(novtable) IDialogElement
    {
    public:
        virtual bool GetButtonClassAcceptsEnterKey(void) = 0;   // slot 0
        virtual bool GetDefaultButtonTracking(void) = 0;       // slot 1
        virtual Element* GetRegisteredDefaultButton(void) = 0; // slot 2
        virtual bool GetHandleEnterKey(void) = 0;             // slot 3
        virtual long SetDefaultButtonTracking(bool track) = 0;// slot 4
        virtual Element* GetKeyFocusedElement(void) = 0;      // slot 5
        virtual bool OnChildLostFocus(Element* elem) = 0;     // slot 6
        virtual bool OnChildReceivedFocus(Element* elem) = 0; // slot 7
        virtual Element* GetDefaultButton(void) = 0;          // slot 8
    };

    // IXBaby: the X-family content-host interface. Evidence
    // (batch 1, triage r6-xbaby-primary-triage.md): the DLL
    // carries an unsuffixed ??_7XBaby@@6B@ vftable (13 slots,
    // 0x00115D08) stored at this+296 in the ctor -- the table
    // XBaby introduces for its LAST base subobject. TouchXBaby's
    // primary (0x0010E950) carries the IDENTICAL 13-slot name
    // sequence; all 13 names have BOTH implementers' exported
    // symbols with identical signature parts. XProvider::
    // CreateXBaby(..., IXBaby**) returns exactly this type.
    // Signatures harvested from the XBaby exports. Pointer-only
    // parameter/return types stay forward-declared (HWNDElement,
    // DUIXmlParser, Element); tagSIZE is windef.h's, already
    // complete at this point.
    class HWNDElement;
    class DUIXmlParser;
    struct __declspec(novtable) IXBaby
    {
    public:
        virtual HWNDElement* GetXBabyElement(void) = 0;                // slot 0
        virtual void CacheParser(DUIXmlParser* parser) = 0;           // slot 1
        virtual long SetToHost(Element* elem) = 0;                    // slot 2
        virtual tagSIZE GetContentDesiredSize(int width, int height) = 0; // slot 3
        virtual bool CanSetFocus(void) = 0;                          // slot 4
        virtual long GetHostedElementID(unsigned short* id) = 0;      // slot 5
        virtual void ForceThemeChange(unsigned __int64 a, __int64 b) = 0; // slot 6
        virtual bool GetDefaultButtonTracking(void) = 0;             // slot 7
        virtual long SetDefaultButtonTracking(bool track) = 0;       // slot 8
        virtual long SetButtonClassAcceptsEnterKey(bool accepts) = 0; // slot 9
        virtual bool ClickDefaultButton(void) = 0;                   // slot 10
        virtual long SetRegisteredDefaultButton(Element* elem) = 0;  // slot 11
        virtual long SetHandleEnterKey(bool handle) = 0;             // slot 12
    };

    // ---- embedded-subsystem namespaces referenced by exported
    //      signatures (pointer-only: namespace + class fwd) ----
    namespace DuiBehaviorFilters { enum Flags { Flags_None = 0 }; }
    namespace SWF { class Bits; class SWF; class Tag;
                    class Fluster; class ColorTransformBrush;
                    class CommandTag; class Definition;
                    class Movie { public: struct DepthRange; };
                    namespace Shape { struct Action; struct LineSegment; }
                    namespace Types { enum BrushType { BrushType_None = 0 }; } }
    namespace Library { class Stream;
                        template <typename T> class SimpleVector; }
    namespace Gdiplus { class Brush; struct ColorMatrix; }

    // ---- class forward declarations ----
    class DeferCycle;
    class ElementProvider;
    class Expression;
    class InvokeHelper;
    class Layout;
    class StyleSheet;
    class Surface;
    class TouchHWNDElement;

    // ---- struct forward declarations ----
    struct XMLParserCond;
    struct Cursor;
    struct DepRecs;
    struct EnumMap;
    struct Event;
    struct Fill;
    struct Graphic;
    struct IClassInfo;
    struct IElementListener;
    struct InputEvent;
    struct KeyboardEvent;
    struct MouseEvent;
    struct NavReference;
    struct PointerEvent;
    struct PropertyInfo;
    struct ScaledInt;
    struct ThemeChangedEvent;
    struct UpdateCache;
    struct CellInfo;
    struct ElementRuntimeId;
    struct IXBaby;
    class IXElementCP;
    struct IXProvider;
    class IXProviderCP;
    struct RectangleChange;

    // ---- ValueType: consumer-side knowledge (enum members are never
    // exported; members transcribed from DirectUI Value.h). Used by
    // UITest in switch statements over Value::GetType(). ----
    enum class ValueType : int
    {
        Unavailable = -2,
        Unset = -1,
        Null = 0,
        Int = 1,
        Bool = 2,
        Element = 3,
        Ellist = 4,
        String = 5,
        Point = 6,
        Size = 7,
        Rect = 8,
        Color = 9,
        Layout = 10,
        Graphic = 11,
        Sheet = 12,
        Expr = 13,
        Atom = 14,
        Cursor = 15,
        Float = 18,
        DblList = 19,
    };

    // ---- ParserTools nested namespace ----
    namespace ParserTools
    {
        struct ExprNode;
        class ValueParser;
    }

    // ---- generic containers referenced by exported methods ----
    // DynamicArray<T, N> is used as a plain (non-template) parameter
    // type by several exported methods (CreateElementList etc.)
    template <typename T, int N>
    class DynamicArray;

    // UiaArray<T>: exported static data members hold instances
    // (g_pArrayPprv, g_pArrayInvokeHelper). Pointer-size object;
    // the mangled data symbol only needs the template-id.
    template <typename T>
    class UiaArray { public: void* _storage; };

} // namespace DirectUI
