// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::Edit -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "Element.h"

namespace DirectUI
{
    class Edit;
    class Element;
    class Value;

    class Edit
        : public Element
    {
    public:
        Edit(Edit const&);
        Edit(void);
        virtual ~Edit(void);
        virtual bool IsContentProtected(void);
        virtual unsigned short const* GetContentStringAsDisplayed(Value**);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        virtual void OnInput(InputEvent*);
        virtual tagSIZE GetContentSize(int, int, Surface*);
        virtual unsigned int MessageCallback(tagGMSG*);
        virtual IClassInfo* GetClassInfoW(void);
        // ABI placeholder: real slot 45 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Edit_45(void) = 0;
        virtual bool OnNotify(unsigned int, unsigned __int64, __int64, __int64*);
        // ABI placeholder: real slot 47 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Edit_47(void) = 0;
        // ABI placeholder: real slot 48 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Edit_48(void) = 0;
        // ABI placeholder: real slot 49 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Edit_49(void) = 0;
        // ABI placeholder: real slot 50 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Edit_50(void) = 0;
        // ABI placeholder: real slot 51 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Edit_51(void) = 0;
        // ABI placeholder: real slot 52 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Edit_52(void) = 0;
        // ABI placeholder: real slot 53 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Edit_53(void) = 0;

        protected:
        virtual HWND__* CreateHWND(HWND__*);

        public:
        // ABI placeholder: real slot 55 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_Edit_55(void) = 0;

        protected:
        virtual HWND__* CreateHWND(HWND__*, bool);

        public:
        Edit& operator=(Edit const&);
        static long Create(unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        static PropertyInfo const* DirtyProp(void);
        static UID Enter(void);
        static IClassInfo* GetClassInfoPtr(void);
        bool GetDirty(void);
        int GetMaxLength(void);
        bool GetMultiline(void);
        int GetPasswordCharacter(void);
        bool GetThemedBorder(void);
        bool GetWantTabs(void);
        long Initialize(unsigned int, Element*, unsigned long*);
        static PropertyInfo const* MaxLengthProp(void);
        static PropertyInfo const* MultilineProp(void);
        static PropertyInfo const* PasswordCharacterProp(void);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);
        long SetDirty(bool);
        long SetMaxLength(int);
        long SetMultiline(bool);
        long SetPasswordCharacter(int);
        long SetThemedBorder(bool);
        long SetWantTabs(bool);
        static PropertyInfo const* ThemedBorderProp(void);
        static PropertyInfo const* WantTabsProp(void);

        private:
        unsigned int GetTextHeight(void);
        void PropertyChangedCore(PropertyInfo const*, int, Value*, HWND__*);
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
