// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::Edit -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "Element.h"

namespace DirectUI
{
    class Value;
    class DUIXmlParser;
    class HWNDElement;
    class NativeHWNDHost;
    class TouchButton;
    class Button;
    class Progress;
    class PushButton;
    class TouchCheckBox;
    class XProvider;

    class Edit
        : public Element
    {
    public:
        Edit(Edit const&);
        Edit(void);
        virtual ~Edit(void);
        Edit& operator=(Edit const&);
        static long Create(unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        static PropertyInfo const* DirtyProp(void);
        static UID Enter(void);
        static IClassInfo* GetClassInfoPtr(void);
        virtual IClassInfo* GetClassInfoW(void);
        virtual tagSIZE GetContentSize(int, int, Surface*);
        virtual unsigned short const* GetContentStringAsDisplayed(Value**);
        bool GetDirty(void);
        int GetMaxLength(void);
        bool GetMultiline(void);
        int GetPasswordCharacter(void);
        bool GetThemedBorder(void);
        bool GetWantTabs(void);
        long Initialize(unsigned int, Element*, unsigned long*);
        virtual bool IsContentProtected(void);
        static PropertyInfo const* MaxLengthProp(void);
        virtual unsigned int MessageCallback(tagGMSG*);
        static PropertyInfo const* MultilineProp(void);
        virtual void OnInput(InputEvent*);
        virtual bool OnNotify(unsigned int, unsigned __int64, __int64, __int64*);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        static PropertyInfo const* PasswordCharacterProp(void);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);
        long SetDirty(bool);
        long SetMaxLength(int);
        long SetMultiline(bool);
        long SetPasswordCharacter(int);
        long SetThemedBorder(bool);
        long SetWantTabs(bool);
        static PropertyInfo const* ThemedBorderProp(void);
        static PropertyInfo const* WantTabsProp(void);

        protected:
        virtual HWND__* CreateHWND(HWND__*);
        virtual HWND__* CreateHWND(HWND__*, bool);

        private:
        unsigned int GetTextHeight(void);
        void PropertyChangedCore(PropertyInfo const*, int, Value*, HWND__*);
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
