// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::ElementProvider -- declarations derived from the real
// dui70.dll export table + PDB publics.
// W5 stage-2 MI emission (ElementProvider family): the
// RefcountBase@1@ subobject is the FIRST base; its table
// carries this class's introduced virtuals in DLL slot
// order (pinned mi-tables.json, schema 2). The DLL's real
// first base is an unnamed RefcountBase-derived
// intermediate; declaring the introduced virtuals here
// reproduces the same subobject tables.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "RefcountBase.h"

#include <UIAutomationCore.h>

#include <UIAutomationCore.h>

#include <UIAutomationCore.h>

#include "Schema.h"

namespace DirectUI
{
    class Element;
    class ElementProvider;
    class ProviderProxy;
}

namespace DirectUI
{
    class Element;
    class ProviderProxy;

}

namespace DirectUI
{
    class ElementProvider
        : public RefcountBase,
          public IRawElementProviderAdviseEvents,
          public IRawElementProviderFragment,
          public IRawElementProviderSimple2
    {
    public:
        virtual ~ElementProvider(void);
        virtual auto GetProxyCreator(void) -> ProviderProxy* (__cdecl *)(Element*);
        virtual Element const volatile* GetElement(void);
        virtual void TossElement(void);
        ElementProvider(void);
        virtual unsigned long AddRef(void) override;
        virtual long AdviseEventAdded(int, tagSAFEARRAY*) override;
        virtual long AdviseEventRemoved(int, tagSAFEARRAY*) override;
        static long Create(Element*, InvokeHelper*, ElementProvider**);
        long DoInvokeArgs(int, ProviderProxy* (__cdecl *)(Element*), char*);
        Element const* GetElementKey(void);
        virtual long GetEmbeddedFragmentRoots(tagSAFEARRAY**) override;
        virtual long GetPatternProvider(int, IUnknown**) override;
        virtual long GetPropertyValue(int, tagVARIANT*) override;
        virtual long GetRuntimeId(tagSAFEARRAY**) override;
        virtual long Navigate(NavigateDirection, IRawElementProviderFragment**) override;
        virtual long QueryInterface(_GUID const&, void**) override;
        virtual unsigned long Release(void) override;
        virtual long SetFocus(void) override;
        virtual long ShowContextMenu(void) override;
        void TossPatternProvider(Schema::Pattern);
        virtual long get_BoundingRectangle(UiaRect*) override;
        virtual long get_FragmentRoot(IRawElementProviderFragmentRoot**) override;
        virtual long get_HostRawElementProvider(IRawElementProviderSimple**) override;
        virtual long get_ProviderOptions(ProviderOptions*) override;
    protected:
        virtual long Init(Element*, InvokeHelper*);
        long DoInvoke(int, ...);
    };

} // namespace DirectUI
