// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::EventManager -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "Schema.h"

namespace DirectUI
{
    class Element;
    class EventManager;
    class Value;

    class EventManager
    {
    public:
        EventManager& operator=(EventManager&&);
        EventManager& operator=(EventManager const&);
        static long AdviseEventAdded(int, tagSAFEARRAY*);
        static long AdviseEventRemoved(int, tagSAFEARRAY*);
        static void Close(void);
        static void DestroyListener(Element*);
        static long EndDefer(Element*);
        static long EventListener(Element*, Event*);
        static bool FWantAnyEvent(Element*);
        static long FireStructureChangedEvent(Element*, StructureChangeType);
        static long Init(void);
        static long OnToolTip(Element*, unsigned long);
        static long PropertyChangingListener(Element*, PropertyInfo const*, bool*);
        static long PropertyListener(Element*, PropertyInfo const*, int, Value*, Value*);
        static bool WantEvent(Schema::Event);
        static bool WantPropertyEvent(int);

        private:
        static long AddRectangleChange(Element*, bool, bool);
        static long GetBool(tagVARIANT*, Value*);
        static void GetExpandCollapseState(tagVARIANT*);
        static long GetInt(tagVARIANT*, Value*);
        static long GetString(tagVARIANT*, Value*);
        static void GetToggleState(tagVARIANT*);
        static long HandleAccChange(Element*, IRawElementProviderSimple*, Value*, Value*);
        static long HandleAccDesc(Element*, IRawElementProviderSimple*, Value*, Value*);
        static long HandleAccPatternChange(Element*, IRawElementProviderSimple*, unsigned int, unsigned int, int, tagVARIANT*, tagVARIANT*, void (__cdecl *)(tagVARIANT*));
        static long HandleAccRoleEvent(IRawElementProviderSimple*, Value*, Value*);
        static long HandleAccStateChange(IRawElementProviderSimple*, unsigned int, unsigned int, int, tagVARIANT*, tagVARIANT*, bool);
        static long HandleBoolProp(Element*, bool (__cdecl *)(Element*), IRawElementProviderSimple*, int, Value*, Value*);
        static long HandleChildrenEvent(Element*, Value*, Value*);
        static long HandleRangeValue(Element*, IRawElementProviderSimple*, Value*, Value*);
        static long HandleScrollPos(Element*, IRawElementProviderSimple*, Value*, Value*);
        static long HandleSelectedChange(IRawElementProviderSimple*, Value*);
        static long HandleStringProp(IRawElementProviderSimple*, int, Value*, Value*);
        static long HandleToggleValue(Element*, IRawElementProviderSimple*, Value*, Value*);
        static long HandleVisibilityChange(Element*, unsigned int);
        static long RaiseChildRemovedEvent(ElementRuntimeId const&, Element*);
        static long RaiseGeometryEventWorker(RectangleChange*, bool, bool, bool, bool);
        static long RaiseGeometryEvents(void);
        static long RaiseStructureChangedEvent(Element*, StructureChangeType);
        static long RaiseStructureEvents(void);
        static long RaiseVisibilityEvents(void);
        static bool WantEvent(Schema::Event, int);
        static const int cChangeBulk;
        static _RTL_CRITICAL_SECTION g_cs;
        static unsigned int* __ptr32 g_eventRegisteredMap;
        static bool g_fWantAnyEvent;
        static UiaArray<int>* g_pArrayPropertyEvent;
    };

} // namespace DirectUI
