// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::Expando -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class Expando;
    class Value;

    class Expando
    {
    public:
        Expando(Expando&&);
        Expando(Expando const&);
        Expando(void);
        virtual ~Expando(void);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        virtual void OnEvent(Event*);
        virtual long Add(Element**, unsigned int);
        virtual IClassInfo* GetClassInfoW(void);
        Expando& operator=(Expando&&);
        Expando& operator=(Expando const&);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        long Initialize(Element*, unsigned long*);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);

        protected:
        static unsigned short Arrow(void);
        static unsigned short Clipper(void);
        void UpdateChildren(Value*);

        private:
        static unsigned short _atmArrow;
        static unsigned short _atmClipper;
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
