// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::ExpandoButtonGlyph -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class ExpandoButtonGlyph;

    class ExpandoButtonGlyph
    {
    public:
        ExpandoButtonGlyph(ExpandoButtonGlyph const&);
        ExpandoButtonGlyph(void);
        virtual ~ExpandoButtonGlyph(void);
        // ABI placeholder: real slot 1 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_1(void) = 0;
        virtual bool OnLostDialogFocus(IDialogElement*);
        // ABI placeholder: real slot 3 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_3(void) = 0;
        // ABI placeholder: real slot 4 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_4(void) = 0;
        virtual bool OnReceivedDialogFocus(IDialogElement*);
        // ABI placeholder: real slot 6 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_6(void) = 0;
        // ABI placeholder: real slot 7 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_7(void) = 0;
        // ABI placeholder: real slot 8 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_8(void) = 0;
        // ABI placeholder: real slot 9 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_9(void) = 0;
        // ABI placeholder: real slot 10 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_10(void) = 0;
        // ABI placeholder: real slot 11 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_11(void) = 0;
        // ABI placeholder: real slot 12 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_12(void) = 0;
        // ABI placeholder: real slot 13 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_13(void) = 0;
        // ABI placeholder: real slot 14 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_14(void) = 0;
        // ABI placeholder: real slot 15 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_15(void) = 0;
        // ABI placeholder: real slot 16 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_16(void) = 0;
        // ABI placeholder: real slot 17 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_17(void) = 0;
        // ABI placeholder: real slot 18 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_18(void) = 0;
        // ABI placeholder: real slot 19 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_19(void) = 0;
        // ABI placeholder: real slot 20 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_20(void) = 0;
        // ABI placeholder: real slot 21 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_21(void) = 0;
        // ABI placeholder: real slot 22 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_22(void) = 0;
        // ABI placeholder: real slot 23 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_23(void) = 0;
        // ABI placeholder: real slot 24 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_24(void) = 0;
        // ABI placeholder: real slot 25 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_25(void) = 0;
        // ABI placeholder: real slot 26 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_26(void) = 0;
        // ABI placeholder: real slot 27 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_27(void) = 0;
        // ABI placeholder: real slot 28 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_28(void) = 0;
        // ABI placeholder: real slot 29 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_29(void) = 0;
        // ABI placeholder: real slot 30 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_30(void) = 0;
        // ABI placeholder: real slot 31 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_31(void) = 0;
        // ABI placeholder: real slot 32 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_32(void) = 0;
        // ABI placeholder: real slot 33 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_33(void) = 0;
        // ABI placeholder: real slot 34 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_34(void) = 0;
        virtual IClassInfo* GetClassInfoW(void);
        // ABI placeholder: real slot 36 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_36(void) = 0;
        // ABI placeholder: real slot 37 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_37(void) = 0;
        // ABI placeholder: real slot 38 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_38(void) = 0;
        // ABI placeholder: real slot 39 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_39(void) = 0;
        // ABI placeholder: real slot 40 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_40(void) = 0;
        // ABI placeholder: real slot 41 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_41(void) = 0;
        // ABI placeholder: real slot 42 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_42(void) = 0;
        // ABI placeholder: real slot 43 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_43(void) = 0;
        // ABI placeholder: real slot 44 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_44(void) = 0;
        // ABI placeholder: real slot 45 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_45(void) = 0;
        // ABI placeholder: real slot 46 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_ExpandoButtonGlyph_46(void) = 0;
        ExpandoButtonGlyph& operator=(ExpandoButtonGlyph const&);
        static long Create(unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        long Initialize(unsigned int, Element*, unsigned long*);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
