// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::FillLayout -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class FillLayout;
    class Layout;
    struct NavReference;
    class Value;

    class FillLayout
    {
    public:
        FillLayout(FillLayout const&);
        FillLayout(void);
        virtual ~FillLayout(void);
        virtual void DoLayout(Element*, int, int);
        virtual tagSIZE UpdateDesiredSize(Element*, int, int, Surface*);
        virtual Element* GetAdjacent(Element*, Element*, int, NavReference const*, unsigned long);
        FillLayout& operator=(FillLayout const&);
        static long Create(int, int*, Value**);
        static long Create(Layout**);
        void Initialize(void);
    };

} // namespace DirectUI
