// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::FontCache -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class FontCache;

    class FontCache
    {
    public:
        // ABI placeholder: real slot 0 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_FontCache_0(void) = 0;
        // ABI placeholder: real slot 1 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_FontCache_1(void) = 0;
        // ABI placeholder: real slot 2 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_FontCache_2(void) = 0;
        // ABI placeholder: real slot 3 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_FontCache_3(void) = 0;
        FontCache(FontCache&&);
        FontCache(FontCache const&);
        FontCache(void);
        FontCache& operator=(FontCache&&);
        FontCache& operator=(FontCache const&);
        static long InitProcess(void);
        static long InitThread(void);
        static void UninitProcess(void);
        static void UninitThread(void);
    };

} // namespace DirectUI
