// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::GridLayout -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class GridLayout;
    class Layout;
    struct NavReference;
    class Value;

    class GridLayout
    {
    public:
        // W5 CONTRACT: REJECTED -- this class cannot be
        // expressed in real-slot order with the current
        // pipeline model; canonical order is deliberate.
        // reason: virtual destructor would take slot 0,
        // but the real table's slot 0 is a method

        GridLayout(GridLayout const&);
        GridLayout(void);
        virtual ~GridLayout(void);
        GridLayout& operator=(GridLayout const&);
        static long Create(int, int, Layout**);
        static long Create(int, int*, Value**);
        virtual void DoLayout(Element*, int, int);
        virtual Element* GetAdjacent(Element*, Element*, int, NavReference const*, unsigned long);
        void Initialize(int, int);
        virtual tagSIZE UpdateDesiredSize(Element*, int, int, Surface*);

        protected:
        unsigned int GetCurrentCols(int);
        unsigned int GetCurrentCols(Element*);
        unsigned int GetCurrentRows(int);
        unsigned int GetCurrentRows(Element*);
    };

} // namespace DirectUI
