// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::GridProvider -- declarations derived from the real
// dui70.dll export table + PDB publics.
// W5 stage-2 MI emission: base-subobject vftables verified
// against pinned mi-tables.json (schema 2).
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "IGridProvider.h"

#include "PatternProvider_GridProvider_IGridProvider_3.h"

namespace DirectUI
{
    class Element;
    class ProviderProxy;
}

namespace DirectUI
{
    class GridProvider
        : public IGridProvider, public PatternProvider<GridProvider, IGridProvider, 3>
    {
    public:
        virtual ~GridProvider(void);
        GridProvider(void);
        virtual unsigned long AddRef(void) override;
        virtual long GetItem(int, int, IRawElementProviderSimple**) override;
        virtual auto GetProxyCreator(void) -> ProviderProxy* (__cdecl *)(Element*) override;
        virtual long QueryInterface(_GUID const&, void**) override;
        virtual unsigned long Release(void) override;
        virtual long get_ColumnCount(int*) override;
        virtual long get_RowCount(int*) override;
    };

} // namespace DirectUI
