// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::GridItemProxy -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class GridItemProxy;

    class GridItemProxy
    {
    public:
        GridItemProxy(GridItemProxy&&);
        GridItemProxy(GridItemProxy const&);
        GridItemProxy(void);
        GridItemProxy& operator=(GridItemProxy&&);
        GridItemProxy& operator=(GridItemProxy const&);
        static GridItemProxy* Create(Element*);
        virtual long DoMethod(int, char*);
        static bool IsPatternSupported(Element*);

        protected:
        virtual void Init(Element*);

        private:
        long GetColumn(int*);
        long GetContainingGrid(IRawElementProviderSimple**);
        long GetRow(int*);
    };

} // namespace DirectUI
