// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::GridLayout -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class GridLayout;
    class Layout;
    struct NavReference;
    class Value;

    class GridLayout
    {
    public:
        virtual void DoLayout(Element*, int, int);
        virtual tagSIZE UpdateDesiredSize(Element*, int, int, Surface*);
        // ABI placeholder: real slot 2 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_GridLayout_2(void) = 0;
        // ABI placeholder: real slot 3 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_GridLayout_3(void) = 0;
        // ABI placeholder: real slot 4 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_GridLayout_4(void) = 0;
        // ABI placeholder: real slot 5 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_GridLayout_5(void) = 0;
        // ABI placeholder: real slot 6 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_GridLayout_6(void) = 0;
        virtual Element* GetAdjacent(Element*, Element*, int, NavReference const*, unsigned long);
        GridLayout(GridLayout const&);
        GridLayout(void);
        virtual ~GridLayout(void);
        GridLayout& operator=(GridLayout const&);
        static long Create(int, int, Layout**);
        static long Create(int, int*, Value**);
        void Initialize(int, int);

        protected:
        unsigned int GetCurrentCols(int);
        unsigned int GetCurrentCols(Element*);
        unsigned int GetCurrentRows(int);
        unsigned int GetCurrentRows(Element*);
    };

} // namespace DirectUI
