// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::GridItemProvider -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "IProvider.h"

#include "RefcountBase.h"

namespace DirectUI
{
    class Element;
    class ProviderProxy;

    class GridItemProvider
        : public IProvider, public RefcountBase
    {
    public:
        // W5 CONTRACT: REJECTED -- this class cannot be
        // expressed in real-slot order with the current
        // pipeline model; canonical order is deliberate.
        // reason: exported virtual(s) not in the primary
        // vtable (secondary/MI subobject table): GetProxyCreator

        GridItemProvider(void);
        virtual ~GridItemProvider(void);
        virtual unsigned long AddRef(void);
        virtual auto GetProxyCreator(void) -> ProviderProxy* (__cdecl *)(Element*);
        virtual long QueryInterface(_GUID const&, void**);
        virtual unsigned long Release(void);
        virtual long get_Column(int*);
        virtual long get_ColumnSpan(int*);
        virtual long get_ContainingGrid(IRawElementProviderSimple**);
        virtual long get_Row(int*);
        virtual long get_RowSpan(int*);
    };

} // namespace DirectUI
