// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::GridProxy -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include <UIAutomationCore.h>  // Option D quarantine: SDK UIA types

namespace DirectUI
{
    class Element;
    class GridProxy;

    class GridProxy
    {
    public:
        virtual long DoMethod(int, char*);

        protected:
        virtual void Init(Element*);

        public:
        GridProxy(GridProxy&&);
        GridProxy(GridProxy const&);
        GridProxy(void);
        GridProxy& operator=(GridProxy&&);
        GridProxy& operator=(GridProxy const&);
        static GridProxy* Create(Element*);
        static bool IsPatternSupported(Element*);

        private:
        long GetColumnCount(int*);
        long GetItem(unsigned int, unsigned int, IRawElementProviderSimple**);
        long GetRowCount(int*);
    };

} // namespace DirectUI
