// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::HWNDElementProvider -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "RefcountBase.h"

#include "UIAutomationCore.h"

#include "UIAutomationCore.h"

#include "UIAutomationCore.h"

namespace DirectUI
{
    class Element;
    class HWNDElement;
    class HWNDElementProvider;
    class ProviderProxy;

    class HWNDElementProvider
        : public IRawElementProviderAdviseEvents, public IRawElementProviderFragment, public IRawElementProviderSimple2, public RefcountBase
    {
    public:
        HWNDElementProvider(void);
        virtual ~HWNDElementProvider(void);
        virtual long QueryInterface(_GUID const&, void**);
        virtual unsigned long AddRef(void);
        virtual unsigned long Release(void);
        virtual long ElementProviderFromPoint(double, double, IRawElementProviderFragment**);
        virtual long GetFocus(IRawElementProviderFragment**);
        virtual auto GetProxyCreator(void) -> ProviderProxy* (__cdecl *)(Element*);

        protected:
        virtual long Init(HWNDElement*, InvokeHelper*);

        public:
        static long Create(HWNDElement*, InvokeHelper*, HWNDElementProvider**);
    };

} // namespace DirectUI
