// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::HWNDHost -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "Element.h"

namespace DirectUI
{
    class Element;
    class HWNDHost;
    class Value;

    class HWNDHost
        : public Element
    {
    public:
        HWNDHost(HWNDHost const&);
        HWNDHost(void);
        virtual ~HWNDHost(void);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        virtual void OnInput(InputEvent*);
        virtual void OnDestroy(void);
        virtual void OnEvent(Event*);
        virtual void Paint(HDC__*, tagRECT const*, tagRECT const*, tagRECT*, tagRECT*);
        virtual void SetKeyFocus(void);
        virtual unsigned int MessageCallback(tagGMSG*);

        protected:
        virtual void OnHosted(Element*);
        virtual void OnUnHosted(Element*);

        public:
        virtual bool GetKeyFocused(void);
        virtual IClassInfo* GetClassInfoW(void);

        private:
        long GetAccessibleImpl(IAccessible**, bool);
        static unsigned int const g_rgMouseMap[1][3];
        static IClassInfo* s_pClassInfo;

        public:
        virtual long GetAccessibleImpl(IAccessible**);
        virtual HWND__* GetHWND(void);
        virtual bool OnMessage(unsigned int, unsigned __int64, __int64, __int64*);
        virtual bool OnNotify(unsigned int, unsigned __int64, __int64, __int64*);
        virtual bool OnSysChar(unsigned short);
        virtual bool OnSinkThemeChanged(unsigned int, unsigned __int64, __int64, __int64*);
        virtual bool OnCtrlThemeChanged(unsigned int, unsigned __int64, __int64, __int64*);
        virtual void OnWindowStyleChanged(unsigned __int64, tagSTYLESTRUCT const*);
        virtual int OnAdjustWindowSize(int, int, unsigned int);
        virtual void SetWindowDirection(HWND__*);

        protected:
        virtual HWND__* CreateHWND(HWND__*);
        virtual bool EraseBkgnd(HDC__*, __int64*);

        public:
        HWNDHost& operator=(HWNDHost const&);
        static PropertyInfo const* BackgroundOwnerIDProp(void);
        static long Create(unsigned int, unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        void Detach(void);
        unsigned short GetBackgroundOwnerID(void);
        static IClassInfo* GetClassInfoPtr(void);
        long GetClientAccessibleImpl(IAccessible**);
        HWND__* GetHWNDParent(void);
        bool GetOptimizeMove(void);
        bool GetTransparent(void);
        long Initialize(unsigned int, unsigned int, Element*, unsigned long*);
        static PropertyInfo const* OptimizeMoveProp(void);
        static long Register(void);
        long SetBackgroundOwnerID(unsigned short const*);
        static void SetClassInfoPtr(IClassInfo*);
        long SetOptimizeMove(bool);
        long SetTransparent(bool);
        static PropertyInfo const* ThemeChangedProp(void);
        static PropertyInfo const* TransparentProp(void);

        protected:
        static void AttachCtrlSubclassProc(HWND__*);
        HWND__* CreateAccNameLabel(HWND__*);
        static __int64 CtrlSubclassProc(HWND__*, unsigned int, unsigned __int64, __int64);
        Element* GetBackgroundOwner(void);
        HFONT__* GetFont(void);
        bool GetStaticColor(HDC__*, HBRUSH__**);
        int GetThemeChanged(void);
        bool IsMoveDeferred(void);
        void PrintRTLControl(HDC__*, HDC__*, tagRECT const&);
        long SetThemeChanged(int);
        void SyncBackground(void);
        void SyncDirection(void);
        void SyncFont(void);
        void SyncForeground(void);
        void SyncParent(void);
        void SyncRect(unsigned int, bool);
        void SyncStyle(void);
        void SyncText(void);
        void SyncVisible(void);
        int VerifyParentage(void);

        private:
        void ApplySinkRegion(tagRECT const*, bool);
        void GetSinkRect(tagRECT const*, tagRECT*);
        bool HaveWin32Focus(void);
        void SyncColorsAndFonts(void);
        void UnvirtualizePosition(void);
        static int _CtrlWndProc(void*, HWND__*, unsigned int, unsigned __int64, __int64, __int64*);
        void _DeleteCtrlWnd(void);
        static int _SinkWndProc(void*, HWND__*, unsigned int, unsigned __int64, __int64, __int64*);
    };

} // namespace DirectUI
