// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::IDataEntry -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    struct IDataEntry;

    struct IDataEntry
    {
    public:
        IDataEntry(IDataEntry const&);
        IDataEntry(void);
        virtual ~IDataEntry(void);
        // ABI placeholder: real slot 1 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_IDataEntry_1(void) = 0;
        // ABI placeholder: real slot 2 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_IDataEntry_2(void) = 0;
        IDataEntry& operator=(IDataEntry const&);
    };

} // namespace DirectUI
