// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// IExpandCollapseProvider -- UIA pattern interface synthesized
// from the pinned mi-tables.json primary vftable of
// DirectUI::ExpandCollapseProvider (slot order == declaration order).
// NOTE: global scope (the pinned mangled template args carry
//       no @DirectUI@@ qualifier for the interface parameter).
#pragma once

#include "dui_abi_types.h"

// Mode semantics (Option D):
//   default (provider-only / SDK-first alike): this header
//     includes the SDK UIAutomationCore.h and the SDK MIDL
//     interface of this name is THE base in the TU; the
//     generated struct below stays yield-guarded out
//     (pinned-signature documentation).
//   DUI_ABI_PROVIDER_ABI_REQUIRED: HARD ERROR. This header is
//     INHERENTLY SDK-coupled -- its method signatures use SDK
//     UIA types (IRawElementProviderSimple*, ScrollAmount,
//     ToggleState*, ...), so no SDK-free form of it can
//     compile. An ABI-critical TU that must not mix SDK UIA
//     interfaces and generated ABI structs must not include
//     this header at all. The check runs BEFORE the SDK
//     include so the error reports the mode violation, not
//     the include's side effect.
#ifdef DUI_ABI_PROVIDER_ABI_REQUIRED
#error "DUI_ABI_PROVIDER_ABI_REQUIRED: pattern interface headers are SDK-coupled by signature; a provider-ABI-required TU must not include this header (the SDK UIAutomationCore.h interfaces are mandatory here)"
#endif

// Option D: this interface's methods use SDK UIA types
// (IRawElementProviderSimple*, ScrollAmount, ...). The SDK
// header is therefore pulled HERE, before the yield check --
// the SDK MIDL interface is the base in every TU.
#include <UIAutomationCore.h>

struct IExpandCollapseProvider;

#ifndef __uiautomationcore_h__
// auto-yield: the SDK UIA header already defined this
// interface name; its MIDL interface owns the name here.
// The generated struct below is the pinned-signature
// documentation; it never defines while the SDK guard is
// set. If an SDK update renames the guard, this struct
// reactivates and C2011s loudly (fail-visible).
struct IExpandCollapseProvider
{
public:
    virtual long QueryInterface(_GUID const&, void**) = 0;
    virtual unsigned long AddRef(void) = 0;
    virtual unsigned long Release(void) = 0;
    virtual long Expand(void) = 0;
    virtual long Collapse(void) = 0;
    virtual long get_ExpandCollapseState(ExpandCollapseState*) = 0;
};
#endif // __uiautomationcore_h__
