// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::IGridItemProvider -- UIA pattern interface synthesized
// from the pinned mi-tables.json primary vftable of
// DirectUI::GridItemProvider (slot order == declaration order).
#pragma once

#include "dui_abi_types.h"

namespace DirectUI
{
    struct IGridItemProvider;

    struct IGridItemProvider
    {
    public:
        virtual long QueryInterface(_GUID const&, void**) = 0;
        virtual unsigned long AddRef(void) = 0;
        virtual unsigned long Release(void) = 0;
        virtual long get_Row(int*) = 0;
        virtual long get_Column(int*) = 0;
        virtual long get_ColumnSpan(int*) = 0;
        virtual long get_RowSpan(int*) = 0;
        virtual long get_ContainingGrid(IRawElementProviderSimple**) = 0;
    };

} // namespace DirectUI
