// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// IInvokeProvider -- UIA pattern interface synthesized
// from the pinned mi-tables.json primary vftable of
// DirectUI::InvokeProvider (slot order == declaration order).
// NOTE: global scope (the pinned mangled template args carry
//       no @DirectUI@@ qualifier for the interface parameter).
#pragma once

#include "dui_abi_types.h"

struct IInvokeProvider;

struct IInvokeProvider
{
public:
    virtual long QueryInterface(_GUID const&, void**) = 0;
    virtual unsigned long AddRef(void) = 0;
    virtual unsigned long Release(void) = 0;
    virtual long Invoke(void) = 0;
};
