// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::InvokeProvider -- declarations derived from the real
// dui70.dll export table + PDB publics.
// W5 stage-2 MI emission: base-subobject vftables verified
// against pinned mi-tables.json (schema 2).
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "IInvokeProvider.h"

#include "PatternProvider_InvokeProvider_IInvokeProvider_0.h"

namespace DirectUI
{
    class Element;
    class ProviderProxy;
}

namespace DirectUI
{
    class InvokeProvider
        : public IInvokeProvider, public PatternProvider<InvokeProvider, IInvokeProvider, 0>
    {
    public:
        virtual ~InvokeProvider(void);
        InvokeProvider(void);
        virtual unsigned long AddRef(void) override;
        virtual auto GetProxyCreator(void) -> ProviderProxy* (__cdecl *)(Element*) override;
        virtual long Invoke(void) override;
        virtual long QueryInterface(_GUID const&, void**) override;
        virtual unsigned long Release(void) override;
    };

} // namespace DirectUI
