// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::IProvider -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class IProvider
    {
    public:
    public:
        // W5 stage-2 schema-2: the real single
        // interface method (pinned mi-tables.json:
        // IProvider secondary length 1, manual input).
        // Return type: the fn-pointer shape comes from the
        // concrete overrides' pinned signature
        // (?GetProxyCreator@...P6APEAVProviderProxy@2@PEAVElement@2@@ZXZ).
        class ProviderProxy;
        class Element;
        typedef ProviderProxy* (__cdecl* ProxyCreatorFn)(Element*);
        virtual ProxyCreatorFn GetProxyCreator(void) = 0;

    private:
        // ICF-fold ctor/assign exports: compiler
        // artifacts, not interface methods;
        // defined out-of-line in the stub TU.
        IProvider(void);
        IProvider(IProvider const&);
        IProvider(IProvider&&);
        IProvider& operator=(IProvider const&);
        IProvider& operator=(IProvider&&);

    };

} // namespace DirectUI
