// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::IProvider -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class IProvider;

    class IProvider
    {
    public:
    public:
        virtual unsigned long AddRef(void) = 0;

        IProvider(IProvider&&);
        IProvider(IProvider const&);
        IProvider(void);
        IProvider& operator=(IProvider&&);
        IProvider& operator=(IProvider const&);
    };

} // namespace DirectUI
