// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::ISelectionItemProvider -- UIA pattern interface synthesized
// from the pinned mi-tables.json primary vftable of
// DirectUI::SelectionItemProvider (slot order == declaration order).
#pragma once

#include "dui_abi_types.h"

namespace DirectUI
{
    struct ISelectionItemProvider;

    struct ISelectionItemProvider
    {
    public:
        virtual long QueryInterface(_GUID const&, void**) = 0;
        virtual unsigned long AddRef(void) = 0;
        virtual unsigned long Release(void) = 0;
        virtual long Select(void) = 0;
        virtual long AddToSelection(void) = 0;
        virtual long RemoveFromSelection(void) = 0;
        virtual long get_IsSelected(int*) = 0;
        virtual long get_SelectionContainer(IRawElementProviderSimple**) = 0;
    };

} // namespace DirectUI
