// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::ITableItemProvider -- UIA pattern interface synthesized
// from the pinned mi-tables.json primary vftable of
// DirectUI::TableItemProvider (slot order == declaration order).
#pragma once

#include "dui_abi_types.h"

namespace DirectUI
{
    struct ITableItemProvider;

    struct ITableItemProvider
    {
    public:
        virtual long QueryInterface(_GUID const&, void**) = 0;
        virtual unsigned long AddRef(void) = 0;
        virtual unsigned long Release(void) = 0;
        virtual long GetRowHeaderItems(tagSAFEARRAY**) = 0;
        virtual long GetColumnHeaderItems(tagSAFEARRAY**) = 0;
    };

} // namespace DirectUI
