// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::ItemList -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    struct NavReference;
    class Value;

    class ItemList
    {
    public:
        ItemList(void);
        virtual ~ItemList(void);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        virtual Element* GetAdjacent(Element*, int, NavReference const*, unsigned long);
        virtual IClassInfo* GetClassInfoW(void);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        bool IsReorderable(void);
        static long Register(void);
        long SetReorderable(bool);
    };

} // namespace DirectUI
