// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// IToggleProvider -- UIA pattern interface synthesized
// from the pinned mi-tables.json primary vftable of
// DirectUI::ToggleProvider (slot order == declaration order).
// NOTE: global scope (the pinned mangled template args carry
//       no @DirectUI@@ qualifier for the interface parameter).
#pragma once

#include "dui_abi_types.h"

struct IToggleProvider;

struct IToggleProvider
{
public:
    virtual long QueryInterface(_GUID const&, void**) = 0;
    virtual unsigned long AddRef(void) = 0;
    virtual unsigned long Release(void) = 0;
    virtual long Toggle(void) = 0;
    virtual long get_ToggleState(ToggleState*) = 0;
};
