// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::IXElementCP -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class IXElementCP;

    class IXElementCP
    {
    public:
    public:
        virtual long OnIXElementCPVirt(void) { return 0; }

        IXElementCP(IXElementCP&&);
        IXElementCP(IXElementCP const&);
        IXElementCP(void);
        IXElementCP& operator=(IXElementCP&&);
        IXElementCP& operator=(IXElementCP const&);
    };

} // namespace DirectUI
