// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::IXProviderCP -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class DUIXmlParser;
    class Element;
    class HWNDElement;
    class IXProviderCP;

    class IXProviderCP
    {
    public:
        // Rule E: slot 0 recovered from IXProviderCP secondary table (TaskPage).
        virtual long CreateDUICP(HWNDElement*, HWND__*, HWND__*, Element**, DUIXmlParser**) = 0;
        // Rule E: slot 1 recovered from IXProviderCP secondary table (TaskPage).
        virtual long CreateParserCP(DUIXmlParser**) = 0;
        // ABI placeholder: real slot 2 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_IXProviderCP_2(void) = 0;
        IXProviderCP(IXProviderCP&&);
        IXProviderCP(IXProviderCP const&);
        IXProviderCP(void);
        IXProviderCP& operator=(IXProviderCP&&);
        IXProviderCP& operator=(IXProviderCP const&);
    };

} // namespace DirectUI
