// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::LinkedList -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class LinkedList;
    class LinkedListNode;

    class LinkedList
    {
    public:
        LinkedList(void);
        ~LinkedList(void);
        LinkedList& operator=(LinkedList const&);
        void Add(LinkedListNode*);
        void Remove(LinkedListNode*);
        LinkedListNode* RemoveTail(void);
    };

} // namespace DirectUI
