// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::ModernProgressBar -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class Value;

    class ModernProgressBar
    {
    public:
        ModernProgressBar(void);
        virtual ~ModernProgressBar(void);
        static long Create(Element*, unsigned long*, Element**);
        static PropertyInfo const* DeterminateProp(void);
        static IClassInfo* GetClassInfoPtr(void);
        virtual IClassInfo* GetClassInfoW(void);
        int GetMaximum(void);
        int GetMinimum(void);
        int GetPosition(void);
        int GetState(void);
        bool IsActivityOccuring(void);
        bool IsAddLayeredRef(void);
        bool IsAutoHeight(void);
        bool IsDeterminate(void);
        bool IsIndependentAnimations(void);
        bool IsSmoothFillAnimation(void);
        static PropertyInfo const* MaximumProp(void);
        static PropertyInfo const* MinimumProp(void);
        static PropertyInfo const* PositionProp(void);
        static long Register(void);
        long SetActivityOccuring(bool);
        long SetAddLayeredRef(bool);
        long SetAutoHeight(bool);
        long SetDeterminate(bool);
        long SetIndependentAnimations(bool);
        long SetMaximum(int);
        long SetMinimum(int);
        long SetPosition(int);
        long SetSmoothFillAnimation(bool);
        long SetState(int);
        static PropertyInfo const* StateProp(void);

        protected:
        virtual void OnDestroy(void);
        virtual void OnHosted(Element*);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        virtual void OnUnHosted(Element*);
        virtual void Paint(HDC__*, tagRECT const*, tagRECT const*, tagRECT*, tagRECT*);
    };

} // namespace DirectUI
