// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::ModernProgressRing -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class Value;

    class ModernProgressRing
    {
    public:
        ModernProgressRing(void);
        virtual ~ModernProgressRing(void);

        protected:
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        virtual void OnDestroy(void);
        virtual void Paint(HDC__*, tagRECT const*, tagRECT const*, tagRECT*, tagRECT*);
        virtual void OnHosted(Element*);
        virtual void OnUnHosted(Element*);

        public:
        virtual IClassInfo* GetClassInfoW(void);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        bool IsActivityOccuring(void);
        bool IsAddLayeredRef(void);
        static long Register(void);
        long SetActivityOccuring(bool);
        long SetAddLayeredRef(bool);
    };

} // namespace DirectUI
