// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::ModernProgressBarRangeValueProxy -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class ModernProgressBarRangeValueProxy;

    class ModernProgressBarRangeValueProxy
    {
    public:
        ModernProgressBarRangeValueProxy(ModernProgressBarRangeValueProxy&&);
        ModernProgressBarRangeValueProxy(ModernProgressBarRangeValueProxy const&);
        ModernProgressBarRangeValueProxy(void);
        ModernProgressBarRangeValueProxy& operator=(ModernProgressBarRangeValueProxy&&);
        ModernProgressBarRangeValueProxy& operator=(ModernProgressBarRangeValueProxy const&);
        virtual long DoMethod(int, char*);

        protected:
        virtual void Init(Element*);
    };

} // namespace DirectUI
