// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::Navigator -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Browser;
    class Element;
    class Navigator;
    class Value;

    class Navigator
    {
    public:
        Navigator(Navigator&&);
        Navigator(Navigator const&);
        Navigator(void);
        virtual ~Navigator(void);
        Navigator& operator=(Navigator&&);
        Navigator& operator=(Navigator const&);
        static UID ActionInitiated(void);
        static long Create(Element*, unsigned long*, Element**);
        Browser* GetBrowser(void);
        static IClassInfo* GetClassInfoPtr(void);
        virtual IClassInfo* GetClassInfoW(void);
        unsigned short const* GetTargetPage(Value**);
        long Initialize(Element*, unsigned long*);
        virtual void OnEvent(Event*);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);
        long SetTargetPage(unsigned short const*);
        static PropertyInfo const* TargetPageProp(void);

        private:
        void FireNavigationEvent(void);
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
