// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::NineGridLayout -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class Layout;
    struct NavReference;
    class NineGridLayout;
    class Value;

    class NineGridLayout
    {
    public:
        virtual void DoLayout(Element*, int, int);
        virtual tagSIZE UpdateDesiredSize(Element*, int, int, Surface*);
        virtual void OnAdd(Element*, Element**, unsigned int);
        virtual void OnRemove(Element*, Element**, unsigned int);
        virtual void OnLayoutPosChanged(Element*, Element*, int, int);
        // ABI placeholder: real slot 5 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_NineGridLayout_5(void) = 0;
        // ABI placeholder: real slot 6 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_NineGridLayout_6(void) = 0;
        virtual Element* GetAdjacent(Element*, Element*, int, NavReference const*, unsigned long);
        NineGridLayout(NineGridLayout const&);
        NineGridLayout(void);
        virtual ~NineGridLayout(void);
        NineGridLayout& operator=(NineGridLayout const&);
        static long Create(int, int*, Value**);
        static long Create(Layout**);
        void Initialize(void);

        private:
        void _UpdateTileList(int, Element*);
    };

} // namespace DirectUI
