// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::Pages -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class Pages;

    class Pages
    {
    public:
        Pages(Pages&&);
        Pages(Pages const&);
        Pages(void);
        virtual ~Pages(void);
        virtual long Add(Element**, unsigned int);
        virtual IClassInfo* GetClassInfoW(void);
        Pages& operator=(Pages&&);
        Pages& operator=(Pages const&);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        unsigned int GetCount(void);
        Element* GetPage(unsigned int);
        Element* GetPage(unsigned short const*);
        long Initialize(Element*, unsigned long*);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);
        void SetNoBrowseOnFirstAdd(void);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
