// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::PatternProvider<GridProvider, IGridProvider, 3> -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "IProvider.h"

#include "RefcountBase.h"

#include "GridProvider.h"

namespace DirectUI
{
    class Element;
    class ElementProvider;
    class ProviderProxy;

    template <typename PROVIDER, typename INTERFACE, int ID>
    class PatternProvider;

    template <>
    class PatternProvider<GridProvider, IGridProvider, 3>
        : public IProvider, public RefcountBase
    {
    public:
        PatternProvider<GridProvider, IGridProvider, 3>(void);
        virtual ~PatternProvider<GridProvider, IGridProvider, 3>(void);
        static long Create(ElementProvider*, IUnknown**);
        virtual auto GetProxyCreator(void) -> ProviderProxy* (__cdecl *)(Element*);
        virtual void Init(ElementProvider*);

        protected:
        long DoInvoke(int, ...);
    };

} // namespace DirectUI
