// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::ProgressRangeValueProxy -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class ProgressRangeValueProxy;

    class ProgressRangeValueProxy
    {
    public:
        ProgressRangeValueProxy(ProgressRangeValueProxy&&);
        ProgressRangeValueProxy(ProgressRangeValueProxy const&);
        ProgressRangeValueProxy(void);
        ProgressRangeValueProxy& operator=(ProgressRangeValueProxy&&);
        ProgressRangeValueProxy& operator=(ProgressRangeValueProxy const&);
        virtual long DoMethod(int, char*);

        protected:
        virtual void Init(Element*);
    };

} // namespace DirectUI
