// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::ProviderProxy -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class ProviderProxy;

    class ProviderProxy
    {
    public:
        ProviderProxy(ProviderProxy&&);
        ProviderProxy(ProviderProxy const&);
        ProviderProxy& operator=(ProviderProxy&&);
        ProviderProxy& operator=(ProviderProxy const&);

        protected:
        ProviderProxy(void);
        virtual void Init(Element*);
    };

} // namespace DirectUI
