// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::PText -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    struct IDataEntry;
    class PText;
    class Value;

    class PText
    {
    public:
        PText(PText const&);
        PText(void);
        virtual ~PText(void);
        PText& operator=(PText const&);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        virtual IClassInfo* GetClassInfoW(void);
        long Initialize(Element*, unsigned long*);
        virtual bool OnPropertyChanging(PropertyInfo const*, int, Value*, Value*);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);
        void SetDataEntry(IDataEntry*);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
