// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::RadioButtonGlyph -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class RadioButtonGlyph;

    class RadioButtonGlyph
    {
    public:
        RadioButtonGlyph(RadioButtonGlyph const&);
        RadioButtonGlyph(void);
        virtual ~RadioButtonGlyph(void);
        virtual bool OnLostDialogFocus(IDialogElement*);
        virtual bool OnReceivedDialogFocus(IDialogElement*);
        virtual IClassInfo* GetClassInfoW(void);
        RadioButtonGlyph& operator=(RadioButtonGlyph const&);
        static long Create(unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        long Initialize(unsigned int, Element*, unsigned long*);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
