// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::RangeValueProxy -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class RangeValueProxy;

    class RangeValueProxy
    {
    public:
        virtual long DoMethod(int, char*);

        protected:
        virtual void Init(Element*);
        RangeValueProxy(void);

        public:
        RangeValueProxy(RangeValueProxy&&);
        RangeValueProxy(RangeValueProxy const&);
        RangeValueProxy& operator=(RangeValueProxy&&);
        RangeValueProxy& operator=(RangeValueProxy const&);
        static RangeValueProxy* Create(Element*);
        static bool IsPatternSupported(Element*);
    };

} // namespace DirectUI
