// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::ResourceModuleHandles -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class ResourceModuleHandles;

    class ResourceModuleHandles
    {
    public:
        ResourceModuleHandles(void);
        ~ResourceModuleHandles(void);
        ResourceModuleHandles& operator=(ResourceModuleHandles const&);
        long GetHandle(unsigned short const*, HINSTANCE__**);

        private:
        static long volatile g_cRefCount;
    };

} // namespace DirectUI
