// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::RichText -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class Value;

    class RichText
    {
    public:
        RichText(void);
        virtual ~RichText(void);
        static PropertyInfo const* AliasedRenderingProp(void);
        static PropertyInfo const* BaselineProp(void);
        static PropertyInfo const* ColorFontPaletteIndexProp(void);
        static PropertyInfo const* ConstrainLayoutProp(void);
        static long Create(Element*, unsigned long*, Element**);
        static long CreateCache(unsigned int, IDUIRichTextCache**);
        static PropertyInfo const* DisableAccTextExtendProp(void);
        static PropertyInfo const* FontColorRunsProp(void);
        static PropertyInfo const* FontSizeRunsProp(void);
        static PropertyInfo const* FontWeightRunsProp(void);
        static IClassInfo* GetClassInfoPtr(void);
        virtual IClassInfo* GetClassInfoW(void);
        virtual tagSIZE GetContentSize(int, int, Surface*);
        IDWriteFactory* GetFactory(void);
        virtual long GetForegroundColorRef(unsigned long*);
        unsigned long GetLineCount(void);
        unsigned short GetShortcutChar(void);
        unsigned long GetTrimmedLineCount(void);
        long Initialize(Element*, unsigned long*);
        static PropertyInfo const* LineSpacingProp(void);
        static PropertyInfo const* LocaleProp(void);
        static PropertyInfo const* MapRunsToClustersProp(void);
        virtual void OnEvent(Event*);
        virtual void OnHosted(Element*);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        static PropertyInfo const* OverhangOffsetProp(void);
        virtual void Paint(HDC__*, tagRECT const*, tagRECT const*, tagRECT*, tagRECT*);
        static long Register(void);
        long SetAliasedRendering(bool);
        long SetBaseline(int);
        void SetCache(unsigned long, IDUIRichTextCache*);
        long SetColorFontPaletteIndex(int);
        long SetConstrainLayout(int);
        void SetDWriteFontCollection(IDWriteFontCollection*);
        void SetDWriteTextLayout(IDWriteTextLayout*);
        long SetDisableAccTextExtend(bool);
        long SetFontColorRuns(unsigned short const*);
        long SetFontSizeRuns(unsigned short const*);
        long SetFontWeightRuns(unsigned short const*);
        long SetLineSpacing(int);
        long SetLocale(unsigned short const*);
        long SetMapRunsToClusters(bool);
        void SetMaxLineCount(unsigned int);
        long SetOverhangOffset(int);
        long SetTypography(unsigned short const*);
        long SetTypographyRuns(unsigned short const*);
        long SetVerticalScript(bool);
        void StopUsingCache(void);
        static PropertyInfo const* TypographyProp(void);
        static PropertyInfo const* TypographyRunsProp(void);
        static PropertyInfo const* VerticalScriptProp(void);
    };

} // namespace DirectUI
