// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::RowLayout -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class Layout;
    struct NavReference;
    class RowLayout;
    class Value;

    class RowLayout
    {
    public:
        virtual void DoLayout(Element*, int, int);
        virtual tagSIZE UpdateDesiredSize(Element*, int, int, Surface*);
        // ABI placeholder: real slot 2 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_RowLayout_2(void) = 0;
        // ABI placeholder: real slot 3 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_RowLayout_3(void) = 0;
        // ABI placeholder: real slot 4 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_RowLayout_4(void) = 0;
        // ABI placeholder: real slot 5 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_RowLayout_5(void) = 0;
        // ABI placeholder: real slot 6 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_RowLayout_6(void) = 0;
        virtual Element* GetAdjacent(Element*, Element*, int, NavReference const*, unsigned long);
        RowLayout(RowLayout const&);
        RowLayout(void);
        virtual ~RowLayout(void);
        RowLayout& operator=(RowLayout const&);
        static long Create(int, unsigned int, unsigned int, Layout**);
        static long Create(int, int*, Value**);
        static long Create(unsigned int, unsigned int, Layout**);
        long Initialize(int, unsigned int, unsigned int);
    };

} // namespace DirectUI
