// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::SafeArrayAccessor<int> -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    template <typename T>
    class SafeArrayAccessor;

    template <>
    class SafeArrayAccessor<int>
    {
    public:
        SafeArrayAccessor<int>(void);
        ~SafeArrayAccessor<int>(void);
        operator int*(void);
        long Access(tagSAFEARRAY*, unsigned short);
        int Count(void);
    };

} // namespace DirectUI
