// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::ScrollBar -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "Element.h"

#include "BaseScrollBar.h"

namespace DirectUI
{
    class Element;
    class ScrollBar;
    class Value;

    class ScrollBar
        : public Element, public BaseScrollBar
    {
    public:
        ScrollBar(ScrollBar const&);
        ScrollBar(void);
        virtual ~ScrollBar(void);
        ScrollBar& operator=(ScrollBar const&);
        static long Create(Element*, unsigned long*, Element**);
        static long Create(bool, Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        virtual IClassInfo* GetClassInfoW(void);
        virtual Element* GetElement(void);
        virtual int GetLine(void);
        virtual int GetMaximum(void);
        virtual int GetMinimum(void);
        int GetOrder(void);
        virtual int GetPage(void);
        virtual int GetPosition(void);
        virtual bool GetProportional(void);
        bool GetVertical(void);
        long Initialize(bool, Element*, unsigned long*);
        static PropertyInfo const* LineProp(void);
        static PropertyInfo const* MaximumProp(void);
        static PropertyInfo const* MinimumProp(void);
        virtual void OnEvent(Event*);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        virtual bool OnPropertyChanging(PropertyInfo const*, int, Value*, Value*);
        static PropertyInfo const* OrderProp(void);
        static PropertyInfo const* PageProp(void);
        static PropertyInfo const* PositionProp(void);
        static PropertyInfo const* ProportionalProp(void);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);
        virtual long SetLine(int);
        virtual long SetMaximum(int);
        virtual long SetMinimum(int);
        long SetOrder(int);
        virtual long SetPage(int);
        virtual long SetPosition(int);
        long SetProportional(bool);
        long SetVertical(bool);
        static PropertyInfo const* VerticalProp(void);
        virtual void _SelfLayoutDoLayout(int, int);
        virtual tagSIZE _SelfLayoutUpdateDesiredSize(int, int, Surface*);

        protected:
        virtual long CreateButtons(void);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
