// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::ScrollViewer -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "Element.h"

#include "Interfaces.h"

namespace DirectUI
{
    class BaseScrollBar;
    class Element;
    class ScrollViewer;
    class Value;

    class ScrollViewer
        : public Element, public IElementListener
    {
    public:
        ScrollViewer(ScrollViewer const&);
        ScrollViewer(void);
        virtual ~ScrollViewer(void);
        ScrollViewer& operator=(ScrollViewer const&);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        virtual IClassInfo* GetClassInfoW(void);
        virtual void OnListenedPropertyChanged(Element*, PropertyInfo const*, int, Value*, Value*);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);

        protected:
        virtual long AddChildren(void);
        virtual long CreateScrollBars(void);
        virtual BaseScrollBar* GetHScroll(void);
        virtual BaseScrollBar* GetVScroll(void);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
