// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::ScrollProvider -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "IProvider.h"

#include "RefcountBase.h"

namespace DirectUI
{
    class Element;
    class ProviderProxy;

    class ScrollProvider
        : public IProvider, public RefcountBase
    {
    public:
        // W5 CONTRACT: REJECTED -- this class cannot be
        // expressed in real-slot order with the current
        // pipeline model; canonical order is deliberate.
        // reason: exported virtual(s) not in the primary
        // vtable (secondary/MI subobject table): GetProxyCreator

        ScrollProvider(void);
        virtual ~ScrollProvider(void);
        virtual unsigned long AddRef(void);
        virtual auto GetProxyCreator(void) -> ProviderProxy* (__cdecl *)(Element*);
        virtual long QueryInterface(_GUID const&, void**);
        virtual unsigned long Release(void);
        virtual long Scroll(ScrollAmount, ScrollAmount);
        virtual long SetScrollPercent(double, double);
        virtual long get_HorizontalScrollPercent(double*);
        virtual long get_HorizontalViewSize(double*);
        virtual long get_HorizontallyScrollable(int*);
        virtual long get_VerticalScrollPercent(double*);
        virtual long get_VerticalViewSize(double*);
        virtual long get_VerticallyScrollable(int*);
    };

} // namespace DirectUI
