// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::ScrollBarRangeValueProxy -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class ScrollBarRangeValueProxy;

    class ScrollBarRangeValueProxy
    {
    public:
        virtual long DoMethod(int, char*);

        protected:
        virtual void Init(Element*);

        public:
        ScrollBarRangeValueProxy(ScrollBarRangeValueProxy&&);
        ScrollBarRangeValueProxy(ScrollBarRangeValueProxy const&);
        ScrollBarRangeValueProxy(void);
        ScrollBarRangeValueProxy& operator=(ScrollBarRangeValueProxy&&);
        ScrollBarRangeValueProxy& operator=(ScrollBarRangeValueProxy const&);
    };

} // namespace DirectUI
