// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::SelectionItemProxy -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class SelectionItemProxy;

    class SelectionItemProxy
    {
    public:
        SelectionItemProxy(SelectionItemProxy&&);
        SelectionItemProxy(SelectionItemProxy const&);
        SelectionItemProxy& operator=(SelectionItemProxy&&);
        SelectionItemProxy& operator=(SelectionItemProxy const&);
        static SelectionItemProxy* Create(Element*);
        virtual long DoMethod(int, char*);
        static bool IsPatternSupported(Element*);

        protected:
        SelectionItemProxy(void);
        virtual void Init(Element*);
    };

} // namespace DirectUI
