// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::SelectionProxy -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class SelectionProxy;

    class SelectionProxy
    {
    public:
        virtual long DoMethod(int, char*);

        protected:
        virtual void Init(Element*);
        SelectionProxy(void);

        public:
        SelectionProxy(SelectionProxy&&);
        SelectionProxy(SelectionProxy const&);
        SelectionProxy& operator=(SelectionProxy&&);
        SelectionProxy& operator=(SelectionProxy const&);
        static SelectionProxy* Create(Element*);
        static bool IsPatternSupported(Element*);
    };

} // namespace DirectUI
