// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::Selector -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    struct NavReference;
    class Selector;
    class Value;

    class Selector
    {
    public:
        Selector(Selector const&);
        Selector(void);
        virtual ~Selector(void);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        virtual void OnInput(InputEvent*);
        virtual void OnKeyFocusMoved(Element*, Element*);
        virtual void OnEvent(Event*);
        virtual Element* GetAdjacent(Element*, int, NavReference const*, unsigned long);
        virtual IClassInfo* GetClassInfoW(void);
        virtual long SetSelection(Element*);
        Selector& operator=(Selector const&);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        Element* GetSelection(void);
        long Initialize(Element*, unsigned long*);
        static long Register(void);
        static UID SelectionChange(void);
        static PropertyInfo const* SelectionProp(void);
        static void SetClassInfoPtr(IClassInfo*);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
