// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::SelectionProvider -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "IProvider.h"

#include "RefcountBase.h"

namespace DirectUI
{
    class Element;
    class ProviderProxy;

    class SelectionProvider
        : public IProvider, public RefcountBase
    {
    public:
        SelectionProvider(void);
        virtual ~SelectionProvider(void);
        virtual long QueryInterface(_GUID const&, void**);
        virtual unsigned long AddRef(void);
        virtual unsigned long Release(void);
        virtual long GetSelection(tagSAFEARRAY**);
        virtual long get_CanSelectMultiple(int*);
        virtual long get_IsSelectionRequired(int*);
        virtual auto GetProxyCreator(void) -> ProviderProxy* (__cdecl *)(Element*);
    };

} // namespace DirectUI
