// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::SemanticZoomToggle -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;

    class SemanticZoomToggle
    {
    public:
        static long Create(Element*, unsigned long*, Element**);
        virtual long DefaultAction(void);
        static IClassInfo* GetClassInfoPtr(void);
        virtual IClassInfo* GetClassInfoW(void);
        long Initialize(Element*, unsigned long*);
        static long Register(void);
        static UID Toggle(void);
        void UpdateToggleState(SemanticZoomToggleState, bool);
    };

} // namespace DirectUI
