// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::StyleSheet -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class StyleSheet;

    class StyleSheet
    {
    public:
        // ABI placeholder: real slot 0 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_StyleSheet_0(void) = 0;
        // ABI placeholder: real slot 1 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_StyleSheet_1(void) = 0;
        // ABI placeholder: real slot 2 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_StyleSheet_2(void) = 0;
        // ABI placeholder: real slot 3 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_StyleSheet_3(void) = 0;
        // ABI placeholder: real slot 4 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_StyleSheet_4(void) = 0;
        // ABI placeholder: real slot 5 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_StyleSheet_5(void) = 0;
        // ABI placeholder: real slot 6 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_StyleSheet_6(void) = 0;
        // ABI placeholder: real slot 7 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_StyleSheet_7(void) = 0;
        // ABI placeholder: real slot 8 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_StyleSheet_8(void) = 0;
        StyleSheet(StyleSheet&&);
        StyleSheet(StyleSheet const&);
        StyleSheet(void);
        StyleSheet& operator=(StyleSheet&&);
        StyleSheet& operator=(StyleSheet const&);
        static long Create(StyleSheet**);
    };

} // namespace DirectUI
