// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::TableProxy -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class TableProxy;

    class TableProxy
    {
    public:
        TableProxy(TableProxy&&);
        TableProxy(TableProxy const&);
        TableProxy(void);
        TableProxy& operator=(TableProxy&&);
        TableProxy& operator=(TableProxy const&);
        static TableProxy* Create(Element*);
        virtual long DoMethod(int, char*);
        static bool IsPatternSupported(Element*);

        protected:
        virtual void Init(Element*);
    };

} // namespace DirectUI
