// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::TableLayout -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class Layout;
    struct NavReference;
    class TableLayout;
    class Value;

    class TableLayout
    {
    public:
        // W5 CONTRACT: REJECTED -- this class cannot be
        // expressed in real-slot order with the current
        // pipeline model; canonical order is deliberate.
        // reason: virtual destructor would take slot 0,
        // but the real table's slot 0 is a method

        TableLayout(TableLayout const&);
        TableLayout(void);
        virtual ~TableLayout(void);
        TableLayout& operator=(TableLayout const&);
        static long Create(int, int*, Value**);
        virtual void DoLayout(Element*, int, int);
        virtual Element* GetAdjacent(Element*, Element*, int, NavReference const*, unsigned long);
        CellInfo* GetCellInfo(int);
        void Initialize(int, int, int, int*);
        static long InternalCreate(int, int, int, int*, Layout**);
        virtual tagSIZE UpdateDesiredSize(Element*, int, int, Surface*);
    };

} // namespace DirectUI
