// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::TableProvider -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "IProvider.h"

#include "RefcountBase.h"

namespace DirectUI
{
    class Element;
    class ProviderProxy;

    class TableProvider
        : public IProvider, public RefcountBase
    {
    public:
        TableProvider(void);
        virtual ~TableProvider(void);
        virtual unsigned long AddRef(void);
        virtual long GetColumnHeaders(tagSAFEARRAY**);
        virtual auto GetProxyCreator(void) -> ProviderProxy* (__cdecl *)(Element*);
        virtual long GetRowHeaders(tagSAFEARRAY**);
        virtual long QueryInterface(_GUID const&, void**);
        virtual unsigned long Release(void);
        virtual long get_RowOrColumnMajor(RowOrColumnMajor*);
    };

} // namespace DirectUI
