// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::TableItemProxy -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class TableItemProxy;

    class TableItemProxy
    {
    public:
        TableItemProxy(TableItemProxy&&);
        TableItemProxy(TableItemProxy const&);
        TableItemProxy(void);
        TableItemProxy& operator=(TableItemProxy&&);
        TableItemProxy& operator=(TableItemProxy const&);
        static TableItemProxy* Create(Element*);
        virtual long DoMethod(int, char*);
        static bool IsPatternSupported(Element*);

        protected:
        virtual void Init(Element*);
    };

} // namespace DirectUI
