// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::TableItemProvider -- declarations derived from the real
// dui70.dll export table + PDB publics.
// W5 stage-2 MI emission: base-subobject vftables verified
// against pinned mi-tables.json (schema 2).
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "ITableItemProvider.h"

#include "PatternProvider_TableItemProvider_ITableItemProvider_10.h"

namespace DirectUI
{
    class Element;
    class ProviderProxy;
}

namespace DirectUI
{
    class TableItemProvider
        : public ITableItemProvider, public PatternProvider<TableItemProvider, ITableItemProvider, 10>
    {
    public:
        virtual ~TableItemProvider(void);
        TableItemProvider(void);
        virtual unsigned long AddRef(void) override;
        virtual long GetColumnHeaderItems(tagSAFEARRAY**) override;
        virtual auto GetProxyCreator(void) -> ProviderProxy* (__cdecl *)(Element*) override;
        virtual long GetRowHeaderItems(tagSAFEARRAY**) override;
        virtual long QueryInterface(_GUID const&, void**) override;
        virtual unsigned long Release(void) override;
    };

} // namespace DirectUI
