// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::TaskPage -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "IXProviderCP.h"

#include "Interfaces.h"

namespace DirectUI
{
    class DUIXmlParser;
    class Element;
    class HWNDElement;
    class TaskPage;
    class Value;

    class TaskPage
        : public IElementListener, public IXProviderCP
    {
    public:
        TaskPage(TaskPage const&);
        TaskPage(void);
        virtual ~TaskPage(void);

        protected:
        virtual long LoadParser(DUIXmlParser**);

        private:
        long LoadPage(Element**, Element*, DUIXmlParser**);

        protected:
        virtual long LoadPage(HWNDElement*, HINSTANCE__*, Element**, DUIXmlParser**);
        virtual unsigned int GetPageRCID(void);
        virtual unsigned short const* GetPageResID(void);
        virtual void InitPropSheetPage(_PROPSHEETPAGEW*);
        virtual __int64 OnKillActive(void);
        virtual __int64 OnQueryCancel(void);
        virtual Element* OnQueryInitialFocus(void);
        virtual __int64 OnReset(void);
        virtual __int64 OnSetActive(void);
        virtual __int64 OnWizBack(void);
        virtual __int64 OnWizFinish(void);
        virtual __int64 OnWizNext(void);
        virtual bool OnMessage(unsigned int, unsigned __int64, __int64, __int64*);

        public:
        TaskPage& operator=(TaskPage const&);
        operator _PSP*(void);
        long DUICreatePropertySheetPage(HINSTANCE__*);
        HWND__* GetParentHWND(void);

        protected:
        Element* GetElement(void);
        virtual void OnListenedEvent(Element*, Event*);
        virtual void OnListenedInput(Element*, InputEvent*);
        virtual void OnListenedPropertyChanged(Element*, PropertyInfo const*, int, Value*, Value*);
        virtual bool OnListenedPropertyChanging(Element*, PropertyInfo const*, int, Value*, Value*);
        virtual void OnListenerAttach(Element*);
        virtual void OnListenerDetach(Element*);
        __int64 PropSheet_SendMessage(unsigned int, unsigned __int64, __int64);

        private:
        virtual long CreateDUICP(HWNDElement*, HWND__*, HWND__*, Element**, DUIXmlParser**);
        virtual long CreateParserCP(DUIXmlParser**);
        virtual void DestroyCP(void);
        void FreeComCtl32(void);
        long LoadComCtl32(void);
        int OnWndMsg(unsigned int, unsigned __int64, __int64, __int64*);
        static __int64 StaticXHostSubclassProc(HWND__*, unsigned int, unsigned __int64, __int64);
        static void StaticXmlParserError(unsigned short const*, unsigned short const*, int, void*);
    };

} // namespace DirectUI
