// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::ToggleProxy -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include <UIAutomationCore.h>  // Option D quarantine: SDK UIA types

namespace DirectUI
{
    class Element;
    class ToggleProxy;

    class ToggleProxy
    {
    public:
        virtual long DoMethod(int, char*);

        protected:
        virtual void Init(Element*);

        public:
        ToggleProxy(ToggleProxy&&);
        ToggleProxy(ToggleProxy const&);
        ToggleProxy(void);
        ToggleProxy& operator=(ToggleProxy&&);
        ToggleProxy& operator=(ToggleProxy const&);
        static ToggleProxy* Create(Element*);
        static bool IsPatternSupported(Element*);

        private:
        long GetToggleState(ToggleState*);
    };

} // namespace DirectUI
