// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::TouchCheckBox -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "TouchButton.h"

namespace DirectUI
{
    class Element;
    class Value;

    class TouchCheckBox
        : public TouchButton
    {
    public:
        TouchCheckBox(void);
        virtual ~TouchCheckBox(void);
        virtual bool OnPropertyChanging(PropertyInfo const*, int, Value*, Value*);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        virtual void OnEvent(Event*);
        virtual void Paint(HDC__*, tagRECT const*, tagRECT const*, tagRECT*, tagRECT*);
        virtual long Insert(Element**, unsigned int, unsigned int);
        virtual void GetImmersiveFocusRectOffsets(tagRECT*);
        virtual IClassInfo* GetClassInfoW(void);
        static PropertyInfo const* CheckedStateProp(void);
        static long Create(unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        CheckedStateFlags GetCheckedState(void);
        static IClassInfo* GetClassInfoPtr(void);
        bool GetToggleOnClick(void);
        long Initialize(unsigned int, Element*, unsigned long*);
        static long Register(void);
        long SetCheckedState(CheckedStateFlags);
        long SetToggleOnClick(bool);
        static PropertyInfo const* ToggleOnClickProp(void);
    };

} // namespace DirectUI
