// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::TouchEditBase -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class Value;

    class TouchEditBase
    {
    public:
        static UID CaretMoved(void);
        static long Create(Element*, unsigned long*, Element**);
        static UID Cut(void);
        static PropertyInfo const* ElementMovesOnIHMNotifyProp(void);
        static UID Enter(void);
        static PropertyInfo const* FilterOnPasteProp(void);
        virtual long FinalizeCurrentIMEComposition(void);
        static PropertyInfo const* ForceEditTextToLTRProp(void);
        static IClassInfo* GetClassInfoPtr(void);
        virtual IClassInfo* GetClassInfoW(void);
        virtual unsigned short const* GetContentStringAsDisplayed(Value**);
        virtual long GetControllerFor(IUnknown**);
        bool GetElementMovesOnIHMNotify(void);
        bool GetFilterOnPaste(void);
        bool GetForceEditTextToLTR(void);
        bool GetIMEComposing(void);
        TouchEditFilteredKeyComboFlags GetIgnoredKeyCombos(void);
        bool GetIntegrateIMECandidateList(void);
        TouchEditKeyboardNavigationCapture GetKeyboardNavigationCapture(void);
        int GetMaxLength(void);
        bool GetMoveCaretToEndOnSyncContent(void);
        bool GetMultiline(void);
        int GetPasswordCharacter(void);
        bool GetPreventFormatChangeUpdatingModifiedState(void);
        bool GetReadOnly(void);
        Value* GetSelectionBackgroundColor(void);
        Value* GetSelectionForegroundColor(void);
        bool GetSyncContentWhileIMEComposing(void);
        virtual long GetTextDocument(ITextDocument**);
        TouchEditTextMode GetTextMode(void);
        virtual long GetTextServices(ITextServices**);
        static PropertyInfo const* IMEComposingProp(void);
        static PropertyInfo const* IgnoredKeyCombosProp(void);
        virtual long Insert(Element**, unsigned int, unsigned int);
        static PropertyInfo const* IntegrateIMECandidateListProp(void);
        virtual bool IsContentProtected(void);
        static PropertyInfo const* KeyboardNavigationCaptureProp(void);
        static PropertyInfo const* MaxLengthProp(void);
        static PropertyInfo const* MoveCaretToEndOnSyncContentProp(void);
        static PropertyInfo const* MultilineProp(void);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        virtual bool OnPropertyChanging(PropertyInfo const*, int, Value*, Value*);
        static PropertyInfo const* PasswordCharacterProp(void);
        static UID Paste(void);
        static PropertyInfo const* PreventFormatChangeUpdatingModifiedStateProp(void);
        static PropertyInfo const* ReadOnlyProp(void);
        virtual long RefreshContent(void);
        static long Register(void);
        static PropertyInfo const* SelectionBackgroundColorProp(void);
        static PropertyInfo const* SelectionForegroundColorProp(void);
        long SetElementMovesOnIHMNotify(bool);
        long SetFilterOnPaste(bool);
        long SetForceEditTextToLTR(bool);
        long SetIMEComposing(bool);
        long SetIgnoredKeyCombos(TouchEditFilteredKeyComboFlags, TouchEditFilteredKeyComboFlags);
        long SetIntegrateIMECandidateList(bool);
        virtual void SetKeyFocus(void);
        long SetKeyboardNavigationCapture(TouchEditKeyboardNavigationCapture);
        long SetMaxLength(int);
        long SetMoveCaretToEndOnSyncContent(bool);
        long SetMultiline(bool);
        long SetPasswordCharacter(int);
        long SetPreventFormatChangeUpdatingModifiedState(bool);
        long SetReadOnly(bool);
        long SetSelectionBackgroundColor(Value*);
        long SetSelectionForegroundColor(Value*);
        long SetSyncContentWhileIMEComposing(bool);
        long SetTextMode(TouchEditTextMode);
        static PropertyInfo const* SyncContentWhileIMEComposingProp(void);
        static PropertyInfo const* TextModeProp(void);
        static UID UserTextChanged(void);
        static UID UserTextUpdateNoChange(void);
    };

} // namespace DirectUI
