// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::TouchSelectItem -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class Value;

    class TouchSelectItem
    {
    public:
        TouchSelectItem(void);
        virtual ~TouchSelectItem(void);
        // ABI placeholder: real slot 1 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_1(void) = 0;
        // ABI placeholder: real slot 2 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_2(void) = 0;
        // ABI placeholder: real slot 3 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_3(void) = 0;
        // ABI placeholder: real slot 4 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_4(void) = 0;
        // ABI placeholder: real slot 5 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_5(void) = 0;
        // ABI placeholder: real slot 6 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_6(void) = 0;
        // ABI placeholder: real slot 7 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_7(void) = 0;
        // ABI placeholder: real slot 8 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_8(void) = 0;
        // ABI placeholder: real slot 9 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_9(void) = 0;
        // ABI placeholder: real slot 10 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_10(void) = 0;
        // ABI placeholder: real slot 11 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_11(void) = 0;
        // ABI placeholder: real slot 12 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_12(void) = 0;
        // ABI placeholder: real slot 13 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_13(void) = 0;
        // ABI placeholder: real slot 14 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_14(void) = 0;
        // ABI placeholder: real slot 15 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_15(void) = 0;
        // ABI placeholder: real slot 16 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_16(void) = 0;
        // ABI placeholder: real slot 17 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_17(void) = 0;
        // ABI placeholder: real slot 18 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_18(void) = 0;
        // ABI placeholder: real slot 19 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_19(void) = 0;
        // ABI placeholder: real slot 20 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_20(void) = 0;
        // ABI placeholder: real slot 21 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_21(void) = 0;
        // ABI placeholder: real slot 22 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_22(void) = 0;
        // ABI placeholder: real slot 23 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_23(void) = 0;
        // ABI placeholder: real slot 24 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_24(void) = 0;
        // ABI placeholder: real slot 25 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_25(void) = 0;
        // ABI placeholder: real slot 26 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_26(void) = 0;
        // ABI placeholder: real slot 27 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_27(void) = 0;
        // ABI placeholder: real slot 28 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_28(void) = 0;
        // ABI placeholder: real slot 29 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_29(void) = 0;
        // ABI placeholder: real slot 30 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_30(void) = 0;
        // ABI placeholder: real slot 31 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_31(void) = 0;
        // ABI placeholder: real slot 32 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_32(void) = 0;
        // ABI placeholder: real slot 33 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_33(void) = 0;
        // ABI placeholder: real slot 34 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_34(void) = 0;
        virtual IClassInfo* GetClassInfoW(void);
        // ABI placeholder: real slot 36 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_36(void) = 0;
        // ABI placeholder: real slot 37 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_37(void) = 0;
        // ABI placeholder: real slot 38 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_38(void) = 0;
        // ABI placeholder: real slot 39 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_39(void) = 0;
        // ABI placeholder: real slot 40 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_40(void) = 0;
        // ABI placeholder: real slot 41 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_41(void) = 0;
        // ABI placeholder: real slot 42 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_42(void) = 0;
        // ABI placeholder: real slot 43 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_43(void) = 0;
        // ABI placeholder: real slot 44 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_44(void) = 0;
        // ABI placeholder: real slot 45 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_45(void) = 0;
        // ABI placeholder: real slot 46 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_46(void) = 0;
        // ABI placeholder: real slot 47 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSelectItem_47(void) = 0;
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        long GetItemData(IUnknown**);
        unsigned short const* GetTextContentOverride(Value**);
        static long Register(void);
        long SetItemData(IUnknown*);
        long SetTextContentOverride(unsigned short const*);
        static PropertyInfo const* TextContentOverrideProp(void);
    };

} // namespace DirectUI
