// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::TouchScrollBar -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class Value;

    class TouchScrollBar
    {
    public:
        TouchScrollBar(void);
        virtual ~TouchScrollBar(void);
        static UID ActiveStateChanged(void);
        static UID AnimateScroll(void);
        static long Create(Element*, unsigned long*, Element**);
        virtual long CreateButtons(void);
        ActiveState GetActiveState(void);
        static IClassInfo* GetClassInfoPtr(void);
        virtual IClassInfo* GetClassInfoW(void);
        Element* GetThumb(void);
        long Initialize(bool, Element*, unsigned long*);
        static UID InteractionEnd(void);
        static UID InteractionStart(void);
        bool IsThumbActive(void);
        virtual void LineDown(unsigned int);
        virtual void LineUp(unsigned int);
        virtual void OnEvent(Event*);
        virtual void OnHosted(Element*);
        virtual void OnInput(InputEvent*);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        virtual void PageDown(unsigned int);
        virtual void PageUp(unsigned int);
        static long Register(void);
        void SetActiveState(ActiveState, bool);
        virtual void _SelfLayoutDoLayout(int, int);
        virtual tagSIZE _SelfLayoutUpdateDesiredSize(int, int, Surface*);
    };

} // namespace DirectUI
