// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::TouchCommandButton -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class Value;

    class TouchCommandButton
    {
    public:
        virtual bool OnPropertyChanging(PropertyInfo const*, int, Value*, Value*);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        virtual void Paint(HDC__*, tagRECT const*, tagRECT const*, tagRECT*, tagRECT*);
        virtual long Insert(Element**, unsigned int, unsigned int);
        virtual IClassInfo* GetClassInfoW(void);
        TouchCommandButton(void);
        static long Create(unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        unsigned short const* GetSubContent(Value**);
        long Initialize(unsigned int, Element*, unsigned long*);
        static long Register(void);
        long SetSubContent(unsigned short const*);
        static PropertyInfo const* SubContentProp(void);
    };

} // namespace DirectUI
