// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::TouchSlider -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Button;
    class Element;

    class TouchSlider
    {
    public:
        // ABI placeholder: real slot 0 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_0(void) = 0;
        // ABI placeholder: real slot 1 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_1(void) = 0;
        // ABI placeholder: real slot 2 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_2(void) = 0;
        // ABI placeholder: real slot 3 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_3(void) = 0;
        // ABI placeholder: real slot 4 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_4(void) = 0;
        // ABI placeholder: real slot 5 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_5(void) = 0;
        // ABI placeholder: real slot 6 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_6(void) = 0;
        // ABI placeholder: real slot 7 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_7(void) = 0;
        // ABI placeholder: real slot 8 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_8(void) = 0;
        // ABI placeholder: real slot 9 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_9(void) = 0;
        // ABI placeholder: real slot 10 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_10(void) = 0;
        // ABI placeholder: real slot 11 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_11(void) = 0;
        // ABI placeholder: real slot 12 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_12(void) = 0;
        // ABI placeholder: real slot 13 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_13(void) = 0;
        // ABI placeholder: real slot 14 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_14(void) = 0;
        // ABI placeholder: real slot 15 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_15(void) = 0;
        // ABI placeholder: real slot 16 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_16(void) = 0;
        // ABI placeholder: real slot 17 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_17(void) = 0;
        // ABI placeholder: real slot 18 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_18(void) = 0;
        // ABI placeholder: real slot 19 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_19(void) = 0;
        // ABI placeholder: real slot 20 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_20(void) = 0;
        // ABI placeholder: real slot 21 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_21(void) = 0;
        // ABI placeholder: real slot 22 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_22(void) = 0;
        // ABI placeholder: real slot 23 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_23(void) = 0;
        // ABI placeholder: real slot 24 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_24(void) = 0;
        // ABI placeholder: real slot 25 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_25(void) = 0;
        // ABI placeholder: real slot 26 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_26(void) = 0;
        // ABI placeholder: real slot 27 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_27(void) = 0;
        // ABI placeholder: real slot 28 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_28(void) = 0;
        // ABI placeholder: real slot 29 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_29(void) = 0;
        // ABI placeholder: real slot 30 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_30(void) = 0;
        // ABI placeholder: real slot 31 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_31(void) = 0;
        // ABI placeholder: real slot 32 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_32(void) = 0;
        // ABI placeholder: real slot 33 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_33(void) = 0;
        // ABI placeholder: real slot 34 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_34(void) = 0;
        virtual IClassInfo* GetClassInfoW(void);
        // ABI placeholder: real slot 36 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_36(void) = 0;
        // ABI placeholder: real slot 37 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_37(void) = 0;
        // ABI placeholder: real slot 38 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_38(void) = 0;
        // ABI placeholder: real slot 39 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_39(void) = 0;
        // ABI placeholder: real slot 40 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_40(void) = 0;
        // ABI placeholder: real slot 41 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_41(void) = 0;
        // ABI placeholder: real slot 42 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_42(void) = 0;
        // ABI placeholder: real slot 43 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_43(void) = 0;
        // ABI placeholder: real slot 44 has no recoverable signature.
        // ABI placeholder: never call.
        virtual void __DuiAbiSlot_TouchSlider_44(void) = 0;
        static PropertyInfo const* BufferingProp(void);
        void CancelCurrentDrag(void);
        static long Create(Element*, unsigned long*, Element**);
        void EraseFeedback(void);
        void FireEventOnMouseOrPointerRelease(void);
        int GetBuffering(void);
        static IClassInfo* GetClassInfoPtr(void);
        Element* GetFillpartElement(void);
        bool GetIsContinuous(void);
        bool GetIsPressed(void);
        bool GetIsShowOnOffFeedback(void);
        bool GetIsVertical(void);
        int GetMetering(void);
        int GetRangeMax(void);
        int GetRangeMin(void);
        bool GetShowTick(void);
        int GetStepCount(void);
        Button* GetThumbElement(void);
        int GetThumbValue(void);
        int GetTickCount(void);
        Element* GetTrackElement(void);
        int GetVisualState(void);
        long Initialize(Element*, unsigned long*);
        static PropertyInfo const* IsContinuousProp(void);
        static PropertyInfo const* IsPressedProp(void);
        static PropertyInfo const* IsShowOnOffFeedbackProp(void);
        static PropertyInfo const* IsVerticalProp(void);
        static PropertyInfo const* MeteringProp(void);
        static UID MouseOrPointerReleased(void);
        static long Register(void);
        void RemoveRichDuiTooltip(void);
        long SetBuffering(int);
        void SetFireContinuousSliderEvent(bool);
        long SetIsContinuous(bool);
        long SetIsPressed(bool);
        long SetIsShowOnOffFeedback(bool);
        long SetIsVertical(bool);
        long SetMetering(int);
        void SetRangeMax(int);
        void SetRangeMin(int);
        void SetRangeMinAndRangeMax(int, int);
        void SetRespectLanguageDirection(bool);
        void SetRespondToMouseScroll(bool);
        long SetShowTick(bool);
        void SetStepCount(int);
        void SetThumbValue(int, bool, bool);
        void SetThumbValue(int, bool);
        long SetTickCount(int);
        void SetTooltipText(unsigned short const*);
        static PropertyInfo const* ShowTickProp(void);
        void ShowTooltipOnRightForLTRBuild(void);
        static UID SliderUpdated(void);
        static PropertyInfo const* ThumbPositionProp(void);
        static PropertyInfo const* TickCountProp(void);
        int TranslateThumbPositionToThumbValue(int);
        void UseFixedTooltipOffset(void);
        static PropertyInfo const* VisualStateProp(void);
    };

} // namespace DirectUI
