// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::TouchButton -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "Element.h"

namespace DirectUI
{
    class Element;
    class Value;

    class TouchButton
        : public Element
    {
    public:
        enum ClickDevice { ClickDevice_None = 0 };

        TouchButton(void);
        virtual ~TouchButton(void);
        bool CancelClick(TouchButton::ClickDevice);
        static PropertyInfo const* CapturedProp(void);
        static UID Click(void);
        static long Create(unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        virtual long DefaultAction(void);
        virtual void FireClickEvent(unsigned int, unsigned int, TouchButton::ClickDevice, tagPOINT*);
        virtual void FireRightClickEvent(unsigned int, tagPOINT*);
        bool GetCaptured(void);
        static IClassInfo* GetClassInfoPtr(void);
        virtual IClassInfo* GetClassInfoW(void);
        TouchButton::ClickDevice GetClickDevice(void);
        virtual long GetForegroundColorRef(unsigned long*);
        bool GetHandleEnter(void);
        bool GetHandleGlobalEnter(void);
        virtual void GetImmersiveFocusRectOffsets(tagRECT*);
        bool GetPressed(void);
        bool GetShowKeyFocus(void);
        bool GetTreatRightMouseButtonAsLeft(void);
        static PropertyInfo const* HandleEnterProp(void);
        static PropertyInfo const* HandleGlobalEnterProp(void);
        long Initialize(unsigned int, Element*, unsigned long*);
        static UID MultipleClick(void);
        virtual void OnEvent(Event*);
        virtual void OnHosted(Element*);
        virtual void OnInput(InputEvent*);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        virtual void OnUnHosted(Element*);
        static PropertyInfo const* PressedProp(void);
        static long Register(void);
        static UID RightClick(void);
        long SetCaptured(bool);
        long SetHandleEnter(bool);
        long SetHandleGlobalEnter(bool);
        long SetPressed(bool);
        long SetShowKeyFocus(bool);
        long SetTreatRightMouseButtonAsLeft(bool);
        static PropertyInfo const* ShowKeyFocusProp(void);
        static PropertyInfo const* TreatRightMouseButtonAsLeftProp(void);
    };

} // namespace DirectUI
