// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::UnknownElement -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class UnknownElement;

    class UnknownElement
    {
    public:
        UnknownElement(UnknownElement const&);
        UnknownElement(void);
        virtual ~UnknownElement(void);
        virtual IClassInfo* GetClassInfoW(void);
        UnknownElement& operator=(UnknownElement const&);
        static long Create(unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        static IClassInfo* GetClassInfoPtr(void);
        long Initialize(unsigned int, Element*, unsigned long*);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
