// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::Viewer -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class Value;
    class Viewer;

    class Viewer
    {
    public:
        Viewer(Viewer const&);
        Viewer(void);
        virtual ~Viewer(void);
        Viewer& operator=(Viewer const&);
        static long Create(Element*, unsigned long*, Element**);
        virtual bool EnsureVisible(int, int, int, int);
        static IClassInfo* GetClassInfoPtr(void);
        virtual IClassInfo* GetClassInfoW(void);
        int GetXOffset(void);
        bool GetXScrollable(void);
        int GetYOffset(void);
        bool GetYScrollable(void);
        long Initialize(Element*, unsigned long*);
        virtual void OnEvent(Event*);
        virtual void OnInput(InputEvent*);
        virtual void OnPropertyChanged(PropertyInfo const*, int, Value*, Value*);
        virtual bool OnPropertyChanging(PropertyInfo const*, int, Value*, Value*);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);
        void SetEnsureVisibleUseLayoutCoordinates(bool);
        long SetXOffset(int);
        long SetXScrollable(bool);
        long SetYOffset(int);
        long SetYScrollable(bool);
        static PropertyInfo const* XOffsetProp(void);
        static PropertyInfo const* XScrollableProp(void);
        static PropertyInfo const* YOffsetProp(void);
        static PropertyInfo const* YScrollableProp(void);
        virtual void _SelfLayoutDoLayout(int, int);
        virtual tagSIZE _SelfLayoutUpdateDesiredSize(int, int, Surface*);

        private:
        Element* _GetContent(void);
        bool _InternalEnsureVisible(int, int, int, int);
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
