// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::XBaby -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "DialogElement.h"

namespace DirectUI
{
    class DUIXmlParser;
    class Element;
    class ElementProvider;
    class HWNDElement;
    class IXElementCP;
    struct NavReference;
    class XBaby;
    class XProvider;

    class XBaby
        : public DialogElement, public IXBaby
    {
    public:
        virtual HWNDElement* GetXBabyElement(void);
        virtual void CacheParser(DUIXmlParser*);
        virtual long SetToHost(Element*);
        virtual tagSIZE GetContentDesiredSize(int, int);
        virtual bool CanSetFocus(void);
        virtual long GetHostedElementID(unsigned short*);
        virtual void ForceThemeChange(unsigned __int64, __int64);
        virtual bool GetDefaultButtonTracking(void);
        virtual long SetDefaultButtonTracking(bool);
        virtual long SetButtonClassAcceptsEnterKey(bool);
        virtual bool ClickDefaultButton(void);
        virtual long SetRegisteredDefaultButton(Element*);
        virtual long SetHandleEnterKey(bool);
        XBaby(XBaby const&);
        XBaby(void);
        virtual ~XBaby(void);
        XBaby& operator=(XBaby const&);
        static long Create(Element*, unsigned long*, Element**);
        static long Create(IXElementCP*, XProvider*, HWND__*, Element*, unsigned long*, Element**);
        virtual long CreateStyleParser(DUIXmlParser**);
        virtual Element* GetAdjacent(Element*, int, NavReference const*, unsigned long);
        static IClassInfo* GetClassInfoPtr(void);
        virtual IClassInfo* GetClassInfoW(void);
        virtual long GetElementProviderImpl(InvokeHelper*, ElementProvider**);
        virtual Element* GetFocusableElement(void);
        virtual bool OnChildLostFocus(Element*);
        virtual bool OnChildReceivedFocus(Element*);
        virtual void OnEvent(Event*);
        virtual void OnNoChildWithShortcutFound(KeyboardEvent*);
        virtual void OnThemeChanged(ThemeChangedEvent*);
        virtual void OnWmThemeChanged(unsigned __int64, __int64);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);
        virtual void SetKeyFocus(void);

        protected:
        long Initialize(IXElementCP*, XProvider*, HWND__*, Element*, unsigned long*);

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
