// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::XElement -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "HWNDHost.h"

#include "IXElementCP.h"

namespace DirectUI
{
    class Element;
    class XElement;

    class XElement
        : public HWNDHost, public IXElementCP
    {
    public:
        XElement(XElement const&);
        XElement(void);
        virtual ~XElement(void);
        XElement& operator=(XElement const&);
        static long Create(unsigned int, Element*, unsigned long*, Element**);
        static long Create(Element*, unsigned long*, Element**);
        virtual HWND__* CreateHWND(HWND__*);
        void FreeProvider(void);
        static IClassInfo* GetClassInfoPtr(void);
        virtual IClassInfo* GetClassInfoW(void);
        virtual unsigned int GetCreationFlags(void);
        HWND__* GetInnerHWND(void);
        virtual HWND__* GetNotificationSinkHWND(void);
        IXProvider* GetProvider(void);
        long Initialize(unsigned int, Element*, unsigned long*);
        bool IsDescendent(Element*);
        virtual void OnEvent(Event*);
        virtual void OnInput(InputEvent*);
        virtual bool OnMessage(unsigned int, unsigned __int64, __int64, __int64*);
        virtual bool OnSinkThemeChanged(unsigned int, unsigned __int64, __int64, __int64*);
        virtual bool OnSysChar(unsigned short);
        static long Register(void);
        static void SetClassInfoPtr(IClassInfo*);
        virtual void SetKeyFocus(void);
        long SetProvider(IUnknown*);
        static UID UnhandledSyschar(void);
        static const unsigned int s_uButtonFocusChangeMsg;
        static const unsigned int s_uNavigateOutMsg;
        static const unsigned int s_uUnhandledSyscharMsg;

        private:
        static IClassInfo* s_pClassInfo;
    };

} // namespace DirectUI
