// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::XHost -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

namespace DirectUI
{
    class Element;
    class IXElementCP;
    class XHost;

    class XHost
    {
    public:
        XHost(void);
        ~XHost(void);
        XHost& operator=(XHost const&);
        static long Create(IXElementCP*, XHost**);
        void Destroy(void);
        void DestroyWindow(void);
        Element* GetElement(void);
        HWND__* GetHWND(void);
        void HideWindow(void);
        void Host(Element*);
        long Initialize(IXElementCP*);
        void ShowWindow(int);
        static __int64 WndProc(HWND__*, unsigned int, unsigned __int64, __int64);
    };

} // namespace DirectUI
