// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// DirectUI::XProvider -- declarations derived from the real
// dui70.dll export table + PDB publics.
#pragma once

#include <windows.h>
#include "dui_abi_types.h"

#include "Interfaces.h"

#include "Interfaces.h"

namespace DirectUI
{
    class DUIXmlParser;
    class Element;
    class IXElementCP;
    class IXProviderCP;
    class XProvider;

    class XProvider
        : public IXProvider
    {
    public:
        virtual long QueryInterface(_GUID const&, void**);
        virtual unsigned long AddRef(void);
        virtual unsigned long Release(void);
        virtual long CreateDUI(IXElementCP*, HWND__**);
        virtual long SetParameter(_GUID const&, void*);
        virtual long GetDesiredSize(int, int, tagSIZE*);
        virtual long IsDescendent(Element*, bool*);
        virtual long SetFocus(Element*);
        virtual long Navigate(int, bool*);
        virtual long CanSetFocus(bool*);
        virtual int FindElementWithShortcutAndDoDefaultAction(unsigned short, int);
        virtual long GetHostedElementID(unsigned short*);
        virtual long ForceThemeChange(unsigned __int64, __int64);
        virtual long SetDefaultButtonTracking(bool);
        virtual int ClickDefaultButton(void);
        virtual long SetRegisteredDefaultButton(Element*);
        virtual long SetButtonClassAcceptsEnterKey(bool);
        virtual long CreateXBaby(IXElementCP*, HWND__*, Element*, unsigned long*, IXBaby**);
        XProvider(XProvider const&);
        XProvider(void);
        virtual ~XProvider(void);
        XProvider& operator=(XProvider const&);
        static long Create(Element*, IXProviderCP*, XProvider**);
        long CreateParser(DUIXmlParser**);
        long Initialize(Element*, IXProviderCP*);

        protected:
        Element* GetRoot(void);
        void SetHandleEnterKey(bool);
    };

} // namespace DirectUI
