// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::AutoThread.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "AutoThread.h"

namespace DirectUI
{

AutoThread::AutoThread(void)
{ }

AutoThread::~AutoThread(void)
{}

AutoThread& AutoThread::operator=(AutoThread const&a0)
{ return *this; }

long AutoThread::Init(void)
{ return 0; }

} // namespace DirectUI
