// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::AutoVariant.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "AutoVariant.h"

namespace DirectUI
{

AutoVariant::AutoVariant(void)
{ }

AutoVariant::~AutoVariant(void)
{}

AutoVariant& AutoVariant::operator=(AutoVariant const&a0)
{ return *this; }

} // namespace DirectUI
