// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::BaseScrollBar.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "BaseScrollBar.h"

namespace DirectUI
{

BaseScrollBar::BaseScrollBar(BaseScrollBar&&a0)
{ }

BaseScrollBar::BaseScrollBar(BaseScrollBar const&a0)
{ }

BaseScrollBar::BaseScrollBar(void)
{ }

BaseScrollBar& BaseScrollBar::operator=(BaseScrollBar&&a0)
{ return *this; }

BaseScrollBar& BaseScrollBar::operator=(BaseScrollBar const&a0)
{ return *this; }

void BaseScrollBar::End(void)
{}

int BaseScrollBar::GetPageInc(void)
{ return 0; }

void BaseScrollBar::Home(void)
{}

bool BaseScrollBar::IsPinned(void)
{ return 0; }

bool BaseScrollBar::IsScrollable(void)
{ return 0; }

void BaseScrollBar::LineDown(unsigned int a0)
{}

void BaseScrollBar::LineUp(unsigned int a0)
{}

void BaseScrollBar::OnMaximumChanged(Value*a0)
{}

void BaseScrollBar::OnMinimumChanged(Value*a0)
{}

void BaseScrollBar::OnPageChanged(Value*a0)
{}

bool BaseScrollBar::OnPageChanging(Value*a0)
{ return 0; }

void BaseScrollBar::OnPositionChanged(Value*a0)
{}

bool BaseScrollBar::OnPositionChanging(Value*a0)
{ return 0; }

void BaseScrollBar::PageDown(unsigned int a0)
{}

void BaseScrollBar::PageUp(unsigned int a0)
{}

UID BaseScrollBar::Scroll(void)
{ return UID(); }

void BaseScrollBar::SetPinned(bool a0)
{}

} // namespace DirectUI
