// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::BrowserSelectionProxy.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "BrowserSelectionProxy.h"

namespace DirectUI
{

BrowserSelectionProxy::BrowserSelectionProxy(BrowserSelectionProxy&&a0)
{ }

BrowserSelectionProxy::BrowserSelectionProxy(BrowserSelectionProxy const&a0)
{ }

BrowserSelectionProxy::BrowserSelectionProxy(void)
{ }

BrowserSelectionProxy& BrowserSelectionProxy::operator=(BrowserSelectionProxy&&a0)
{ return *this; }

BrowserSelectionProxy& BrowserSelectionProxy::operator=(BrowserSelectionProxy const&a0)
{ return *this; }

long BrowserSelectionProxy::DoMethod(int a0, char*a1)
{ return 0; }

long BrowserSelectionProxy::GetIsSelectionRequired(int*a0)
{ return 0; }

long BrowserSelectionProxy::GetSelection(tagSAFEARRAY**a0)
{ return 0; }

void BrowserSelectionProxy::Init(Element*a0)
{}

} // namespace DirectUI
