// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::Browser.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "Browser.h"
#include "Interfaces.h"

namespace DirectUI
{

Browser::Browser(Browser&&a0)
{ }

Browser::Browser(Browser const&a0)
{ }

Browser::Browser(void)
{ }

Browser::~Browser(void)
{}

Browser& Browser::operator=(Browser&&a0)
{ return *this; }

Browser& Browser::operator=(Browser const&a0)
{ return *this; }

long Browser::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

UID Browser::Entered(void)
{ return UID(); }

int Browser::FireNavigate(unsigned short a0)
{ return 0; }

IClassInfo* Browser::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* Browser::GetClassInfoW(void)
{ return nullptr; }

Element* Browser::GetCurrentPage(void)
{ return nullptr; }

unsigned short Browser::GetCurrentPageID(void)
{ return 0; }

Pages* Browser::GetPages(void)
{ return nullptr; }

long Browser::Initialize(Element*a0, unsigned long*a1)
{ return 0; }

UID Browser::Leaving(void)
{ return UID(); }

void Browser::OnEvent(Event*a0)
{}

void Browser::OnPropertyChanged(PropertyInfo const*a0, int a1, Value*a2, Value*a3)
{}

long Browser::Register(void)
{ return 0; }

void Browser::SetClassInfoPtr(IClassInfo*a0)
{}

UID Browser::StartNavigate(void)
{ return UID(); }

IClassInfo* Browser::s_pClassInfo = nullptr;

} // namespace DirectUI
