// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::Button.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "Button.h"
#include "Interfaces.h"

namespace DirectUI
{

Button::Button(Button const&a0)
{ }

Button::Button(void)
{ }

Button::~Button(void)
{}

Button& Button::operator=(Button const&a0)
{ return *this; }

PropertyInfo const* Button::CapturedProp(void)
{ return nullptr; }

UID Button::Click(void)
{ return UID(); }

UID Button::Context(void)
{ return UID(); }

long Button::Create(unsigned int a0, Element*a1, unsigned long*a2, Element**a3)
{ return 0; }

long Button::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

long Button::DefaultAction(void)
{ return 0; }

bool Button::GetCaptured(void)
{ return 0; }

IClassInfo* Button::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* Button::GetClassInfoW(void)
{ return nullptr; }

bool Button::GetPressed(void)
{ return 0; }

long Button::Initialize(unsigned int a0, Element*a1, unsigned long*a2)
{ return 0; }

void Button::OnInput(InputEvent*a0)
{}

bool Button::OnLostDialogFocus(IDialogElement*a0)
{ return 0; }

void Button::OnPropertyChanged(PropertyInfo const*a0, int a1, Value*a2, Value*a3)
{}

bool Button::OnReceivedDialogFocus(IDialogElement*a0)
{ return 0; }

PropertyInfo const* Button::PressedProp(void)
{ return nullptr; }

long Button::Register(void)
{ return 0; }

long Button::SetCaptured(bool a0)
{ return 0; }

void Button::SetClassInfoPtr(IClassInfo*a0)
{}

long Button::SetPressed(bool a0)
{ return 0; }

IClassInfo* Button::s_pClassInfo = nullptr;

} // namespace DirectUI
