; Generated by tools/dui-pipeline -- DO NOT EDIT. Pin: 2080E43F5D99

; 'default ctor closure' exports of DirectUI::CCBase.
; Compiler-synthesized symbols (??_F...) are not expressible
; in C++ source; MASM defines them verbatim.
_TEXT SEGMENT
PUBLIC ??_FCCBase@DirectUI@@QEAAXXZ
??_FCCBase@DirectUI@@QEAAXXZ PROC
    ret
??_FCCBase@DirectUI@@QEAAXXZ ENDP
_TEXT ENDS
END
