// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::CCBase.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "CCBase.h"
#include "Interfaces.h"

namespace DirectUI
{

CCBase::CCBase(CCBase const&a0)
{ }

CCBase::CCBase(unsigned long a0, unsigned short const*a1)
{ }

CCBase::~CCBase(void)
{}

CCBase& CCBase::operator=(CCBase const&a0)
{ return *this; }

long CCBase::Create(unsigned int a0, Element*a1, unsigned long*a2, Element**a3)
{ return 0; }

long CCBase::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

HWND__* CCBase::CreateHWND(HWND__*a0)
{ return nullptr; }

long CCBase::DefaultAction(void)
{ return 0; }

IClassInfo* CCBase::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* CCBase::GetClassInfoW(void)
{ return nullptr; }

tagSIZE CCBase::GetContentSize(int a0, int a1, Surface*a2)
{ return tagSIZE{}; }

int CCBase::GetWinStyle(void)
{ return 0; }

long CCBase::Initialize(unsigned int a0, Element*a1, unsigned long*a2)
{ return 0; }

bool CCBase::OnCustomDraw(tagNMCUSTOMDRAWINFO*a0, __int64*a1)
{ return 0; }

void CCBase::OnInput(InputEvent*a0)
{}

bool CCBase::OnLostDialogFocus(IDialogElement*a0)
{ return 0; }

bool CCBase::OnNotify(unsigned int a0, unsigned __int64 a1, __int64 a2, __int64*a3)
{ return 0; }

void CCBase::OnPropertyChanged(PropertyInfo const*a0, int a1, Value*a2, Value*a3)
{}

bool CCBase::OnReceivedDialogFocus(IDialogElement*a0)
{ return 0; }

void CCBase::PostCreate(HWND__*a0)
{}

long CCBase::Register(void)
{ return 0; }

void CCBase::SetClassInfoPtr(IClassInfo*a0)
{}

void CCBase::SetNotifyHandler(int (__cdecl * a0)(unsigned int, unsigned __int64, __int64, __int64*, void*), void*a1)
{}

long CCBase::SetWinStyle(int a0)
{ return 0; }

PropertyInfo const* CCBase::WinStyleProp(void)
{ return nullptr; }

IClassInfo* CCBase::s_pClassInfo = nullptr;

} // namespace DirectUI
