// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::CCProgressBar.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "CCProgressBar.h"
#include "Interfaces.h"

namespace DirectUI
{

CCProgressBar::CCProgressBar(CCProgressBar&&a0)
{ }

CCProgressBar::CCProgressBar(CCProgressBar const&a0)
{ }

CCProgressBar::CCProgressBar(void)
{ }

CCProgressBar::~CCProgressBar(void)
{}

CCProgressBar& CCProgressBar::operator=(CCProgressBar&&a0)
{ return *this; }

CCProgressBar& CCProgressBar::operator=(CCProgressBar const&a0)
{ return *this; }

long CCProgressBar::Create(unsigned int a0, Element*a1, unsigned long*a2, Element**a3)
{ return 0; }

long CCProgressBar::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

IClassInfo* CCProgressBar::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* CCProgressBar::GetClassInfoW(void)
{ return nullptr; }

long CCProgressBar::Initialize(unsigned int a0, Element*a1, unsigned long*a2)
{ return 0; }

void CCProgressBar::OnInput(InputEvent*a0)
{}

long CCProgressBar::Register(void)
{ return 0; }

void CCProgressBar::SetClassInfoPtr(IClassInfo*a0)
{}

IClassInfo* CCProgressBar::s_pClassInfo = nullptr;

} // namespace DirectUI
