// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::CCTrackBar.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "CCTrackBar.h"
#include "Interfaces.h"

namespace DirectUI
{

CCTrackBar::CCTrackBar(CCTrackBar&&a0)
: CCBase(0, nullptr) { }

CCTrackBar::CCTrackBar(CCTrackBar const&a0)
: CCBase(0, nullptr) { }

CCTrackBar::CCTrackBar(void)
: CCBase(0, nullptr) { }

CCTrackBar::~CCTrackBar(void)
{}

CCTrackBar& CCTrackBar::operator=(CCTrackBar&&a0)
{ return *this; }

CCTrackBar& CCTrackBar::operator=(CCTrackBar const&a0)
{ return *this; }

long CCTrackBar::Create(unsigned int a0, Element*a1, unsigned long*a2, Element**a3)
{ return 0; }

long CCTrackBar::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

IClassInfo* CCTrackBar::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* CCTrackBar::GetClassInfoW(void)
{ return nullptr; }

int CCTrackBar::GetLineSize(void)
{ return 0; }

int CCTrackBar::GetRangeMax(void)
{ return 0; }

int CCTrackBar::GetRangeMin(void)
{ return 0; }

int CCTrackBar::GetThumbPosition(void)
{ return 0; }

PropertyInfo const* CCTrackBar::LineSizeProp(void)
{ return nullptr; }

bool CCTrackBar::OnMessage(unsigned int a0, unsigned __int64 a1, __int64 a2, __int64*a3)
{ return 0; }

void CCTrackBar::OnPropertyChanged(PropertyInfo const*a0, int a1, Value*a2, Value*a3)
{}

bool CCTrackBar::OnPropertyChanging(PropertyInfo const*a0, int a1, Value*a2, Value*a3)
{ return 0; }

void CCTrackBar::PostCreate(HWND__*a0)
{}

PropertyInfo const* CCTrackBar::RangeMaxProp(void)
{ return nullptr; }

PropertyInfo const* CCTrackBar::RangeMinProp(void)
{ return nullptr; }

long CCTrackBar::Register(void)
{ return 0; }

void CCTrackBar::SetClassInfoPtr(IClassInfo*a0)
{}

long CCTrackBar::SetLineSize(int a0)
{ return 0; }

long CCTrackBar::SetRangeMax(int a0)
{ return 0; }

long CCTrackBar::SetRangeMin(int a0)
{ return 0; }

long CCTrackBar::SetThumbPosition(int a0)
{ return 0; }

PropertyInfo const* CCTrackBar::ThumbPositionProp(void)
{ return nullptr; }

IClassInfo* CCTrackBar::s_pClassInfo = nullptr;

} // namespace DirectUI
