// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::CritSecLock.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "CritSecLock.h"

namespace DirectUI
{

CritSecLock::CritSecLock(_RTL_CRITICAL_SECTION*a0)
{ }

CritSecLock::~CritSecLock(void)
{}

CritSecLock& CritSecLock::operator=(CritSecLock const&a0)
{ return *this; }

void CritSecLock::Unlock(void)
{}

} // namespace DirectUI
