// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::DialogElement.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "DialogElement.h"
#include "Interfaces.h"

namespace DirectUI
{

DialogElement::DialogElement(DialogElement&&a0)
{ }

DialogElement::DialogElement(DialogElement const&a0)
{ }

DialogElement::DialogElement(void)
{ }

DialogElement::~DialogElement(void)
{}

DialogElement& DialogElement::operator=(DialogElement&&a0)
{ return *this; }

DialogElement& DialogElement::operator=(DialogElement const&a0)
{ return *this; }

PropertyInfo const* DialogElement::ButtonClassAcceptsEnterKeyProp(void)
{ return nullptr; }

bool DialogElement::ClickDefaultButton(void)
{ return 0; }

long DialogElement::Create(HWND__*a0, bool a1, unsigned int a2, Element*a3, unsigned long*a4, Element**a5)
{ return 0; }

PropertyInfo const* DialogElement::DefaultButtonTrackingProp(void)
{ return nullptr; }

bool DialogElement::GetButtonClassAcceptsEnterKey(void)
{ return 0; }

IClassInfo* DialogElement::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* DialogElement::GetClassInfoW(void)
{ return nullptr; }

Element* DialogElement::GetDefaultButton(void)
{ return nullptr; }

bool DialogElement::GetDefaultButtonTracking(void)
{ return 0; }

bool DialogElement::GetHandleEnterKey(void)
{ return 0; }

Element* DialogElement::GetKeyFocusedElement(void)
{ return nullptr; }

Element* DialogElement::GetRegisteredDefaultButton(void)
{ return nullptr; }

PropertyInfo const* DialogElement::HandleEnterKeyProp(void)
{ return nullptr; }

bool DialogElement::OnChildLostFocus(Element*a0)
{ return 0; }

bool DialogElement::OnChildReceivedFocus(Element*a0)
{ return 0; }

void DialogElement::OnDestroy(void)
{}

void DialogElement::OnGetDlgCode(tagMSG*a0, __int64*a1)
{}

void DialogElement::OnInput(InputEvent*a0)
{}

void DialogElement::OnKeyFocusMoved(Element*a0, Element*a1)
{}

void DialogElement::OnListenedEvent(Element*a0, Event*a1)
{}

void DialogElement::OnListenedInput(Element*a0, InputEvent*a1)
{}

void DialogElement::OnListenedPropertyChanged(Element*a0, PropertyInfo const*a1, int a2, Value*a3, Value*a4)
{}

bool DialogElement::OnListenedPropertyChanging(Element*a0, PropertyInfo const*a1, int a2, Value*a3, Value*a4)
{ return 0; }

void DialogElement::OnListenerAttach(Element*a0)
{}

void DialogElement::OnListenerDetach(Element*a0)
{}

void DialogElement::OnPropertyChanged(PropertyInfo const*a0, int a1, Value*a2, Value*a3)
{}

long DialogElement::Register(void)
{ return 0; }

PropertyInfo const* DialogElement::RegisteredDefaultButtonProp(void)
{ return nullptr; }

long DialogElement::SetButtonClassAcceptsEnterKey(bool a0)
{ return 0; }

void DialogElement::SetClassInfoPtr(IClassInfo*a0)
{}

long DialogElement::SetDefaultButtonTracking(bool a0)
{ return 0; }

long DialogElement::SetHandleEnterKey(bool a0)
{ return 0; }

long DialogElement::SetRegisteredDefaultButton(Element*a0)
{ return 0; }

IClassInfo* DialogElement::s_pClassInfo = nullptr;

} // namespace DirectUI
