// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::ElementProxy.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "ElementProxy.h"

namespace DirectUI
{

ElementProxy::ElementProxy(void)
{ }

ElementProxy::ElementProxy(ElementProxy&&a0)
{ }

ElementProxy::ElementProxy(ElementProxy const&a0)
{ }

ElementProxy& ElementProxy::operator=(ElementProxy&&a0)
{ return *this; }

ElementProxy& ElementProxy::operator=(ElementProxy const&a0)
{ return *this; }

ElementProxy* ElementProxy::Create(Element*a0)
{ return nullptr; }

long ElementProxy::DoMethod(int a0, char*a1)
{ return 0; }

long ElementProxy::GetAutomationId(tagVARIANT*a0)
{ return 0; }

long ElementProxy::GetBoundingRect(UiaRect*a0)
{ return 0; }

long ElementProxy::GetContent(tagVARIANT*a0, IAccessible*a1)
{ return 0; }

void ElementProxy::GetControlType(tagVARIANT*a0, IAccessible*a1)
{}

long ElementProxy::GetFragmentRoot(IRawElementProviderFragmentRoot**a0)
{ return 0; }

long ElementProxy::GetHwnd(HWND__**a0)
{ return 0; }

long ElementProxy::GetLabel(tagVARIANT*a0)
{ return 0; }

long ElementProxy::GetProperty(tagVARIANT*a0, int a1)
{ return 0; }

long ElementProxy::GetProviderOptions(ProviderOptions*a0)
{ return 0; }

long ElementProxy::GetRuntimeId(tagSAFEARRAY**a0)
{ return 0; }

void ElementProxy::Init(Element*a0)
{}

long ElementProxy::IsPatternSupported(Schema::Pattern a0, bool*a1)
{ return 0; }

long ElementProxy::Navigate(NavigateDirection a0, IRawElementProviderFragment**a1)
{ return 0; }

long ElementProxy::SetString(tagVARIANT*a0, unsigned short const* (__cdecl DirectUI::Element::* a1)(Value**))
{ return 0; }

bool ElementProxy::_IsSemanticZoomControl(int a0)
{ return 0; }

bool ElementProxy::_IsWindowHostUsingDoNotStealFocusFlag(void)
{ return 0; }

int ElementProxy::_UsesUIAProxies(void)
{ return 0; }

} // namespace DirectUI
