// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::Element.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "Element.h"
#include "Interfaces.h"

namespace DirectUI
{

Element::Element(Element const&a0)
{ }

Element::Element(void)
{ }

Element::~Element(void)
{}

Element& Element::operator=(Element const&a0)
{ return *this; }

PropertyInfo const* Element::AbsorbsShortcutProp(void)
{ return nullptr; }

PropertyInfo const* Element::AccDefActionProp(void)
{ return nullptr; }

PropertyInfo const* Element::AccDescProp(void)
{ return nullptr; }

PropertyInfo const* Element::AccHelpProp(void)
{ return nullptr; }

PropertyInfo const* Element::AccItemStatusProp(void)
{ return nullptr; }

PropertyInfo const* Element::AccItemTypeProp(void)
{ return nullptr; }

PropertyInfo const* Element::AccNameProp(void)
{ return nullptr; }

PropertyInfo const* Element::AccRoleProp(void)
{ return nullptr; }

PropertyInfo const* Element::AccStateProp(void)
{ return nullptr; }

PropertyInfo const* Element::AccValueProp(void)
{ return nullptr; }

PropertyInfo const* Element::AccessibleProp(void)
{ return nullptr; }

void Element::ActivateTooltip(Element*a0, unsigned long a1)
{}

PropertyInfo const* Element::ActiveProp(void)
{ return nullptr; }

long Element::Add(Element*a0)
{ return 0; }

long Element::Add(Element*a0, int (__cdecl * a1)(void const*, void const*))
{ return 0; }

long Element::Add(Element**a0, unsigned int a1)
{ return 0; }

long Element::AddBehavior(IDuiBehavior*a0)
{ return 0; }

long Element::AddListener(IElementListener*a0)
{ return 0; }

unsigned long Element::AddRef(void)
{ return 0; }

PropertyInfo const* Element::AlphaProp(void)
{ return nullptr; }

UID Element::AnimationChange(void)
{ return UID(); }

PropertyInfo const* Element::AnimationProp(void)
{ return nullptr; }

PropertyInfo const* Element::BackgroundProp(void)
{ return nullptr; }

PropertyInfo const* Element::BorderColorProp(void)
{ return nullptr; }

PropertyInfo const* Element::BorderStyleProp(void)
{ return nullptr; }

PropertyInfo const* Element::BorderThicknessProp(void)
{ return nullptr; }

void Element::BroadcastEvent(Event*a0)
{}

PropertyInfo const* Element::ChildrenProp(void)
{ return nullptr; }

PropertyInfo const* Element::ClassProp(void)
{ return nullptr; }

PropertyInfo const* Element::CompositedTextProp(void)
{ return nullptr; }

PropertyInfo const* Element::ContentAlignProp(void)
{ return nullptr; }

PropertyInfo const* Element::ContentProp(void)
{ return nullptr; }

long Element::Create(unsigned int a0, Element*a1, unsigned long*a2, Element**a3)
{ return 0; }

PropertyInfo const* Element::CursorProp(void)
{ return nullptr; }

PropertyInfo const* Element::CustomProp(void)
{ return nullptr; }

UID Element::DCompDeviceRebuilt(void)
{ return UID(); }

PropertyInfo const* Element::DPIProp(void)
{ return nullptr; }

long Element::DefaultAction(void)
{ return 0; }

PropertyInfo const* Element::DesiredSizeProp(void)
{ return nullptr; }

long Element::Destroy(bool a0)
{ return 0; }

long Element::DestroyAll(bool a0)
{ return 0; }

void Element::Detach(DeferCycle*a0)
{}

PropertyInfo const* Element::DirectionProp(void)
{ return nullptr; }

void Element::DoubleBuffered(bool a0)
{}

PropertyInfo const* Element::EdgeHighlightColorProp(void)
{ return nullptr; }

PropertyInfo const* Element::EdgeHighlightThicknessProp(void)
{ return nullptr; }

void Element::EnableUiaEvents(bool a0)
{}

PropertyInfo const* Element::EnabledProp(void)
{ return nullptr; }

void Element::EndDefer(unsigned long a0)
{}

bool Element::EnsureVisible(unsigned int a0)
{ return 0; }

bool Element::EnsureVisible(void)
{ return 0; }

bool Element::EnsureVisible(int a0, int a1, int a2, int a3)
{ return 0; }

PropertyInfo const* Element::ExtentProp(void)
{ return nullptr; }

Element* Element::FindDescendent(unsigned short a0)
{ return nullptr; }

Element* Element::FindDescendentWorker(unsigned short a0)
{ return nullptr; }

void Element::FireEvent(Event*a0, bool a1, bool a2)
{}

PropertyInfo const* Element::FontFaceProp(void)
{ return nullptr; }

PropertyInfo const* Element::FontProp(void)
{ return nullptr; }

PropertyInfo const* Element::FontQualityProp(void)
{ return nullptr; }

PropertyInfo const* Element::FontSizeProp(void)
{ return nullptr; }

PropertyInfo const* Element::FontStyleProp(void)
{ return nullptr; }

PropertyInfo const* Element::FontWeightProp(void)
{ return nullptr; }

PropertyInfo const* Element::ForegroundProp(void)
{ return nullptr; }

bool Element::GetAbsorbsShortcut(void)
{ return 0; }

unsigned short const* Element::GetAccDefAction(Value**a0)
{ return nullptr; }

unsigned short const* Element::GetAccDesc(Value**a0)
{ return nullptr; }

unsigned short const* Element::GetAccHelp(Value**a0)
{ return nullptr; }

unsigned short const* Element::GetAccItemStatus(Value**a0)
{ return nullptr; }

unsigned short const* Element::GetAccItemType(Value**a0)
{ return nullptr; }

unsigned short const* Element::GetAccName(Value**a0)
{ return nullptr; }

unsigned short const* Element::GetAccNameAsDisplayed(Value**a0)
{ return nullptr; }

int Element::GetAccRole(void)
{ return 0; }

int Element::GetAccState(void)
{ return 0; }

unsigned short const* Element::GetAccValue(Value**a0)
{ return nullptr; }

bool Element::GetAccessible(void)
{ return 0; }

long Element::GetAccessibleImpl(IAccessible**a0)
{ return 0; }

int Element::GetActive(void)
{ return 0; }

Element* Element::GetAdjacent(Element*a0, int a1, NavReference const*a2, unsigned long a3)
{ return nullptr; }

int Element::GetAlpha(void)
{ return 0; }

int Element::GetAnimation(void)
{ return 0; }

Fill const* Element::GetBackgroundColor(Value**a0)
{ return nullptr; }

int Element::GetBackgroundStdColor(void)
{ return 0; }

Fill const* Element::GetBorderColor(Value**a0)
{ return nullptr; }

int Element::GetBorderStdColor(void)
{ return 0; }

int Element::GetBorderStyle(void)
{ return 0; }

tagRECT const* Element::GetBorderThickness(Value**a0)
{ return nullptr; }

DynamicArray<class Element*, 0>* Element::GetChildren(Value**a0)
{ return nullptr; }

unsigned short const* Element::GetClass(Value**a0)
{ return nullptr; }

IClassInfo* Element::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* Element::GetClassInfoW(void)
{ return nullptr; }

bool Element::GetClickablePoint(tagPOINT*a0)
{ return 0; }

int Element::GetColorize(void)
{ return 0; }

unsigned int Element::GetCommonDrawTextFlags(int a0)
{ return 0; }

int Element::GetContentAlign(void)
{ return 0; }

tagSIZE Element::GetContentSize(int a0, int a1, Surface*a2)
{ return tagSIZE{}; }

unsigned short const* Element::GetContentString(Value**a0)
{ return nullptr; }

unsigned short const* Element::GetContentStringAsDisplayed(Value**a0)
{ return nullptr; }

int Element::GetDPI(void)
{ return 0; }

DeferCycle* Element::GetDeferObject(void)
{ return nullptr; }

tagSIZE const* Element::GetDesiredSize(void)
{ return nullptr; }

int Element::GetDirection(void)
{ return 0; }

HGADGET__* Element::GetDisplayNode(void)
{ return nullptr; }

Fill const* Element::GetEdgeHighlightColor(Value**a0)
{ return nullptr; }

tagRECT const* Element::GetEdgeHighlightThickness(Value**a0)
{ return nullptr; }

long Element::GetElementProviderImpl(InvokeHelper*a0, ElementProvider**a1)
{ return 0; }

float Element::GetElementScaleFactor(void)
{ return 0; }

bool Element::GetEnabled(void)
{ return 0; }

long Element::GetEncodedContentString(unsigned short*a0, unsigned __int64 a1)
{ return 0; }

unsigned __int64 Element::GetEncodedContentStringLength(void)
{ return 0; }

tagSIZE const* Element::GetExtent(Value**a0)
{ return nullptr; }

_RTL_CRITICAL_SECTION* Element::GetFactoryLock(void)
{ return nullptr; }

unsigned short const* Element::GetFont(Value**a0)
{ return nullptr; }

unsigned short const* Element::GetFontFace(Value**a0)
{ return nullptr; }

int Element::GetFontQuality(void)
{ return 0; }

int Element::GetFontSize(void)
{ return 0; }

int Element::GetFontStyle(void)
{ return 0; }

int Element::GetFontWeight(void)
{ return 0; }

Fill const* Element::GetForegroundColor(Value**a0)
{ return nullptr; }

int Element::GetForegroundStdColor(void)
{ return 0; }

int Element::GetHeight(void)
{ return 0; }

bool Element::GetHighDPI(void)
{ return 0; }

unsigned short Element::GetID(void)
{ return 0; }

Element* Element::GetImmediateChild(Element*a0)
{ return nullptr; }

void Element::GetImmersiveFocusRectOffsets(tagRECT*a0)
{}

int Element::GetIndex(void)
{ return 0; }

bool Element::GetKeyFocused(void)
{ return 0; }

bool Element::GetKeyWithin(void)
{ return 0; }

Element* Element::GetKeyWithinChild(void)
{ return nullptr; }

Layout* Element::GetLayout(Value**a0)
{ return nullptr; }

int Element::GetLayoutPos(void)
{ return 0; }

tagPOINT const* Element::GetLocation(Value**a0)
{ return nullptr; }

tagRECT const* Element::GetMargin(Value**a0)
{ return nullptr; }

tagSIZE const* Element::GetMinSize(Value**a0)
{ return nullptr; }

bool Element::GetMouseFocused(void)
{ return 0; }

bool Element::GetMouseWithin(void)
{ return 0; }

Element* Element::GetMouseWithinChild(void)
{ return nullptr; }

bool Element::GetOverhang(void)
{ return 0; }

int Element::GetPVLAnimationState(void)
{ return 0; }

tagRECT const* Element::GetPadding(Value**a0)
{ return nullptr; }

Element* Element::GetParent(void)
{ return nullptr; }

bool Element::GetPreserveAlphaChannel(void) const
{ return 0; }

Value* Element::GetRawValue(PropertyInfo const*a0, int a1, UpdateCache*a2)
{ return nullptr; }

void Element::GetRenderBorderThickness(tagRECT*a0)
{}

void Element::GetRenderEdgeHighlightThickness(tagRECT*a0)
{}

void Element::GetRenderMargin(tagRECT*a0)
{}

void Element::GetRenderMinSize(tagSIZE*a0)
{}

void Element::GetRenderPadding(tagRECT*a0)
{}

Element* Element::GetRoot(void)
{ return nullptr; }

long Element::GetRootRelativeBounds(tagRECT*a0)
{ return 0; }

bool Element::GetSelected(void)
{ return 0; }

int Element::GetShadowIntensity(void)
{ return 0; }

StyleSheet* Element::GetSheet(void)
{ return nullptr; }

int Element::GetShortcut(void)
{ return 0; }

unsigned short Element::GetShortcutChar(void)
{ return 0; }

int Element::GetTextGlowSize(void)
{ return 0; }

long Element::GetTheme(unsigned short const*a0, void**a1)
{ return 0; }

bool Element::GetTooltip(void)
{ return 0; }

int Element::GetTooltipMaxWidth(void)
{ return 0; }

Element* Element::GetTopLevel(void)
{ return nullptr; }

float Element::GetTreeAlphaLevel(void)
{ return 0; }

long Element::GetUIAElementProvider(_GUID const&a0, void**a1)
{ return 0; }

Element* Element::GetUiaFocusDelegate(void)
{ return nullptr; }

Value* Element::GetValue(PropertyInfo const* (__cdecl * a0)(void), int a1, UpdateCache*a2)
{ return nullptr; }

Value* Element::GetValue(PropertyInfo const*a0, int a1, UpdateCache*a2)
{ return nullptr; }

bool Element::GetVisible(void)
{ return 0; }

int Element::GetWidth(void)
{ return 0; }

bool Element::GetWindowActive(void)
{ return 0; }

int Element::GetX(void)
{ return 0; }

int Element::GetY(void)
{ return 0; }

void Element::HandleUiaDestroyListener(void)
{}

void Element::HandleUiaEventListener(Event*a0)
{}

void Element::HandleUiaPropertyChangingListener(PropertyInfo const*a0)
{}

void Element::HandleUiaPropertyListener(PropertyInfo const*a0, int a1, Value*a2, Value*a3)
{}

bool Element::HasAnimation(void)
{ return 0; }

bool Element::HasBorder(void)
{ return 0; }

bool Element::HasChildren(void)
{ return 0; }

bool Element::HasContent(void)
{ return 0; }

bool Element::HasEdgeHighlight(void)
{ return 0; }

bool Element::HasLayout(void)
{ return 0; }

bool Element::HasMargin(void)
{ return 0; }

bool Element::HasPVLAnimationState(unsigned int a0)
{ return 0; }

bool Element::HasPadding(void)
{ return 0; }

PropertyInfo const* Element::HeightProp(void)
{ return nullptr; }

PropertyInfo const* Element::HighDPIProp(void)
{ return nullptr; }

PropertyInfo const* Element::IDProp(void)
{ return nullptr; }

long Element::Initialize(unsigned int a0, Element*a1, unsigned long*a2)
{ return 0; }

long Element::Insert(Element*a0, unsigned int a1)
{ return 0; }

long Element::Insert(Element**a0, unsigned int a1, unsigned int a2)
{ return 0; }

void Element::InvokeAnimation(int a0, unsigned int a1)
{}

void Element::InvokeAnimation(unsigned int a0, unsigned int a1, float a2, float a3, bool a4)
{}

bool Element::IsBehaviorLayout(void) const
{ return 0; }

bool Element::IsCompositedText(void)
{ return 0; }

bool Element::IsContentProtected(void)
{ return 0; }

bool Element::IsDefaultCAlign(void)
{ return 0; }

bool Element::IsDefaultCursor(void)
{ return 0; }

bool Element::IsDescendent(Element*a0)
{ return 0; }

bool Element::IsDestroyed(void)
{ return 0; }

bool Element::IsHosted(void)
{ return 0; }

bool Element::IsPointValid(double a0, double a1)
{ return 0; }

bool Element::IsRTL(void)
{ return 0; }

bool Element::IsRTLReading(void)
{ return 0; }

int Element::IsRoot(void)
{ return 0; }

bool Element::IsSelfLayout(void)
{ return 0; }

bool Element::IsValidAccessor(PropertyInfo const*a0, int a1, bool a2)
{ return 0; }

bool Element::IsValidValue(PropertyInfo const*a0, Value*a1)
{ return 0; }

bool Element::IsWordWrap(void)
{ return 0; }

PropertyInfo const* Element::KeyFocusedProp(void)
{ return nullptr; }

PropertyInfo const* Element::KeyWithinProp(void)
{ return nullptr; }

UID Element::KeyboardNavigate(void)
{ return UID(); }

PropertyInfo const* Element::LastDSConstProp(void)
{ return nullptr; }

PropertyInfo const* Element::LayoutPosProp(void)
{ return nullptr; }

PropertyInfo const* Element::LayoutProp(void)
{ return nullptr; }

PropertyInfo const* Element::LocationProp(void)
{ return nullptr; }

void Element::MapElementPoint(Element*a0, tagPOINT const*a1, tagPOINT*a2)
{}

PropertyInfo const* Element::MarginProp(void)
{ return nullptr; }

void Element::MarkHosted(void)
{}

void Element::MarkNeedsDSUpdate(void)
{}

void Element::MarkSelfLayout(void)
{}

unsigned int Element::MessageCallback(tagGMSG*a0)
{ return 0; }

PropertyInfo const* Element::MinSizeProp(void)
{ return nullptr; }

PropertyInfo const* Element::MouseFocusedProp(void)
{ return nullptr; }

PropertyInfo const* Element::MouseWithinProp(void)
{ return nullptr; }

bool Element::NeedsDSUpdate(void)
{ return 0; }

void Element::OnDestroy(void)
{}

void Element::OnEvent(Event*a0)
{}

void Element::OnGroupChanged(int a0, bool a1)
{}

void Element::OnHosted(Element*a0)
{}

void Element::OnInput(InputEvent*a0)
{}

void Element::OnKeyFocusMoved(Element*a0, Element*a1)
{}

void Element::OnMouseFocusMoved(Element*a0, Element*a1)
{}

void Element::OnPropertyChanged(PropertyInfo*a0, int a1, Value*a2, Value*a3)
{}

void Element::OnPropertyChanged(PropertyInfo const*a0, int a1, Value*a2, Value*a3)
{}

bool Element::OnPropertyChanging(PropertyInfo*a0, int a1, Value*a2, Value*a3)
{ return 0; }

bool Element::OnPropertyChanging(PropertyInfo const*a0, int a1, Value*a2, Value*a3)
{ return 0; }

void Element::OnUnHosted(Element*a0)
{}

PropertyInfo const* Element::OverhangProp(void)
{ return nullptr; }

PropertyInfo const* Element::PaddingProp(void)
{ return nullptr; }

void Element::Paint(HDC__*a0, tagRECT const*a1, tagRECT const*a2, tagRECT*a3, tagRECT*a4)
{}

void Element::PaintBackground(HDC__*a0, Value*a1, tagRECT const&a2, tagRECT const&a3, tagRECT const&a4, tagRECT const&a5)
{}

void Element::PaintBorder(HDC__*a0, Value*a1, tagRECT*a2, tagRECT const&a3)
{}

void Element::PaintContent(HDC__*a0, tagRECT const*a1)
{}

void Element::PaintEdgeHighlight(HDC__*a0, tagRECT const&a1, tagRECT const&a2)
{}

void Element::PaintFocusRect(HDC__*a0, tagRECT const*a1, tagRECT const*a2)
{}

void Element::PaintStringContent(HDC__*a0, tagRECT const*a1, Value*a2, int a3)
{}

PropertyInfo const* Element::ParentProp(void)
{ return nullptr; }

PropertyInfo const* Element::PosInLayoutProp(void)
{ return nullptr; }

long Element::QueryInterface(_GUID const&a0, void**a1)
{ return 0; }

long Element::QueueDefaultAction(void)
{ return 0; }

long Element::Register(void)
{ return 0; }

unsigned long Element::Release(void)
{ return 0; }

long Element::Remove(Element*a0)
{ return 0; }

long Element::Remove(Element**a0, unsigned int a1)
{ return 0; }

long Element::RemoveAll(void)
{ return 0; }

long Element::RemoveBehavior(IDuiBehavior*a0)
{ return 0; }

void Element::RemoveListener(IElementListener*a0)
{}

long Element::RemoveLocalValue(PropertyInfo const* (__cdecl * a0)(void))
{ return 0; }

long Element::RemoveLocalValue(PropertyInfo const*a0)
{ return 0; }

unsigned short* Element::RemoveShortcutFromName(unsigned short const*a0)
{ return nullptr; }

void Element::RemoveTooltip(Element*a0)
{}

PropertyInfo const* Element::ScaleFactorProp(void)
{ return nullptr; }

PropertyInfo const* Element::SelectedProp(void)
{ return nullptr; }

long Element::SetAbsorbsShortcut(bool a0)
{ return 0; }

long Element::SetAccDefAction(unsigned short const*a0)
{ return 0; }

long Element::SetAccDesc(unsigned short const*a0)
{ return 0; }

long Element::SetAccHelp(unsigned short const*a0)
{ return 0; }

long Element::SetAccItemStatus(unsigned short const*a0)
{ return 0; }

long Element::SetAccItemType(unsigned short const*a0)
{ return 0; }

long Element::SetAccName(unsigned short const*a0)
{ return 0; }

long Element::SetAccRole(int a0)
{ return 0; }

long Element::SetAccState(int a0)
{ return 0; }

long Element::SetAccValue(unsigned short const*a0)
{ return 0; }

long Element::SetAccessible(bool a0)
{ return 0; }

long Element::SetActive(int a0)
{ return 0; }

long Element::SetAlpha(int a0)
{ return 0; }

long Element::SetAnimation(int a0)
{ return 0; }

long Element::SetBackgroundColor(Fill const&a0)
{ return 0; }

long Element::SetBackgroundColor(unsigned long a0)
{ return 0; }

long Element::SetBackgroundColor(unsigned long a0, unsigned long a1, unsigned char a2)
{ return 0; }

long Element::SetBackgroundColor(unsigned long a0, unsigned long a1, unsigned long a2, unsigned char a3)
{ return 0; }

long Element::SetBackgroundColor(unsigned short const*a0, int a1, int a2)
{ return 0; }

long Element::SetBackgroundStdColor(int a0)
{ return 0; }

long Element::SetBorderColor(unsigned long a0)
{ return 0; }

long Element::SetBorderGradientColor(unsigned long a0, unsigned long a1, unsigned char a2)
{ return 0; }

long Element::SetBorderStdColor(int a0)
{ return 0; }

long Element::SetBorderStyle(int a0)
{ return 0; }

long Element::SetBorderThickness(int a0, int a1, int a2, int a3)
{ return 0; }

long Element::SetClass(unsigned short const*a0)
{ return 0; }

void Element::SetClassInfoPtr(IClassInfo*a0)
{}

long Element::SetCompositedText(bool a0)
{ return 0; }

long Element::SetContentAlign(int a0)
{ return 0; }

long Element::SetContentGraphic(unsigned short const*a0, unsigned char a1, unsigned int a2)
{ return 0; }

long Element::SetContentGraphic(unsigned short const*a0, unsigned short a1, unsigned short a2)
{ return 0; }

long Element::SetContentString(unsigned short const*a0)
{ return 0; }

long Element::SetCursor(unsigned short const*a0)
{ return 0; }

long Element::SetCursorHandle(HICON__*a0)
{ return 0; }

long Element::SetDirection(int a0)
{ return 0; }

long Element::SetEdgeHighlightColor(unsigned long a0)
{ return 0; }

long Element::SetEdgeHighlightThickness(int a0, int a1, int a2, int a3)
{ return 0; }

long Element::SetEnabled(bool a0)
{ return 0; }

long Element::SetEncodedContentString(unsigned short const*a0)
{ return 0; }

long Element::SetFont(unsigned short const*a0)
{ return 0; }

long Element::SetFontFace(unsigned short const*a0)
{ return 0; }

long Element::SetFontQuality(int a0)
{ return 0; }

long Element::SetFontSize(int a0)
{ return 0; }

long Element::SetFontStyle(int a0)
{ return 0; }

long Element::SetFontWeight(int a0)
{ return 0; }

long Element::SetForegroundColor(unsigned long a0)
{ return 0; }

long Element::SetForegroundColor(unsigned long a0, unsigned long a1, unsigned char a2)
{ return 0; }

long Element::SetForegroundColor(unsigned long a0, unsigned long a1, unsigned long a2, unsigned char a3)
{ return 0; }

long Element::SetForegroundStdColor(int a0)
{ return 0; }

long Element::SetHeight(int a0)
{ return 0; }

long Element::SetID(unsigned short const*a0)
{ return 0; }

void Element::SetKeyFocus(void)
{}

long Element::SetLayout(Layout*a0)
{ return 0; }

void Element::SetLayoutCompletionNotify(bool a0)
{}

long Element::SetLayoutPos(int a0)
{ return 0; }

long Element::SetMargin(int a0, int a1, int a2, int a3)
{ return 0; }

long Element::SetMinSize(int a0, int a1)
{ return 0; }

long Element::SetOverhang(bool a0)
{ return 0; }

void Element::SetOverrideScaleFactor(float a0)
{}

void Element::SetPVLAnimationState(int a0)
{}

long Element::SetPadding(int a0, int a1, int a2, int a3)
{ return 0; }

void Element::SetPreserveAlphaChannel(bool a0)
{}

long Element::SetRelPixHeight(int a0)
{ return 0; }

long Element::SetRelPixMargin(int a0, int a1, int a2, int a3)
{ return 0; }

long Element::SetRelPixPadding(int a0, int a1, int a2, int a3)
{ return 0; }

long Element::SetRelPixWidth(int a0)
{ return 0; }

long Element::SetSelected(bool a0)
{ return 0; }

long Element::SetShadowIntensity(int a0)
{ return 0; }

long Element::SetSheet(StyleSheet*a0)
{ return 0; }

long Element::SetShortcut(int a0)
{ return 0; }

long Element::SetStdCursor(int a0)
{ return 0; }

long Element::SetTextGlowSize(int a0)
{ return 0; }

long Element::SetTooltip(bool a0)
{ return 0; }

long Element::SetTooltipMaxWidth(int a0)
{ return 0; }

long Element::SetValue(PropertyInfo const* (__cdecl * a0)(void), int a1, Value*a2)
{ return 0; }

long Element::SetValue(PropertyInfo const*a0, int a1, Value*a2)
{ return 0; }

long Element::SetVisible(bool a0)
{ return 0; }

long Element::SetWidth(int a0)
{ return 0; }

long Element::SetWindowActive(bool a0)
{ return 0; }

long Element::SetX(int a0)
{ return 0; }

long Element::SetY(int a0)
{ return 0; }

PropertyInfo const* Element::ShadowIntensityProp(void)
{ return nullptr; }

PropertyInfo const* Element::SheetProp(void)
{ return nullptr; }

long Element::ShiftChild(unsigned int a0, unsigned int a1)
{ return 0; }

PropertyInfo const* Element::ShortcutProp(void)
{ return nullptr; }

PropertyInfo const* Element::SizeInLayoutProp(void)
{ return nullptr; }

long Element::SortChildren(int (__cdecl * a0)(void const*, void const*))
{ return 0; }

void Element::StartDefer(unsigned long*a0)
{}

void Element::StopAnimation(unsigned int a0)
{}

DeferCycle* Element::TestDeferObject(void)
{ return nullptr; }

PropertyInfo const* Element::TextGlowSizeProp(void)
{ return nullptr; }

PropertyInfo const* Element::TooltipMaxWidthProp(void)
{ return nullptr; }

PropertyInfo const* Element::TooltipProp(void)
{ return nullptr; }

bool Element::TryLinePattern(tagPOINT*a0, tagRECT const&a1)
{ return 0; }

bool Element::TryPattern(double a0, double a1, tagPOINT*a2, tagRECT const&a3)
{ return 0; }

bool Element::TrySparsePattern(tagPOINT*a0, tagRECT const&a1)
{ return 0; }

bool Element::UiaEvents(void)
{ return 0; }

long Element::UnRegister(IClassInfo**a0)
{ return 0; }

void Element::UpdateLayout(void)
{}

void Element::UpdateTooltip(Element*a0)
{}

PropertyInfo const* Element::UsesDesktopPerMonitorScalingProp(void)
{ return nullptr; }

PropertyInfo const* Element::VisibleProp(void)
{ return nullptr; }

PropertyInfo const* Element::WidthProp(void)
{ return nullptr; }

PropertyInfo const* Element::WindowActiveProp(void)
{ return nullptr; }

PropertyInfo const* Element::XProp(void)
{ return nullptr; }

PropertyInfo const* Element::YProp(void)
{ return nullptr; }

void Element::_AddDependency(Element*a0, PropertyInfo const*a1, int a2, DepRecs*a3, DeferCycle*a4, long*a5)
{}

void Element::_BroadcastEventWorker(Event*a0)
{}

int Element::_CachedValueIsEqual(PropertyInfo const*a0, Element*a1)
{ return 0; }

void Element::_ClearNeedsLayout(void)
{}

long Element::_DisplayNodeCallback(HGADGET__*a0, void*a1, EventMsg*a2)
{ return 0; }

void Element::_EndOptimizedLayoutQ(void)
{}

void Element::_Fill(HDC__*a0, unsigned long a1, int a2, int a3, int a4, int a5, bool a6)
{}

void Element::_FlushDS(DeferCycle*a0)
{}

void Element::_FlushLayout(Element*a0, DeferCycle*a1)
{}

void Element::_GetBuriedSheetDependencies(PropertyInfo const*a0, Element*a1, DepRecs*a2, DeferCycle*a3, long*a4)
{}

int Element::_GetChangesUpdatePass(void)
{ return 0; }

Value* Element::_GetComputedValue(PropertyInfo const*a0, UpdateCache*a1)
{ return nullptr; }

long Element::_GetDependencies(PropertyInfo const*a0, int a1, DepRecs*a2, int a3, Value*a4, DeferCycle*a5)
{ return 0; }

Value* Element::_GetLocalValue(PropertyInfo const*a0)
{ return nullptr; }

Value* Element::_GetLocalValueFromVM(PropertyInfo const*a0)
{ return nullptr; }

unsigned int Element::_GetNeedsLayout(void)
{ return 0; }

Value* Element::_GetSpecifiedValue(PropertyInfo const*a0, UpdateCache*a1)
{ return nullptr; }

Value* Element::_GetSpecifiedValueIgnoreCache(PropertyInfo const*a0)
{ return nullptr; }

void Element::_InheritProperties(void)
{}

void Element::_InvalidateCachedDSConstraints(Element*a0)
{}

int Element::_MarkElementForDS(Element*a0)
{ return 0; }

int Element::_MarkElementForLayout(Element*a0, unsigned int a1)
{ return 0; }

void Element::_OnFontPropChanged(Value*a0)
{}

void Element::_PostEvent(Event*a0, int a1)
{}

long Element::_PostSourceChange(void)
{ return 0; }

long Element::_PreSourceChange(PropertyInfo const* (__cdecl * a0)(void), int a1, Value*a2, Value*a3)
{ return 0; }

long Element::_PreSourceChange(PropertyInfo const*a0, int a1, Value*a2, Value*a3)
{ return 0; }

long Element::_RemoveLocalValue(PropertyInfo const* (__cdecl * a0)(void), bool a1)
{ return 0; }

long Element::_RemoveLocalValue(PropertyInfo const*a0, bool a1)
{ return 0; }

void Element::_SelfLayoutDoLayout(int a0, int a1)
{}

tagSIZE Element::_SelfLayoutUpdateDesiredSize(int a0, int a1, Surface*a2)
{ return tagSIZE{}; }

bool Element::_SetGroupChanges(Element*a0, int a1, DeferCycle*a2)
{ return 0; }

int Element::_SetNeedsLayout(unsigned int a0)
{ return 0; }

long Element::_SetRelPixRect(PropertyInfo const*a0, int a1, int a2, int a3, int a4)
{ return 0; }

long Element::_SetRelPixValue(PropertyInfo const*a0, int a1)
{ return 0; }

long Element::_SetValue(PropertyInfo const* (__cdecl * a0)(void), int a1, Value*a2, bool a3)
{ return 0; }

long Element::_SetValue(PropertyInfo const*a0, int a1, Value*a2, bool a3)
{ return 0; }

void Element::_StartOptimizedLayoutQ(void)
{}

void Element::_SyncBackground(void)
{}

void Element::_SyncRedrawStyle(void)
{}

void Element::_SyncVisible(void)
{}

void Element::_TransferGroupFlags(Element*a0, int a1)
{}

tagSIZE Element::_UpdateDesiredSize(int a0, int a1, Surface*a2)
{ return tagSIZE{}; }

void Element::_UpdateLayoutPosition(int a0, int a1)
{}

void Element::_UpdateLayoutSize(int a0, int a1)
{}

void Element::_UpdatePropertyInCache(PropertyInfo const*a0)
{}

void Element::_VoidPCNotifyTree(int a0, DeferCycle*a1)
{}

bool Element::s_HandleDUIEventMessage(Element*a0, EventMsg*a1)
{ return 0; }

IClassInfo* Element::s_pClassInfo = nullptr;

} // namespace DirectUI
