// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::Expando.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "Expando.h"
#include "Interfaces.h"

namespace DirectUI
{

Expando::Expando(Expando&&a0)
{ }

Expando::Expando(Expando const&a0)
{ }

Expando::Expando(void)
{ }

Expando::~Expando(void)
{}

Expando& Expando::operator=(Expando&&a0)
{ return *this; }

Expando& Expando::operator=(Expando const&a0)
{ return *this; }

long Expando::Add(Element**a0, unsigned int a1)
{ return 0; }

unsigned short Expando::Arrow(void)
{ return 0; }

unsigned short Expando::Clipper(void)
{ return 0; }

long Expando::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

IClassInfo* Expando::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* Expando::GetClassInfoW(void)
{ return nullptr; }

long Expando::Initialize(Element*a0, unsigned long*a1)
{ return 0; }

void Expando::OnEvent(Event*a0)
{}

void Expando::OnPropertyChanged(PropertyInfo const*a0, int a1, Value*a2, Value*a3)
{}

long Expando::Register(void)
{ return 0; }

void Expando::SetClassInfoPtr(IClassInfo*a0)
{}

void Expando::UpdateChildren(Value*a0)
{}

unsigned short Expando::_atmArrow = 0;

unsigned short Expando::_atmClipper = 0;

IClassInfo* Expando::s_pClassInfo = nullptr;

} // namespace DirectUI
