// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::ExpandoButtonGlyph.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "ExpandoButtonGlyph.h"
#include "Interfaces.h"

namespace DirectUI
{

ExpandoButtonGlyph::ExpandoButtonGlyph(ExpandoButtonGlyph const&a0)
{ }

ExpandoButtonGlyph::ExpandoButtonGlyph(void)
{ }

ExpandoButtonGlyph::~ExpandoButtonGlyph(void)
{}

ExpandoButtonGlyph& ExpandoButtonGlyph::operator=(ExpandoButtonGlyph const&a0)
{ return *this; }

long ExpandoButtonGlyph::Create(unsigned int a0, Element*a1, unsigned long*a2, Element**a3)
{ return 0; }

long ExpandoButtonGlyph::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

IClassInfo* ExpandoButtonGlyph::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* ExpandoButtonGlyph::GetClassInfoW(void)
{ return nullptr; }

long ExpandoButtonGlyph::Initialize(unsigned int a0, Element*a1, unsigned long*a2)
{ return 0; }

bool ExpandoButtonGlyph::OnLostDialogFocus(IDialogElement*a0)
{ return 0; }

bool ExpandoButtonGlyph::OnReceivedDialogFocus(IDialogElement*a0)
{ return 0; }

long ExpandoButtonGlyph::Register(void)
{ return 0; }

void ExpandoButtonGlyph::SetClassInfoPtr(IClassInfo*a0)
{}

IClassInfo* ExpandoButtonGlyph::s_pClassInfo = nullptr;

} // namespace DirectUI
