// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::FontCache.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "FontCache.h"

namespace DirectUI
{

FontCache::FontCache(FontCache&&a0)
{ }

FontCache::FontCache(FontCache const&a0)
{ }

FontCache::FontCache(void)
{ }

FontCache& FontCache::operator=(FontCache&&a0)
{ return *this; }

FontCache& FontCache::operator=(FontCache const&a0)
{ return *this; }

long FontCache::InitProcess(void)
{ return 0; }

long FontCache::InitThread(void)
{ return 0; }

void FontCache::UninitProcess(void)
{}

void FontCache::UninitThread(void)
{}

} // namespace DirectUI
