// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::HWNDElementAccessible.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "HWNDElementAccessible.h"

namespace DirectUI
{

HWNDElementAccessible::HWNDElementAccessible(void)
{ }

HWNDElementAccessible::~HWNDElementAccessible(void)
{}

long HWNDElementAccessible::Create(HWNDElement*a0, DuiAccessible**a1)
{ return 0; }

long HWNDElementAccessible::Disconnect(void)
{ return 0; }

long HWNDElementAccessible::Initialize(HWNDElement*a0)
{ return 0; }

long HWNDElementAccessible::get_accParent(IDispatch**a0)
{ return 0; }

} // namespace DirectUI
