// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::HWNDElementProxy.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "HWNDElementProxy.h"

namespace DirectUI
{

HWNDElementProxy::HWNDElementProxy(void)
{ }

HWNDElementProxy::HWNDElementProxy(HWNDElementProxy&&a0)
{ }

HWNDElementProxy::HWNDElementProxy(HWNDElementProxy const&a0)
{ }

HWNDElementProxy& HWNDElementProxy::operator=(HWNDElementProxy&&a0)
{ return *this; }

HWNDElementProxy& HWNDElementProxy::operator=(HWNDElementProxy const&a0)
{ return *this; }

HWNDElementProxy* HWNDElementProxy::Create(HWNDElement*a0)
{ return nullptr; }

long HWNDElementProxy::DoMethod(int a0, char*a1)
{ return 0; }

long HWNDElementProxy::ElementFromPoint(double a0, double a1, IRawElementProviderFragment**a2)
{ return 0; }

long HWNDElementProxy::GetFocus(IRawElementProviderFragment**a0)
{ return 0; }

void HWNDElementProxy::Init(HWNDElement*a0)
{}

} // namespace DirectUI
