// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::HWNDHostAccessible.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "HWNDHostAccessible.h"

namespace DirectUI
{

HWNDHostAccessible::HWNDHostAccessible(void)
{ }

HWNDHostAccessible::~HWNDHostAccessible(void)
{}

long HWNDHostAccessible::Clone(IEnumVARIANT**a0)
{ return 0; }

long HWNDHostAccessible::ContextSensitiveHelp(int a0)
{ return 0; }

long HWNDHostAccessible::Create(Element*a0, IAccessible*a1, DuiAccessible**a2)
{ return 0; }

long HWNDHostAccessible::Disconnect(void)
{ return 0; }

long HWNDHostAccessible::GetIdentityString(unsigned long a0, unsigned char**a1, unsigned long*a2)
{ return 0; }

long HWNDHostAccessible::GetWindow(HWND__**a0)
{ return 0; }

long HWNDHostAccessible::Initialize(Element*a0, IAccessible*a1)
{ return 0; }

long HWNDHostAccessible::Next(unsigned long a0, tagVARIANT*a1, unsigned long*a2)
{ return 0; }

long HWNDHostAccessible::QueryInterface(_GUID const&a0, void**a1)
{ return 0; }

long HWNDHostAccessible::QueryService(_GUID const&a0, _GUID const&a1, void**a2)
{ return 0; }

long HWNDHostAccessible::Reset(void)
{ return 0; }

long HWNDHostAccessible::Skip(unsigned long a0)
{ return 0; }

long HWNDHostAccessible::accDoDefaultAction(tagVARIANT a0)
{ return 0; }

long HWNDHostAccessible::accHitTest(long a0, long a1, tagVARIANT*a2)
{ return 0; }

long HWNDHostAccessible::accLocation(long*a0, long*a1, long*a2, long*a3, tagVARIANT a4)
{ return 0; }

long HWNDHostAccessible::accNavigate(long a0, tagVARIANT a1, tagVARIANT*a2)
{ return 0; }

long HWNDHostAccessible::accSelect(long a0, tagVARIANT a1)
{ return 0; }

long HWNDHostAccessible::get_accChild(tagVARIANT a0, IDispatch**a1)
{ return 0; }

long HWNDHostAccessible::get_accChildCount(long*a0)
{ return 0; }

long HWNDHostAccessible::get_accDefaultAction(tagVARIANT a0, unsigned short**a1)
{ return 0; }

long HWNDHostAccessible::get_accDescription(tagVARIANT a0, unsigned short**a1)
{ return 0; }

long HWNDHostAccessible::get_accFocus(tagVARIANT*a0)
{ return 0; }

long HWNDHostAccessible::get_accHelp(tagVARIANT a0, unsigned short**a1)
{ return 0; }

long HWNDHostAccessible::get_accHelpTopic(unsigned short**a0, tagVARIANT a1, long*a2)
{ return 0; }

long HWNDHostAccessible::get_accKeyboardShortcut(tagVARIANT a0, unsigned short**a1)
{ return 0; }

long HWNDHostAccessible::get_accName(tagVARIANT a0, unsigned short**a1)
{ return 0; }

long HWNDHostAccessible::get_accParent(IDispatch**a0)
{ return 0; }

long HWNDHostAccessible::get_accRole(tagVARIANT a0, tagVARIANT*a1)
{ return 0; }

long HWNDHostAccessible::get_accSelection(tagVARIANT*a0)
{ return 0; }

long HWNDHostAccessible::get_accState(tagVARIANT a0, tagVARIANT*a1)
{ return 0; }

long HWNDHostAccessible::get_accValue(tagVARIANT a0, unsigned short**a1)
{ return 0; }

long HWNDHostAccessible::put_accName(tagVARIANT a0, unsigned short*a1)
{ return 0; }

long HWNDHostAccessible::put_accValue(tagVARIANT a0, unsigned short*a1)
{ return 0; }

} // namespace DirectUI
