// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::IDataEntry.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "IDataEntry.h"

namespace DirectUI
{

IDataEntry::IDataEntry(IDataEntry const&a0)
{ }

IDataEntry::IDataEntry(void)
{ }

IDataEntry::~IDataEntry(void)
{}

IDataEntry& IDataEntry::operator=(IDataEntry const&a0)
{ return *this; }

} // namespace DirectUI
