// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::InvokeHelper.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "InvokeHelper.h"

namespace DirectUI
{

InvokeHelper::InvokeHelper(void)
{ }

InvokeHelper::~InvokeHelper(void)
{}

long InvokeHelper::DoInvoke(int a0, ElementProvider*a1, ProviderProxy* (__cdecl * a2)(Element*), char*a3)
{ return 0; }

int InvokeHelper::Init(unsigned long a0)
{ return 0; }

void InvokeHelper::OnInvoke(InvokeHelper::InvokeArgs*a0)
{}

void InvokeHelper::Uninit(void)
{}

int InvokeHelper::_WndProc(void*a0, HWND__*a1, unsigned int a2, unsigned __int64 a3, __int64 a4, __int64*a5)
{ return 0; }

unsigned int const InvokeHelper::s_uInvokeHelperMsg = 0;

} // namespace DirectUI
