// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::ISBLeak.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "ISBLeak.h"

namespace DirectUI
{

ISBLeak::ISBLeak(ISBLeak&&a0) = default;

ISBLeak::ISBLeak(ISBLeak const&a0) = default;

ISBLeak::ISBLeak(void) = default;

ISBLeak& ISBLeak::operator=(ISBLeak&&a0) = default;

ISBLeak& ISBLeak::operator=(ISBLeak const&a0) = default;

} // namespace DirectUI
