// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::IXProviderCP.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "IXProviderCP.h"

namespace DirectUI
{

IXProviderCP::IXProviderCP(IXProviderCP&&a0)
{ }

IXProviderCP::IXProviderCP(IXProviderCP const&a0)
{ }

IXProviderCP::IXProviderCP(void)
{ }

IXProviderCP& IXProviderCP::operator=(IXProviderCP&&a0)
{ return *this; }

IXProviderCP& IXProviderCP::operator=(IXProviderCP const&a0)
{ return *this; }

} // namespace DirectUI
