// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::LinkedList.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "LinkedList.h"

namespace DirectUI
{

LinkedList::LinkedList(void)
{ }

LinkedList::~LinkedList(void)
{}

LinkedList& LinkedList::operator=(LinkedList const&a0)
{ return *this; }

void LinkedList::Add(LinkedListNode*a0)
{}

void LinkedList::Remove(LinkedListNode*a0)
{}

LinkedListNode* LinkedList::RemoveTail(void)
{ return nullptr; }

} // namespace DirectUI
