// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::Macro.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "Macro.h"
#include "Interfaces.h"

namespace DirectUI
{

Macro::Macro(Macro&&a0)
{ }

Macro::Macro(Macro const&a0)
{ }

Macro::Macro(void)
{ }

Macro::~Macro(void)
{}

Macro& Macro::operator=(Macro&&a0)
{ return *this; }

Macro& Macro::operator=(Macro const&a0)
{ return *this; }

long Macro::Add(Element**a0, unsigned int a1)
{ return 0; }

long Macro::BuildElement(void)
{ return 0; }

long Macro::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

PropertyInfo const* Macro::ExpandProp(void)
{ return nullptr; }

IClassInfo* Macro::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* Macro::GetClassInfoW(void)
{ return nullptr; }

IDataEntry* Macro::GetDataEntry(void)
{ return nullptr; }

unsigned short const* Macro::GetExpand(Value**a0)
{ return nullptr; }

long Macro::Initialize(Element*a0, unsigned long*a1)
{ return 0; }

void Macro::OnPropertyChanged(PropertyInfo const*a0, int a1, Value*a2, Value*a3)
{}

long Macro::Register(void)
{ return 0; }

void Macro::ResolveBindings(void)
{}

void Macro::SetClassInfoPtr(IClassInfo*a0)
{}

void Macro::SetDataEntry(IDataEntry*a0, Element*a1)
{}

void Macro::SetDefaultGraphicType(unsigned char a0, bool a1)
{}

long Macro::SetExpand(unsigned short const*a0)
{ return 0; }

void Macro::SetParser(DUIXmlParser*a0)
{}

void Macro::_BitAccurateFillRect(HDC__*a0, int a1, int a2, int a3, int a4, unsigned char a5, unsigned char a6, unsigned char a7, unsigned char a8, unsigned long a9)
{}

bool Macro::_GetBitmapSize(HBITMAP__*a0, tagSIZE*a1)
{ return 0; }

Value* Macro::_LoadImage32BitsPerPixel(unsigned short const*a0)
{ return nullptr; }

IClassInfo* Macro::s_pClassInfo = nullptr;

} // namespace DirectUI
