// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::ModernProgressBarRangeValueProxy.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "ModernProgressBarRangeValueProxy.h"

namespace DirectUI
{

ModernProgressBarRangeValueProxy::ModernProgressBarRangeValueProxy(ModernProgressBarRangeValueProxy&&a0)
{ }

ModernProgressBarRangeValueProxy::ModernProgressBarRangeValueProxy(ModernProgressBarRangeValueProxy const&a0)
{ }

ModernProgressBarRangeValueProxy::ModernProgressBarRangeValueProxy(void)
{ }

ModernProgressBarRangeValueProxy& ModernProgressBarRangeValueProxy::operator=(ModernProgressBarRangeValueProxy&&a0)
{ return *this; }

ModernProgressBarRangeValueProxy& ModernProgressBarRangeValueProxy::operator=(ModernProgressBarRangeValueProxy const&a0)
{ return *this; }

long ModernProgressBarRangeValueProxy::DoMethod(int a0, char*a1)
{ return 0; }

void ModernProgressBarRangeValueProxy::Init(Element*a0)
{}

} // namespace DirectUI
