// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::NavigatorSelectionItemProxy.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "NavigatorSelectionItemProxy.h"

namespace DirectUI
{

NavigatorSelectionItemProxy::NavigatorSelectionItemProxy(NavigatorSelectionItemProxy&&a0)
{ }

NavigatorSelectionItemProxy::NavigatorSelectionItemProxy(NavigatorSelectionItemProxy const&a0)
{ }

NavigatorSelectionItemProxy::NavigatorSelectionItemProxy(void)
{ }

NavigatorSelectionItemProxy& NavigatorSelectionItemProxy::operator=(NavigatorSelectionItemProxy&&a0)
{ return *this; }

NavigatorSelectionItemProxy& NavigatorSelectionItemProxy::operator=(NavigatorSelectionItemProxy const&a0)
{ return *this; }

long NavigatorSelectionItemProxy::AddToSelection(Browser*a0)
{ return 0; }

long NavigatorSelectionItemProxy::DoMethod(int a0, char*a1)
{ return 0; }

long NavigatorSelectionItemProxy::GetIsSelected(Browser*a0, int*a1)
{ return 0; }

void NavigatorSelectionItemProxy::Init(Element*a0)
{}

} // namespace DirectUI
