// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::NavReference.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "NavReference.h"

namespace DirectUI
{

NavReference& NavReference::operator=(NavReference&&a0) = default;

NavReference& NavReference::operator=(NavReference const&a0) = default;

void NavReference::Init(Element*a0, tagRECT*a1)
{}

} // namespace DirectUI
