// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::NavScoring.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "NavScoring.h"

namespace DirectUI
{

NavScoring& NavScoring::operator=(NavScoring&&a0) = default;

NavScoring& NavScoring::operator=(NavScoring const&a0) = default;

void NavScoring::Init(Element*a0, int a1, NavReference const*a2)
{}

int NavScoring::TrackScore(Element*a0, Element*a1)
{ return 0; }

int NavScoring::Try(Element*a0, int a1, NavReference const*a2, unsigned long a3)
{ return 0; }

} // namespace DirectUI
