// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::NineGridLayout.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "NineGridLayout.h"

namespace DirectUI
{

NineGridLayout::NineGridLayout(NineGridLayout const&a0)
{ }

NineGridLayout::NineGridLayout(void)
{ }

NineGridLayout::~NineGridLayout(void)
{}

NineGridLayout& NineGridLayout::operator=(NineGridLayout const&a0)
{ return *this; }

long NineGridLayout::Create(int a0, int*a1, Value**a2)
{ return 0; }

long NineGridLayout::Create(Layout**a0)
{ return 0; }

void NineGridLayout::DoLayout(Element*a0, int a1, int a2)
{}

Element* NineGridLayout::GetAdjacent(Element*a0, Element*a1, int a2, NavReference const*a3, unsigned long a4)
{ return nullptr; }

void NineGridLayout::Initialize(void)
{}

void NineGridLayout::OnAdd(Element*a0, Element**a1, unsigned int a2)
{}

void NineGridLayout::OnLayoutPosChanged(Element*a0, Element*a1, int a2, int a3)
{}

void NineGridLayout::OnRemove(Element*a0, Element**a1, unsigned int a2)
{}

tagSIZE NineGridLayout::UpdateDesiredSize(Element*a0, int a1, int a2, Surface*a3)
{ return tagSIZE{}; }

void NineGridLayout::_UpdateTileList(int a0, Element*a1)
{}

} // namespace DirectUI
