// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::Page.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "Page.h"
#include "Interfaces.h"

namespace DirectUI
{

Page::Page(Page&&a0)
{ }

Page::Page(Page const&a0)
{ }

Page::Page(void)
{ }

Page::~Page(void)
{}

Page& Page::operator=(Page&&a0)
{ return *this; }

Page& Page::operator=(Page const&a0)
{ return *this; }

long Page::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

IClassInfo* Page::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* Page::GetClassInfoW(void)
{ return nullptr; }

long Page::Initialize(Element*a0, unsigned long*a1)
{ return 0; }

long Page::Register(void)
{ return 0; }

void Page::SetClassInfoPtr(IClassInfo*a0)
{}

IClassInfo* Page::s_pClassInfo = nullptr;

} // namespace DirectUI
