// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::PatternProvider<ScrollProvider, IScrollProvider, 5>.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "PatternProvider_ScrollProvider_IScrollProvider_5.h"

namespace DirectUI
{

PatternProvider<ScrollProvider, IScrollProvider, 5>::PatternProvider<class DirectUI::ScrollProvider, struct IScrollProvider, 5>(void)
{ }

PatternProvider<ScrollProvider, IScrollProvider, 5>::~PatternProvider(void)
{}

long PatternProvider<ScrollProvider, IScrollProvider, 5>::Create(ElementProvider*a0, IUnknown**a1)
{ return 0; }

long PatternProvider<ScrollProvider, IScrollProvider, 5>::DoInvoke(int a0, ...)
{ return 0; }

auto PatternProvider<ScrollProvider, IScrollProvider, 5>::GetProxyCreator(void) -> ProviderProxy* (__cdecl *)(Element*)
{ return nullptr; }

void PatternProvider<ScrollProvider, IScrollProvider, 5>::Init(ElementProvider*a0)
{}

} // namespace DirectUI
