// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::PatternProvider<InvokeProvider, IInvokeProvider, 0>.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "PatternProvider_InvokeProvider_IInvokeProvider_0.h"

namespace DirectUI
{

PatternProvider<InvokeProvider, IInvokeProvider, 0>::PatternProvider<class DirectUI::InvokeProvider, struct IInvokeProvider, 0>(void)
{ }

PatternProvider<InvokeProvider, IInvokeProvider, 0>::~PatternProvider(void)
{}

long PatternProvider<InvokeProvider, IInvokeProvider, 0>::Create(ElementProvider*a0, IUnknown**a1)
{ return 0; }

long PatternProvider<InvokeProvider, IInvokeProvider, 0>::DoInvoke(int a0, ...)
{ return 0; }

auto PatternProvider<InvokeProvider, IInvokeProvider, 0>::GetProxyCreator(void) -> ProviderProxy* (__cdecl *)(Element*)
{ return nullptr; }

void PatternProvider<InvokeProvider, IInvokeProvider, 0>::Init(ElementProvider*a0)
{}

} // namespace DirectUI
