// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::PatternProvider<GridProvider, IGridProvider, 3>.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "PatternProvider_GridProvider_IGridProvider_3.h"

namespace DirectUI
{

PatternProvider<GridProvider, IGridProvider, 3>::PatternProvider<class DirectUI::GridProvider, struct IGridProvider, 3>(void)
{ }

PatternProvider<GridProvider, IGridProvider, 3>::~PatternProvider(void)
{}

long PatternProvider<GridProvider, IGridProvider, 3>::Create(ElementProvider*a0, IUnknown**a1)
{ return 0; }

long PatternProvider<GridProvider, IGridProvider, 3>::DoInvoke(int a0, ...)
{ return 0; }

auto PatternProvider<GridProvider, IGridProvider, 3>::GetProxyCreator(void) -> ProviderProxy* (__cdecl *)(Element*)
{ return nullptr; }

void PatternProvider<GridProvider, IGridProvider, 3>::Init(ElementProvider*a0)
{}

} // namespace DirectUI
