// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::PatternProvider<TableProvider, ITableProvider, 9>.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "PatternProvider_TableProvider_ITableProvider_9.h"

namespace DirectUI
{

PatternProvider<TableProvider, ITableProvider, 9>::PatternProvider<class DirectUI::TableProvider, struct ITableProvider, 9>(void)
{ }

PatternProvider<TableProvider, ITableProvider, 9>::~PatternProvider(void)
{}

long PatternProvider<TableProvider, ITableProvider, 9>::Create(ElementProvider*a0, IUnknown**a1)
{ return 0; }

long PatternProvider<TableProvider, ITableProvider, 9>::DoInvoke(int a0, ...)
{ return 0; }

auto PatternProvider<TableProvider, ITableProvider, 9>::GetProxyCreator(void) -> ProviderProxy* (__cdecl *)(Element*)
{ return nullptr; }

void PatternProvider<TableProvider, ITableProvider, 9>::Init(ElementProvider*a0)
{}

} // namespace DirectUI
