// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::ProviderProxy.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "ProviderProxy.h"

namespace DirectUI
{

ProviderProxy::ProviderProxy(void)
{ }

ProviderProxy::ProviderProxy(ProviderProxy&&a0)
{ }

ProviderProxy::ProviderProxy(ProviderProxy const&a0)
{ }

ProviderProxy& ProviderProxy::operator=(ProviderProxy&&a0)
{ return *this; }

ProviderProxy& ProviderProxy::operator=(ProviderProxy const&a0)
{ return *this; }

void ProviderProxy::Init(Element*a0)
{}

} // namespace DirectUI
