// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::Proxy.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "Proxy.h"

namespace DirectUI
{

Proxy::Proxy(Proxy const&a0)
{ }

Proxy::Proxy(void)
{ }

Proxy::~Proxy(void)
{}

Proxy& Proxy::operator=(Proxy const&a0)
{ return *this; }

void Proxy::Invoke(unsigned int a0, void*a1)
{}

void Proxy::OnInvoke(unsigned int a0, void*a1)
{}

long Proxy::SyncCallback(HGADGET__*a0, void*a1, EventMsg*a2)
{ return 0; }

} // namespace DirectUI
