// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::PushButton.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "PushButton.h"
#include "Interfaces.h"

namespace DirectUI
{

PushButton::PushButton(PushButton&&a0)
{ }

PushButton::PushButton(PushButton const&a0)
{ }

PushButton::PushButton(void)
{ }

PushButton::~PushButton(void)
{}

PushButton& PushButton::operator=(PushButton&&a0)
{ return *this; }

PushButton& PushButton::operator=(PushButton const&a0)
{ return *this; }

long PushButton::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

PropertyInfo const* PushButton::EnforceSizeProp(void)
{ return nullptr; }

void PushButton::FireHostEvent(Element*a0, bool a1)
{}

IClassInfo* PushButton::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* PushButton::GetClassInfoW(void)
{ return nullptr; }

tagSIZE PushButton::GetContentSize(int a0, int a1, Surface*a2)
{ return tagSIZE{}; }

bool PushButton::GetEnforceSize(void)
{ return 0; }

UID PushButton::Hosted(void)
{ return UID(); }

void PushButton::OnHosted(Element*a0)
{}

void PushButton::OnUnHosted(Element*a0)
{}

long PushButton::Register(void)
{ return 0; }

void PushButton::SetClassInfoPtr(IClassInfo*a0)
{}

long PushButton::SetEnforceSize(bool a0)
{ return 0; }

IClassInfo* PushButton::s_pClassInfo = nullptr;

} // namespace DirectUI
