// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::PVLAnimation.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "PVLAnimation.h"

namespace DirectUI
{

PVLAnimation& PVLAnimation::operator=(PVLAnimation&&a0)
{ return *this; }

PVLAnimation& PVLAnimation::operator=(PVLAnimation const&a0)
{ return *this; }

UID PVLAnimation::AnimationStatusChange(void)
{ return UID(); }

UID PVLAnimation::CustomDragDropScalingHint(void)
{ return UID(); }

UID PVLAnimation::CustomReflowHint(void)
{ return UID(); }

UID PVLAnimation::CustomTapHint(void)
{ return UID(); }

UID PVLAnimation::ManualStoryboardVerify(void)
{ return UID(); }

UID PVLAnimation::NotifyComplete(void)
{ return UID(); }

UID PVLAnimation::NotifyImplicit(void)
{ return UID(); }

UID PVLAnimation::NotifyStart(void)
{ return UID(); }

UID PVLAnimation::NotifyStoryboardComplete(void)
{ return UID(); }

UID PVLAnimation::ReflowStyle(void)
{ return UID(); }

UID PVLAnimation::TriggeredAnimationComplete(void)
{ return UID(); }

} // namespace DirectUI
