// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::RadioButtonGlyph.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "RadioButtonGlyph.h"
#include "Interfaces.h"

namespace DirectUI
{

RadioButtonGlyph::RadioButtonGlyph(RadioButtonGlyph const&a0)
{ }

RadioButtonGlyph::RadioButtonGlyph(void)
{ }

RadioButtonGlyph::~RadioButtonGlyph(void)
{}

RadioButtonGlyph& RadioButtonGlyph::operator=(RadioButtonGlyph const&a0)
{ return *this; }

long RadioButtonGlyph::Create(unsigned int a0, Element*a1, unsigned long*a2, Element**a3)
{ return 0; }

long RadioButtonGlyph::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

IClassInfo* RadioButtonGlyph::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* RadioButtonGlyph::GetClassInfoW(void)
{ return nullptr; }

long RadioButtonGlyph::Initialize(unsigned int a0, Element*a1, unsigned long*a2)
{ return 0; }

bool RadioButtonGlyph::OnLostDialogFocus(IDialogElement*a0)
{ return 0; }

bool RadioButtonGlyph::OnReceivedDialogFocus(IDialogElement*a0)
{ return 0; }

long RadioButtonGlyph::Register(void)
{ return 0; }

void RadioButtonGlyph::SetClassInfoPtr(IClassInfo*a0)
{}

IClassInfo* RadioButtonGlyph::s_pClassInfo = nullptr;

} // namespace DirectUI
