// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::RangeValueProvider.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "RangeValueProvider.h"

namespace DirectUI
{

RangeValueProvider::RangeValueProvider(void)
{ }

RangeValueProvider::~RangeValueProvider(void)
{}

unsigned long RangeValueProvider::AddRef(void)
{ return 0; }

auto RangeValueProvider::GetProxyCreator(void) -> ProviderProxy* (__cdecl *)(Element*)
{ return nullptr; }

long RangeValueProvider::QueryInterface(_GUID const&a0, void**a1)
{ return 0; }

unsigned long RangeValueProvider::Release(void)
{ return 0; }

long RangeValueProvider::SetValue(double a0)
{ return 0; }

long RangeValueProvider::get_IsReadOnly(int*a0)
{ return 0; }

long RangeValueProvider::get_LargeChange(double*a0)
{ return 0; }

long RangeValueProvider::get_Maximum(double*a0)
{ return 0; }

long RangeValueProvider::get_Minimum(double*a0)
{ return 0; }

long RangeValueProvider::get_SmallChange(double*a0)
{ return 0; }

long RangeValueProvider::get_Value(double*a0)
{ return 0; }

} // namespace DirectUI
