// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::RangeValueProxy.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "RangeValueProxy.h"

namespace DirectUI
{

RangeValueProxy::RangeValueProxy(void)
{ }

RangeValueProxy::RangeValueProxy(RangeValueProxy&&a0)
{ }

RangeValueProxy::RangeValueProxy(RangeValueProxy const&a0)
{ }

RangeValueProxy& RangeValueProxy::operator=(RangeValueProxy&&a0)
{ return *this; }

RangeValueProxy& RangeValueProxy::operator=(RangeValueProxy const&a0)
{ return *this; }

RangeValueProxy* RangeValueProxy::Create(Element*a0)
{ return nullptr; }

long RangeValueProxy::DoMethod(int a0, char*a1)
{ return 0; }

void RangeValueProxy::Init(Element*a0)
{}

bool RangeValueProxy::IsPatternSupported(Element*a0)
{ return 0; }

} // namespace DirectUI
