// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::RefPointElement.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "RefPointElement.h"
#include "Interfaces.h"

namespace DirectUI
{

RefPointElement::RefPointElement(RefPointElement const&a0)
{ }

RefPointElement::RefPointElement(void)
{ }

RefPointElement::~RefPointElement(void)
{}

RefPointElement& RefPointElement::operator=(RefPointElement const&a0)
{ return *this; }

PropertyInfo const* RefPointElement::ActualReferencePointProp(void)
{ return nullptr; }

long RefPointElement::Create(unsigned int a0, Element*a1, unsigned long*a2, Element**a3)
{ return 0; }

long RefPointElement::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

Element* RefPointElement::FindRefPoint(Element*a0, tagPOINT*a1)
{ return nullptr; }

tagPOINT const* RefPointElement::GetActualReferencePoint(Value**a0)
{ return nullptr; }

IClassInfo* RefPointElement::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* RefPointElement::GetClassInfoW(void)
{ return nullptr; }

tagPOINT const* RefPointElement::GetReferencePoint(Value**a0)
{ return nullptr; }

long RefPointElement::Initialize(unsigned int a0, Element*a1, unsigned long*a2)
{ return 0; }

RefPointElement* RefPointElement::Locate(Element*a0)
{ return nullptr; }

void RefPointElement::OnPropertyChanged(PropertyInfo const*a0, int a1, Value*a2, Value*a3)
{}

PropertyInfo const* RefPointElement::ReferencePointProp(void)
{ return nullptr; }

long RefPointElement::Register(void)
{ return 0; }

void RefPointElement::SetClassInfoPtr(IClassInfo*a0)
{}

long RefPointElement::SetReferencePoint(int a0, int a1)
{ return 0; }

IClassInfo* RefPointElement::s_pClassInfo = nullptr;

} // namespace DirectUI
