// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::Repeater.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "Repeater.h"
#include "Interfaces.h"

namespace DirectUI
{

Repeater::Repeater(Repeater&&a0)
{ }

Repeater::Repeater(Repeater const&a0)
{ }

Repeater::Repeater(void)
{ }

Repeater::~Repeater(void)
{}

Repeater& Repeater::operator=(Repeater&&a0)
{ return *this; }

Repeater& Repeater::operator=(Repeater const&a0)
{ return *this; }

long Repeater::BuildElement(void)
{ return 0; }

long Repeater::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

IClassInfo* Repeater::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* Repeater::GetClassInfoW(void)
{ return nullptr; }

long Repeater::Initialize(Element*a0, unsigned long*a1)
{ return 0; }

long Repeater::Register(void)
{ return 0; }

void Repeater::SetClassInfoPtr(IClassInfo*a0)
{}

void Repeater::SetDataEngine(IDataEngine*a0)
{}

void Repeater::SetGraphicType(unsigned char a0)
{}

IClassInfo* Repeater::s_pClassInfo = nullptr;

} // namespace DirectUI
