// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::RichText.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "RichText.h"

namespace DirectUI
{

RichText::RichText(void)
{ }

RichText::~RichText(void)
{}

PropertyInfo const* RichText::AliasedRenderingProp(void)
{ return nullptr; }

PropertyInfo const* RichText::BaselineProp(void)
{ return nullptr; }

PropertyInfo const* RichText::ColorFontPaletteIndexProp(void)
{ return nullptr; }

PropertyInfo const* RichText::ConstrainLayoutProp(void)
{ return nullptr; }

long RichText::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

long RichText::CreateCache(unsigned int a0, IDUIRichTextCache**a1)
{ return 0; }

PropertyInfo const* RichText::DisableAccTextExtendProp(void)
{ return nullptr; }

PropertyInfo const* RichText::FontColorRunsProp(void)
{ return nullptr; }

PropertyInfo const* RichText::FontSizeRunsProp(void)
{ return nullptr; }

PropertyInfo const* RichText::FontWeightRunsProp(void)
{ return nullptr; }

IClassInfo* RichText::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* RichText::GetClassInfoW(void)
{ return nullptr; }

tagSIZE RichText::GetContentSize(int a0, int a1, Surface*a2)
{ return tagSIZE{}; }

IDWriteFactory* RichText::GetFactory(void)
{ return nullptr; }

long RichText::GetForegroundColorRef(unsigned long*a0)
{ return 0; }

unsigned long RichText::GetLineCount(void)
{ return 0; }

unsigned short RichText::GetShortcutChar(void)
{ return 0; }

unsigned long RichText::GetTrimmedLineCount(void)
{ return 0; }

long RichText::Initialize(Element*a0, unsigned long*a1)
{ return 0; }

PropertyInfo const* RichText::LineSpacingProp(void)
{ return nullptr; }

PropertyInfo const* RichText::LocaleProp(void)
{ return nullptr; }

PropertyInfo const* RichText::MapRunsToClustersProp(void)
{ return nullptr; }

void RichText::OnEvent(Event*a0)
{}

void RichText::OnHosted(Element*a0)
{}

void RichText::OnPropertyChanged(PropertyInfo const*a0, int a1, Value*a2, Value*a3)
{}

PropertyInfo const* RichText::OverhangOffsetProp(void)
{ return nullptr; }

void RichText::Paint(HDC__*a0, tagRECT const*a1, tagRECT const*a2, tagRECT*a3, tagRECT*a4)
{}

long RichText::Register(void)
{ return 0; }

long RichText::SetAliasedRendering(bool a0)
{ return 0; }

long RichText::SetBaseline(int a0)
{ return 0; }

void RichText::SetCache(unsigned long a0, IDUIRichTextCache*a1)
{}

long RichText::SetColorFontPaletteIndex(int a0)
{ return 0; }

long RichText::SetConstrainLayout(int a0)
{ return 0; }

void RichText::SetDWriteFontCollection(IDWriteFontCollection*a0)
{}

void RichText::SetDWriteTextLayout(IDWriteTextLayout*a0)
{}

long RichText::SetDisableAccTextExtend(bool a0)
{ return 0; }

long RichText::SetFontColorRuns(unsigned short const*a0)
{ return 0; }

long RichText::SetFontSizeRuns(unsigned short const*a0)
{ return 0; }

long RichText::SetFontWeightRuns(unsigned short const*a0)
{ return 0; }

long RichText::SetLineSpacing(int a0)
{ return 0; }

long RichText::SetLocale(unsigned short const*a0)
{ return 0; }

long RichText::SetMapRunsToClusters(bool a0)
{ return 0; }

void RichText::SetMaxLineCount(unsigned int a0)
{}

long RichText::SetOverhangOffset(int a0)
{ return 0; }

long RichText::SetTypography(unsigned short const*a0)
{ return 0; }

long RichText::SetTypographyRuns(unsigned short const*a0)
{ return 0; }

long RichText::SetVerticalScript(bool a0)
{ return 0; }

void RichText::StopUsingCache(void)
{}

PropertyInfo const* RichText::TypographyProp(void)
{ return nullptr; }

PropertyInfo const* RichText::TypographyRunsProp(void)
{ return nullptr; }

PropertyInfo const* RichText::VerticalScriptProp(void)
{ return nullptr; }

} // namespace DirectUI
