// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::RowLayout.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "RowLayout.h"

namespace DirectUI
{

RowLayout::RowLayout(RowLayout const&a0)
{ }

RowLayout::RowLayout(void)
{ }

RowLayout::~RowLayout(void)
{}

RowLayout& RowLayout::operator=(RowLayout const&a0)
{ return *this; }

long RowLayout::Create(int a0, unsigned int a1, unsigned int a2, Layout**a3)
{ return 0; }

long RowLayout::Create(int a0, int*a1, Value**a2)
{ return 0; }

long RowLayout::Create(unsigned int a0, unsigned int a1, Layout**a2)
{ return 0; }

void RowLayout::DoLayout(Element*a0, int a1, int a2)
{}

Element* RowLayout::GetAdjacent(Element*a0, Element*a1, int a2, NavReference const*a3, unsigned long a4)
{ return nullptr; }

long RowLayout::Initialize(int a0, unsigned int a1, unsigned int a2)
{ return 0; }

tagSIZE RowLayout::UpdateDesiredSize(Element*a0, int a1, int a2, Surface*a3)
{ return tagSIZE{}; }

} // namespace DirectUI
