// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::Selector.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "Selector.h"
#include "Interfaces.h"

namespace DirectUI
{

Selector::Selector(Selector const&a0)
{ }

Selector::Selector(void)
{ }

Selector::~Selector(void)
{}

Selector& Selector::operator=(Selector const&a0)
{ return *this; }

long Selector::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

Element* Selector::GetAdjacent(Element*a0, int a1, NavReference const*a2, unsigned long a3)
{ return nullptr; }

IClassInfo* Selector::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* Selector::GetClassInfoW(void)
{ return nullptr; }

Element* Selector::GetSelection(void)
{ return nullptr; }

long Selector::Initialize(Element*a0, unsigned long*a1)
{ return 0; }

void Selector::OnEvent(Event*a0)
{}

void Selector::OnInput(InputEvent*a0)
{}

void Selector::OnKeyFocusMoved(Element*a0, Element*a1)
{}

void Selector::OnPropertyChanged(PropertyInfo const*a0, int a1, Value*a2, Value*a3)
{}

long Selector::Register(void)
{ return 0; }

UID Selector::SelectionChange(void)
{ return UID(); }

PropertyInfo const* Selector::SelectionProp(void)
{ return nullptr; }

void Selector::SetClassInfoPtr(IClassInfo*a0)
{}

long Selector::SetSelection(Element*a0)
{ return 0; }

IClassInfo* Selector::s_pClassInfo = nullptr;

} // namespace DirectUI
