// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::SelectorNoDefault.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "SelectorNoDefault.h"
#include "Interfaces.h"

namespace DirectUI
{

SelectorNoDefault::SelectorNoDefault(SelectorNoDefault&&a0)
{ }

SelectorNoDefault::SelectorNoDefault(SelectorNoDefault const&a0)
{ }

SelectorNoDefault::SelectorNoDefault(void)
{ }

SelectorNoDefault::~SelectorNoDefault(void)
{}

SelectorNoDefault& SelectorNoDefault::operator=(SelectorNoDefault&&a0)
{ return *this; }

SelectorNoDefault& SelectorNoDefault::operator=(SelectorNoDefault const&a0)
{ return *this; }

long SelectorNoDefault::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

IClassInfo* SelectorNoDefault::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* SelectorNoDefault::GetClassInfoW(void)
{ return nullptr; }

long SelectorNoDefault::Initialize(Element*a0, unsigned long*a1)
{ return 0; }

void SelectorNoDefault::OnEvent(Event*a0)
{}

void SelectorNoDefault::OnKeyFocusMoved(Element*a0, Element*a1)
{}

long SelectorNoDefault::Register(void)
{ return 0; }

void SelectorNoDefault::SetClassInfoPtr(IClassInfo*a0)
{}

long SelectorNoDefault::SetSelection(Element*a0)
{ return 0; }

IClassInfo* SelectorNoDefault::s_pClassInfo = nullptr;

} // namespace DirectUI
