// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::StyleSheet.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "StyleSheet.h"

namespace DirectUI
{

StyleSheet::StyleSheet(StyleSheet&&a0)
{ }

StyleSheet::StyleSheet(StyleSheet const&a0)
{ }

StyleSheet::StyleSheet(void)
{ }

StyleSheet& StyleSheet::operator=(StyleSheet&&a0)
{ return *this; }

StyleSheet& StyleSheet::operator=(StyleSheet const&a0)
{ return *this; }

long StyleSheet::Create(StyleSheet**a0)
{ return 0; }

} // namespace DirectUI
