// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::TableItemProvider.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "TableItemProvider.h"

namespace DirectUI
{

TableItemProvider::TableItemProvider(void)
{ }

TableItemProvider::~TableItemProvider(void)
{}

unsigned long TableItemProvider::AddRef(void)
{ return 0; }

long TableItemProvider::GetColumnHeaderItems(tagSAFEARRAY**a0)
{ return 0; }

auto TableItemProvider::GetProxyCreator(void) -> ProviderProxy* (__cdecl *)(Element*)
{ return nullptr; }

long TableItemProvider::GetRowHeaderItems(tagSAFEARRAY**a0)
{ return 0; }

long TableItemProvider::QueryInterface(_GUID const&a0, void**a1)
{ return 0; }

unsigned long TableItemProvider::Release(void)
{ return 0; }

} // namespace DirectUI
