; Generated by tools/dui-pipeline -- DO NOT EDIT. Pin: 2080E43F5D99

; own-vptr vftable export of DirectUI::TableProvider.
; The real dui70.dll (VC8-era layout) emits ??_7X@@6B@ for this
; MI class in addition to the base-subobject vftables that the C++
; TU emits. Modern MSVC always merges into a primary base, so this
; symbol is defined here as data (PUBLIC qword slot).
_rdata SEGMENT READONLY
PUBLIC ??_7TableProvider@DirectUI@@6B@
??_7TableProvider@DirectUI@@6B@ DQ 0
_rdata ENDS
END
