// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::TaskPage.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "TaskPage.h"

namespace DirectUI
{

TaskPage::TaskPage(TaskPage const&a0)
{ }

TaskPage::TaskPage(void)
{ }

TaskPage::~TaskPage(void)
{}

TaskPage& TaskPage::operator=(TaskPage const&a0)
{ return *this; }

TaskPage::operator struct _PSP *(void)
{ return (_PSP*)nullptr; }

long TaskPage::CreateDUICP(HWNDElement*a0, HWND__*a1, HWND__*a2, Element**a3, DUIXmlParser**a4)
{ return 0; }

long TaskPage::CreateParserCP(DUIXmlParser**a0)
{ return 0; }

long TaskPage::DUICreatePropertySheetPage(HINSTANCE__*a0)
{ return 0; }

void TaskPage::DestroyCP(void)
{}

void TaskPage::FreeComCtl32(void)
{}

Element* TaskPage::GetElement(void)
{ return nullptr; }

unsigned int TaskPage::GetPageRCID(void)
{ return 0; }

unsigned short const* TaskPage::GetPageResID(void)
{ return nullptr; }

HWND__* TaskPage::GetParentHWND(void)
{ return nullptr; }

void TaskPage::InitPropSheetPage(_PROPSHEETPAGEW*a0)
{}

long TaskPage::LoadComCtl32(void)
{ return 0; }

long TaskPage::LoadPage(Element**a0, Element*a1, DUIXmlParser**a2)
{ return 0; }

long TaskPage::LoadPage(HWNDElement*a0, HINSTANCE__*a1, Element**a2, DUIXmlParser**a3)
{ return 0; }

long TaskPage::LoadParser(DUIXmlParser**a0)
{ return 0; }

__int64 TaskPage::OnKillActive(void)
{ return 0; }

void TaskPage::OnListenedEvent(Element*a0, Event*a1)
{}

void TaskPage::OnListenedInput(Element*a0, InputEvent*a1)
{}

void TaskPage::OnListenedPropertyChanged(Element*a0, PropertyInfo const*a1, int a2, Value*a3, Value*a4)
{}

bool TaskPage::OnListenedPropertyChanging(Element*a0, PropertyInfo const*a1, int a2, Value*a3, Value*a4)
{ return 0; }

void TaskPage::OnListenerAttach(Element*a0)
{}

void TaskPage::OnListenerDetach(Element*a0)
{}

bool TaskPage::OnMessage(unsigned int a0, unsigned __int64 a1, __int64 a2, __int64*a3)
{ return 0; }

__int64 TaskPage::OnQueryCancel(void)
{ return 0; }

Element* TaskPage::OnQueryInitialFocus(void)
{ return nullptr; }

__int64 TaskPage::OnReset(void)
{ return 0; }

__int64 TaskPage::OnSetActive(void)
{ return 0; }

__int64 TaskPage::OnWizBack(void)
{ return 0; }

__int64 TaskPage::OnWizFinish(void)
{ return 0; }

__int64 TaskPage::OnWizNext(void)
{ return 0; }

int TaskPage::OnWndMsg(unsigned int a0, unsigned __int64 a1, __int64 a2, __int64*a3)
{ return 0; }

__int64 TaskPage::PropSheet_SendMessage(unsigned int a0, unsigned __int64 a1, __int64 a2)
{ return 0; }

__int64 TaskPage::StaticXHostSubclassProc(HWND__*a0, unsigned int a1, unsigned __int64 a2, __int64 a3)
{ return 0; }

void TaskPage::StaticXmlParserError(unsigned short const*a0, unsigned short const*a1, int a2, void*a3)
{}

} // namespace DirectUI
