// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::TouchCheckBoxGlyph.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "TouchCheckBoxGlyph.h"

namespace DirectUI
{

TouchCheckBoxGlyph::TouchCheckBoxGlyph(void)
{ }

TouchCheckBoxGlyph::~TouchCheckBoxGlyph(void)
{}

long TouchCheckBoxGlyph::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

IClassInfo* TouchCheckBoxGlyph::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* TouchCheckBoxGlyph::GetClassInfoW(void)
{ return nullptr; }

long TouchCheckBoxGlyph::Initialize(Element*a0, unsigned long*a1)
{ return 0; }

long TouchCheckBoxGlyph::Insert(Element**a0, unsigned int a1, unsigned int a2)
{ return 0; }

bool TouchCheckBoxGlyph::OnPropertyChanging(PropertyInfo const*a0, int a1, Value*a2, Value*a3)
{ return 0; }

void TouchCheckBoxGlyph::Paint(HDC__*a0, tagRECT const*a1, tagRECT const*a2, tagRECT*a3, tagRECT*a4)
{}

long TouchCheckBoxGlyph::Register(void)
{ return 0; }

} // namespace DirectUI
