// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::TouchEdit2.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "TouchEdit2.h"

namespace DirectUI
{

TouchEdit2::TouchEdit2(void)
{ }

long TouchEdit2::Add(Element**a0, unsigned int a1)
{ return 0; }

UID TouchEdit2::ClearButtonClicked(void)
{ return UID(); }

UID TouchEdit2::ContextMenuRequested(void)
{ return UID(); }

long TouchEdit2::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

void TouchEdit2::DisableSelectionHandlesOnEmptyContent(void)
{}

long TouchEdit2::FinalizeCurrentIMEComposition(void)
{ return 0; }

long TouchEdit2::GetAccessibleImpl(IAccessible**a0)
{ return 0; }

IClassInfo* TouchEdit2::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* TouchEdit2::GetClassInfoW(void)
{ return nullptr; }

tagRECT const* TouchEdit2::GetInnerBorderThickness(Value**a0)
{ return nullptr; }

__MIDL___MIDL_itf_inputscope_0000_0000_0001 TouchEdit2::GetInputScope(void)
{ return __MIDL___MIDL_itf_inputscope_0000_0000_0001{}; }

TouchEditPasswordRevealMode TouchEdit2::GetPasswordRevealMode(void)
{ return TouchEditPasswordRevealMode{}; }

unsigned short const* TouchEdit2::GetPromptText(Value**a0)
{ return nullptr; }

bool TouchEdit2::GetPromptWithCaret(void)
{ return 0; }

long TouchEdit2::GetSelection(long*a0, long*a1)
{ return 0; }

int TouchEdit2::GetShowClearButtonMinWidth(void)
{ return 0; }

bool TouchEdit2::GetSuppressClearButton(void)
{ return 0; }

long TouchEdit2::GetTextDocument(ITextDocument**a0)
{ return 0; }

long TouchEdit2::GetTextHost(ITextHost**a0)
{ return 0; }

long TouchEdit2::GetTextSelection(ITextSelection**a0)
{ return 0; }

long TouchEdit2::GetTextServices(ITextServices**a0)
{ return 0; }

Element* TouchEdit2::GetUiaFocusDelegate(void)
{ return nullptr; }

bool TouchEdit2::HasSelection(void)
{ return 0; }

long TouchEdit2::Initialize(Element*a0, unsigned long*a1)
{ return 0; }

PropertyInfo const* TouchEdit2::InnerBorderThicknessProp(void)
{ return nullptr; }

void TouchEdit2::OnEvent(Event*a0)
{}

void TouchEdit2::OnHosted(Element*a0)
{}

void TouchEdit2::OnInput(InputEvent*a0)
{}

void TouchEdit2::OnListenedPropertyChanged(Element*a0, PropertyInfo const*a1, int a2, Value*a3, Value*a4)
{}

void TouchEdit2::OnListenerDetach(Element*a0)
{}

void TouchEdit2::OnPropertyChanged(PropertyInfo const*a0, int a1, Value*a2, Value*a3)
{}

bool TouchEdit2::OnPropertyChanging(PropertyInfo const*a0, int a1, Value*a2, Value*a3)
{ return 0; }

void TouchEdit2::Paint(HDC__*a0, tagRECT const*a1, tagRECT const*a2, tagRECT*a3, tagRECT*a4)
{}

PropertyInfo const* TouchEdit2::PasswordRevealModeProp(void)
{ return nullptr; }

long TouchEdit2::PasteText(unsigned short const*a0)
{ return 0; }

PropertyInfo const* TouchEdit2::PromptTextProp(void)
{ return nullptr; }

PropertyInfo const* TouchEdit2::PromptWithCaretProp(void)
{ return nullptr; }

long TouchEdit2::RefreshContent(void)
{ return 0; }

long TouchEdit2::Register(void)
{ return 0; }

long TouchEdit2::SelectAll(void)
{ return 0; }

long TouchEdit2::SelectNone(void)
{ return 0; }

long TouchEdit2::SetCaretPosition(long a0)
{ return 0; }

long TouchEdit2::SetInnerBorderThickness(int a0, int a1, int a2, int a3)
{ return 0; }

long TouchEdit2::SetInputScope(__MIDL___MIDL_itf_inputscope_0000_0000_0001 a0)
{ return 0; }

long TouchEdit2::SetPasswordRevealMode(TouchEditPasswordRevealMode a0)
{ return 0; }

long TouchEdit2::SetPromptText(unsigned short const*a0)
{ return 0; }

long TouchEdit2::SetPromptWithCaret(bool a0)
{ return 0; }

long TouchEdit2::SetSelection(long a0, long a1)
{ return 0; }

long TouchEdit2::SetShowClearButtonMinWidth(int a0)
{ return 0; }

long TouchEdit2::SetSuppressClearButton(bool a0)
{ return 0; }

PropertyInfo const* TouchEdit2::ShowClearButtonMinWidthProp(void)
{ return nullptr; }

PropertyInfo const* TouchEdit2::SuppressClearButtonProp(void)
{ return nullptr; }

} // namespace DirectUI
