// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::TouchScrollViewer.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "TouchScrollViewer.h"

namespace DirectUI
{

bool TouchScrollViewer::CanPerformManualVisualSwap(void)
{ return 0; }

long TouchScrollViewer::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

long TouchScrollViewer::ExecuteManualSwapDeferredZoomToRect(bool a0)
{ return 0; }

bool TouchScrollViewer::GetAllowArrowOut(void)
{ return 0; }

IClassInfo* TouchScrollViewer::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* TouchScrollViewer::GetClassInfoW(void)
{ return nullptr; }

float TouchScrollViewer::GetContentCrossfadeOpacity(void)
{ return 0; }

long TouchScrollViewer::GetHScrollbar(Element**a0)
{ return 0; }

void TouchScrollViewer::GetInertiaEndpointVisibleRect(tagRECT*a0)
{}

float TouchScrollViewer::GetInertiaEndpointZoomLevel(float a0)
{ return 0; }

int TouchScrollViewer::GetInteractionMode(void)
{ return 0; }

bool TouchScrollViewer::GetLinkIndicatorsToContent(void)
{ return 0; }

IDirectManipulationCompositor* TouchScrollViewer::GetManipulationCompositor(void)
{ return nullptr; }

int TouchScrollViewer::GetManipulationHorizontalAlignment(void)
{ return 0; }

IDirectManipulationManager* TouchScrollViewer::GetManipulationManager(void)
{ return nullptr; }

int TouchScrollViewer::GetManipulationVerticalAlignment(void)
{ return 0; }

IDirectManipulationViewport* TouchScrollViewer::GetManipulationViewport(bool a0)
{ return nullptr; }

bool TouchScrollViewer::GetMouseWithinHorizontalScrollRegion(void)
{ return 0; }

void TouchScrollViewer::GetPredictedVisibleRect(tagRECT*a0)
{}

tagRECT const* TouchScrollViewer::GetScrollPadding(Value**a0)
{ return nullptr; }

float TouchScrollViewer::GetSnapIntervalX(void)
{ return 0; }

float TouchScrollViewer::GetSnapIntervalY(void)
{ return 0; }

int TouchScrollViewer::GetSnapMode(void)
{ return 0; }

float TouchScrollViewer::GetSnapOffsetX(void)
{ return 0; }

float TouchScrollViewer::GetSnapOffsetY(void)
{ return 0; }

DynamicArray<double, 0>* TouchScrollViewer::GetSnapPointCollectionX(Value**a0)
{ return nullptr; }

DynamicArray<double, 0>* TouchScrollViewer::GetSnapPointCollectionY(Value**a0)
{ return nullptr; }

void TouchScrollViewer::GetTranslatedTileRects(tagRECT*a0, unsigned int*a1, unsigned int a2)
{}

long TouchScrollViewer::GetVScrollbar(Element**a0)
{ return 0; }

void TouchScrollViewer::GetVisibleRect(tagRECT*a0)
{}

float TouchScrollViewer::GetZoomMaximum(void)
{ return 0; }

float TouchScrollViewer::GetZoomMinimum(void)
{ return 0; }

bool TouchScrollViewer::IsCrossfadeInProgress(void)
{ return 0; }

bool TouchScrollViewer::IsManualVisualSwapInProgress(void)
{ return 0; }

bool TouchScrollViewer::IsTileMember(unsigned int a0, Element*a1)
{ return 0; }

UID TouchScrollViewer::ManipulationCompleted(void)
{ return UID(); }

UID TouchScrollViewer::ManipulationDelta(void)
{ return UID(); }

PropertyInfo const* TouchScrollViewer::ManipulationHorizontalAlignmentProp(void)
{ return nullptr; }

UID TouchScrollViewer::ManipulationStarted(void)
{ return UID(); }

UID TouchScrollViewer::ManipulationStarting(void)
{ return UID(); }

PropertyInfo const* TouchScrollViewer::ManipulationVerticalAlignmentProp(void)
{ return nullptr; }

UID TouchScrollViewer::MapContentVisuals(void)
{ return UID(); }

void TouchScrollViewer::NewChildElementsAdded(void)
{}

long TouchScrollViewer::OverrideZoomThreshold(float a0, float a1, int a2)
{ return 0; }

long TouchScrollViewer::PrepareManualSwapDeferredZoomToRect(tagRECT const*a0, float const*a1, float const*a2, float*a3, float*a4, float a5)
{ return 0; }

UID TouchScrollViewer::ReleaseSnapshot(void)
{ return UID(); }

long TouchScrollViewer::ResetInputState(void)
{ return 0; }

long TouchScrollViewer::ResetManipulations(void)
{ return 0; }

PropertyInfo const* TouchScrollViewer::ScrollPaddingProp(void)
{ return nullptr; }

UID TouchScrollViewer::SemanticChange(void)
{ return UID(); }

long TouchScrollViewer::SetAllowArrowOut(bool a0)
{ return 0; }

long TouchScrollViewer::SetContact(unsigned int a0, bool a1)
{ return 0; }

UID TouchScrollViewer::SetContactNeeded(void)
{ return UID(); }

UID TouchScrollViewer::SetContactNotify(void)
{ return UID(); }

long TouchScrollViewer::SetDelegateEventHandler(IUnknown*a0)
{ return 0; }

void TouchScrollViewer::SetDisableOffscreenCaching(bool a0)
{}

long TouchScrollViewer::SetInteractionMode(int a0)
{ return 0; }

long TouchScrollViewer::SetLinkIndicatorsToContent(bool a0)
{ return 0; }

long TouchScrollViewer::SetManipulationHorizontalAlignment(int a0)
{ return 0; }

long TouchScrollViewer::SetManipulationVerticalAlignment(int a0)
{ return 0; }

long TouchScrollViewer::SetScrollControlHost(Element*a0)
{ return 0; }

long TouchScrollViewer::SetScrollPadding(int a0, int a1, int a2, int a3)
{ return 0; }

long TouchScrollViewer::SetSnapIntervalX(float a0)
{ return 0; }

long TouchScrollViewer::SetSnapIntervalY(float a0)
{ return 0; }

long TouchScrollViewer::SetSnapMode(int a0)
{ return 0; }

long TouchScrollViewer::SetSnapOffsetX(float a0)
{ return 0; }

long TouchScrollViewer::SetSnapOffsetY(float a0)
{ return 0; }

long TouchScrollViewer::SetSnapPointCollectionX(DynamicArray<double, 0>*a0)
{ return 0; }

long TouchScrollViewer::SetSnapPointCollectionX(double const*a0, int a1)
{ return 0; }

long TouchScrollViewer::SetSnapPointCollectionY(DynamicArray<double, 0>*a0)
{ return 0; }

long TouchScrollViewer::SetSnapPointCollectionY(double const*a0, int a1)
{ return 0; }

long TouchScrollViewer::SetSuppressSetContact(bool a0)
{ return 0; }

long TouchScrollViewer::SetVirtualizeElements(bool a0)
{ return 0; }

long TouchScrollViewer::SetZoomMaximum(float a0)
{ return 0; }

long TouchScrollViewer::SetZoomMinimum(float a0)
{ return 0; }

PropertyInfo const* TouchScrollViewer::SnapIntervalXProp(void)
{ return nullptr; }

PropertyInfo const* TouchScrollViewer::SnapIntervalYProp(void)
{ return nullptr; }

PropertyInfo const* TouchScrollViewer::SnapModeProp(void)
{ return nullptr; }

PropertyInfo const* TouchScrollViewer::SnapOffsetXProp(void)
{ return nullptr; }

PropertyInfo const* TouchScrollViewer::SnapOffsetYProp(void)
{ return nullptr; }

PropertyInfo const* TouchScrollViewer::SnapPointCollectionXProp(void)
{ return nullptr; }

PropertyInfo const* TouchScrollViewer::SnapPointCollectionYProp(void)
{ return nullptr; }

UID TouchScrollViewer::SnapshotTransformElement(void)
{ return UID(); }

long TouchScrollViewer::TelemetrySetDescription(unsigned short const*a0)
{ return 0; }

UID TouchScrollViewer::UpdateContentSize(void)
{ return UID(); }

UID TouchScrollViewer::UpdateView(void)
{ return UID(); }

long TouchScrollViewer::ZoomToRect(tagRECT const*a0, bool a1)
{ return 0; }

long TouchScrollViewer::ZoomToRectManualVisualSwap(float a0, float a1, float a2, float a3, int const*a4, float a5, float a6, float a7, bool a8)
{ return 0; }

} // namespace DirectUI
