// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::UnknownElement.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "UnknownElement.h"
#include "Interfaces.h"

namespace DirectUI
{

UnknownElement::UnknownElement(UnknownElement const&a0)
{ }

UnknownElement::UnknownElement(void)
{ }

UnknownElement::~UnknownElement(void)
{}

UnknownElement& UnknownElement::operator=(UnknownElement const&a0)
{ return *this; }

long UnknownElement::Create(unsigned int a0, Element*a1, unsigned long*a2, Element**a3)
{ return 0; }

long UnknownElement::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

IClassInfo* UnknownElement::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* UnknownElement::GetClassInfoW(void)
{ return nullptr; }

long UnknownElement::Initialize(unsigned int a0, Element*a1, unsigned long*a2)
{ return 0; }

long UnknownElement::Register(void)
{ return 0; }

void UnknownElement::SetClassInfoPtr(IClassInfo*a0)
{}

IClassInfo* UnknownElement::s_pClassInfo = nullptr;

} // namespace DirectUI
