// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::Value.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "Value.h"

namespace DirectUI
{

Value& Value::operator=(Value&&a0)
{ return *this; }

Value& Value::operator=(Value const&a0)
{ return *this; }

void Value::AddRef(void)
{}

Value* Value::CreateAtom(unsigned short a0)
{ return nullptr; }

Value* Value::CreateAtom(unsigned short const*a0)
{ return nullptr; }

Value* Value::CreateBool(bool a0)
{ return nullptr; }

Value* Value::CreateColor(unsigned long a0)
{ return nullptr; }

Value* Value::CreateColor(unsigned long a0, unsigned long a1, unsigned char a2)
{ return nullptr; }

Value* Value::CreateColor(unsigned long a0, unsigned long a1, unsigned long a2, unsigned char a3)
{ return nullptr; }

Value* Value::CreateCursor(HICON__*a0)
{ return nullptr; }

Value* Value::CreateCursor(unsigned short const*a0)
{ return nullptr; }

Value* Value::CreateDFCFill(unsigned int a0, unsigned int a1)
{ return nullptr; }

Value* Value::CreateDTBFill(unsigned short const*a0, int a1, int a2)
{ return nullptr; }

Value* Value::CreateDoubleList(DynamicArray<double, 0>*a0)
{ return nullptr; }

Value* Value::CreateDoubleList(double const*a0, int a1)
{ return nullptr; }

Value* Value::CreateElementList(DynamicArray<class Element*, 0>*a0)
{ return nullptr; }

Value* Value::CreateElementRef(Element*a0)
{ return nullptr; }

Value* Value::CreateElementScaledValue(Element*a0, Value*a1)
{ return nullptr; }

Value* Value::CreateEncodedString(unsigned short const*a0)
{ return nullptr; }

Value* Value::CreateExpression(Expression*a0)
{ return nullptr; }

Value* Value::CreateFill(Fill const&a0)
{ return nullptr; }

Value* Value::CreateFloat(float a0, DynamicScaleValue a1)
{ return nullptr; }

Value* Value::CreateGraphic(HBITMAP__*a0, unsigned char a1, unsigned int a2, bool a3, bool a4, bool a5)
{ return nullptr; }

Value* Value::CreateGraphic(HENHMETAFILE__*a0, HENHMETAFILE__*a1)
{ return nullptr; }

Value* Value::CreateGraphic(HICON__*a0, bool a1, bool a2, bool a3)
{ return nullptr; }

Value* Value::CreateGraphic(ISharedBitmap*a0, unsigned char a1, unsigned int a2)
{ return nullptr; }

Value* Value::CreateGraphic(unsigned short const*a0, unsigned char a1, unsigned int a2, unsigned short a3, unsigned short a4, HINSTANCE__*a5, bool a6, bool a7)
{ return nullptr; }

Value* Value::CreateGraphic(unsigned short const*a0, unsigned short a1, unsigned short a2, HINSTANCE__*a3, bool a4, bool a5)
{ return nullptr; }

Value* Value::CreateGraphic(unsigned short const*a0, ScaledSIZE a1, HINSTANCE__*a2, bool a3, bool a4)
{ return nullptr; }

Value* Value::CreateIconGraphicHelper(HICON__*a0, bool a1, bool a2, bool a3)
{ return nullptr; }

Value* Value::CreateInt(int a0, DynamicScaleValue a1)
{ return nullptr; }

Value* Value::CreateLayout(Layout*a0)
{ return nullptr; }

Value* Value::CreatePoint(int a0, int a1, DynamicScaleValue a2)
{ return nullptr; }

Value* Value::CreateRect(int a0, int a1, int a2, int a3, DynamicScaleValue a4)
{ return nullptr; }

Value* Value::CreateScaledValue(float a0, Value*a1)
{ return nullptr; }

Value* Value::CreateSize(int a0, int a1, DynamicScaleValue a2)
{ return nullptr; }

Value* Value::CreateString(unsigned short const*a0, HINSTANCE__*a1)
{ return nullptr; }

Value* Value::CreateStringRP(unsigned short const*a0, HINSTANCE__*a1)
{ return nullptr; }

Value* Value::CreateStyleSheet(StyleSheet*a0)
{ return nullptr; }

Value* Value::CreateValueList(Value*a0)
{ return nullptr; }

Value* Value::CreateValueList(DynamicArray<class Value*, 0>*a0)
{ return nullptr; }

unsigned short Value::GetAtom(void)
{ return 0; }

Value* Value::GetAtomZero(void)
{ return nullptr; }

bool Value::GetBool(void)
{ return 0; }

Value* Value::GetBoolFalse(void)
{ return nullptr; }

Value* Value::GetBoolTrue(void)
{ return nullptr; }

Value* Value::GetColorTrans(void)
{ return nullptr; }

Cursor* Value::GetCursor(void)
{ return nullptr; }

Value* Value::GetCursorNull(void)
{ return nullptr; }

Value* Value::GetDblListEmpty(void)
{ return nullptr; }

DynamicArray<double, 0>* Value::GetDoubleList(void)
{ return nullptr; }

Value* Value::GetElListNull(void)
{ return nullptr; }

Element* Value::GetElement(void)
{ return nullptr; }

DynamicArray<class Element*, 0>* Value::GetElementList(void)
{ return nullptr; }

Value* Value::GetElementNull(void)
{ return nullptr; }

float Value::GetElementScaledFloat(Element*a0)
{ return 0; }

int Value::GetElementScaledInt(Element*a0)
{ return 0; }

void Value::GetElementScaledPoint(Element*a0, tagPOINT*a1)
{}

void Value::GetElementScaledRect(Element*a0, tagRECT*a1)
{}

void Value::GetElementScaledSize(Element*a0, tagSIZE*a1)
{}

long Value::GetEncodedString(unsigned short*a0, unsigned __int64 a1)
{ return 0; }

unsigned __int64 Value::GetEncodedStringLength(void)
{ return 0; }

Value* Value::GetExprNull(void)
{ return nullptr; }

Expression* Value::GetExpression(void)
{ return nullptr; }

Fill const* Value::GetFill(void)
{ return nullptr; }

float Value::GetFloat(void)
{ return 0; }

Value* Value::GetFloatOne(void)
{ return nullptr; }

Value* Value::GetFloatZero(void)
{ return nullptr; }

Graphic* Value::GetGraphic(void)
{ return nullptr; }

void* Value::GetImage(bool a0, float a1)
{ return nullptr; }

int Value::GetInt(void)
{ return 0; }

Value* Value::GetIntMinusOne(void)
{ return nullptr; }

Value* Value::GetIntZero(void)
{ return nullptr; }

Layout* Value::GetLayout(void)
{ return nullptr; }

Value* Value::GetLayoutNull(void)
{ return nullptr; }

Value* Value::GetNull(void)
{ return nullptr; }

tagPOINT const* Value::GetPoint(void)
{ return nullptr; }

Value* Value::GetPointZero(void)
{ return nullptr; }

tagRECT const* Value::GetRect(void)
{ return nullptr; }

Value* Value::GetRectZero(void)
{ return nullptr; }

int Value::GetRefCount(void) const
{ return 0; }

float Value::GetScaledFloat(float a0)
{ return 0; }

int Value::GetScaledInt(float a0)
{ return 0; }

ScaledInt const* Value::GetScaledInt(void)
{ return nullptr; }

void Value::GetScaledPoint(float a0, tagPOINT*a1)
{}

void Value::GetScaledRect(float a0, tagRECT*a1)
{}

void Value::GetScaledSize(float a0, tagSIZE*a1)
{}

Value* Value::GetSheetNull(void)
{ return nullptr; }

tagSIZE const* Value::GetSize(void)
{ return nullptr; }

Value* Value::GetSizeZero(void)
{ return nullptr; }

unsigned short const* Value::GetString(void)
{ return nullptr; }

unsigned short const* Value::GetStringDynamicScaling(void)
{ return nullptr; }

Value* Value::GetStringNull(void)
{ return nullptr; }

Value* Value::GetStringRPNull(void)
{ return nullptr; }

StyleSheet* Value::GetStyleSheet(void)
{ return nullptr; }

int Value::GetType(void) const
{ return 0; }

Value* Value::GetUnavailable(void)
{ return nullptr; }

Value* Value::GetUnset(void)
{ return nullptr; }

DynamicArray<class Value*, 0>* Value::GetValueList(void)
{ return nullptr; }

bool Value::IsDynamicScaled(void)
{ return 0; }

bool Value::IsEqual(Value*a0)
{ return 0; }

void Value::Release(void)
{}

HICON__* Value::ReloadIcon(Graphic*a0, float a1)
{ return nullptr; }

void Value::SetLayoutPointerToNull(void)
{}

long Value::StrDupW(unsigned short const*a0, unsigned short**a1)
{ return 0; }

unsigned short* Value::ToString(unsigned short*a0, unsigned int a1) const
{ return nullptr; }

void Value::_ZeroRelease(void)
{}

int const Value::c_RefCountBitOffset = 0;

long const Value::c_RefCountMask = 0;

long const Value::c_SingleRefCount = 0;

} // namespace DirectUI
