// Generated by tools/dui-pipeline — DO NOT EDIT. Pin: 2080E43F5D99

// Stub implementations for DirectUI::XBaby.
// Every definition exists solely to materialize the exact
// decorated names of the real dui70.dll exports.

#include "XBaby.h"
#include "Interfaces.h"

namespace DirectUI
{

XBaby::XBaby(XBaby const&a0)
{ }

XBaby::XBaby(void)
{ }

XBaby::~XBaby(void)
{}

XBaby& XBaby::operator=(XBaby const&a0)
{ return *this; }

void XBaby::CacheParser(DUIXmlParser*a0)
{}

bool XBaby::CanSetFocus(void)
{ return 0; }

bool XBaby::ClickDefaultButton(void)
{ return 0; }

long XBaby::Create(Element*a0, unsigned long*a1, Element**a2)
{ return 0; }

long XBaby::Create(IXElementCP*a0, XProvider*a1, HWND__*a2, Element*a3, unsigned long*a4, Element**a5)
{ return 0; }

long XBaby::CreateStyleParser(DUIXmlParser**a0)
{ return 0; }

void XBaby::ForceThemeChange(unsigned __int64 a0, __int64 a1)
{}

Element* XBaby::GetAdjacent(Element*a0, int a1, NavReference const*a2, unsigned long a3)
{ return nullptr; }

IClassInfo* XBaby::GetClassInfoPtr(void)
{ return nullptr; }

IClassInfo* XBaby::GetClassInfoW(void)
{ return nullptr; }

tagSIZE XBaby::GetContentDesiredSize(int a0, int a1)
{ return tagSIZE{}; }

bool XBaby::GetDefaultButtonTracking(void)
{ return 0; }

long XBaby::GetElementProviderImpl(InvokeHelper*a0, ElementProvider**a1)
{ return 0; }

Element* XBaby::GetFocusableElement(void)
{ return nullptr; }

long XBaby::GetHostedElementID(unsigned short*a0)
{ return 0; }

HWNDElement* XBaby::GetXBabyElement(void)
{ return nullptr; }

long XBaby::Initialize(IXElementCP*a0, XProvider*a1, HWND__*a2, Element*a3, unsigned long*a4)
{ return 0; }

bool XBaby::OnChildLostFocus(Element*a0)
{ return 0; }

bool XBaby::OnChildReceivedFocus(Element*a0)
{ return 0; }

void XBaby::OnEvent(Event*a0)
{}

void XBaby::OnNoChildWithShortcutFound(KeyboardEvent*a0)
{}

void XBaby::OnThemeChanged(ThemeChangedEvent*a0)
{}

void XBaby::OnWmThemeChanged(unsigned __int64 a0, __int64 a1)
{}

long XBaby::Register(void)
{ return 0; }

long XBaby::SetButtonClassAcceptsEnterKey(bool a0)
{ return 0; }

void XBaby::SetClassInfoPtr(IClassInfo*a0)
{}

long XBaby::SetDefaultButtonTracking(bool a0)
{ return 0; }

long XBaby::SetHandleEnterKey(bool a0)
{ return 0; }

void XBaby::SetKeyFocus(void)
{}

long XBaby::SetRegisteredDefaultButton(Element*a0)
{ return 0; }

long XBaby::SetToHost(Element*a0)
{ return 0; }

IClassInfo* XBaby::s_pClassInfo = nullptr;

} // namespace DirectUI
