#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
emit_headers.py -- header emitter of the dui-pipeline.

Generates C++ header files for the target DirectUI classes from
pinned/symbols.json + pinned/classes.json. Output is deterministic:
the same pinned inputs always produce byte-identical files (CI golden).

Contract: tools/dui-pipeline/INTERFACE.md.

Usage:
    python emit_headers.py [--pinned <dir>] [--out <dir>] [--classes a,b,c]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DEFAULT_PINNED = REPO / "pinned"
DEFAULT_OUT = REPO / "DirectUI" / "include"

CALLABLE_KINDS = {"method", "static_method", "ctor", "dtor", "operator"}

# ---------------------------------------------------------------------------
# Type universe
# ---------------------------------------------------------------------------
# Types inside namespace DirectUI. kind -> declaration strategy.
DIRECTUI_CLASS_TYPES = {
    "DeferCycle": "fwd",
    "ElementProvider": "fwd",
    "Expression": "fwd",
    "InvokeHelper": "fwd",
    "Layout": "fwd",
    "StyleSheet": "fwd",
    "Surface": "fwd",
    "TouchHWNDElement": "fwd",
}
DIRECTUI_STRUCT_TYPES = {
    "Cursor": "fwd",
    "DepRecs": "fwd",
    "EnumMap": "fwd",
    "Event": "fwd",
    "Fill": "fwd",
    "Graphic": "fwd",
    "IClassInfo": "fwd",
    "IElementListener": "fwd",
    "InputEvent": "fwd",
    "KeyboardEvent": "fwd",
    "LINEINFO": "define",  # by-value in several DUIXmlParser signatures
    "MouseEvent": "fwd",
    "NavReference": "fwd",
    "PointerEvent": "fwd",
    "PropertyInfo": "fwd",
    "ScaledInt": "fwd",
    "ScaledRECT": "define",  # by-value? no - pointer only, but keep symmetrical
    "ScaledSIZE": "define",  # by-value in Value::CreateGraphic
    "ThemeChangedEvent": "fwd",
    "UpdateCache": "fwd",
}
# extra types referenced by the target class set. kind must match the real
# DLL's mangling (PEAU=struct vs PEAV=class): IXElementCP/IXProviderCP are
# real-exported connection-point CLASSES (PEAV); the rest are structs.
EXTRA_FWD_TYPES = {
    "IXBaby": "struct",
    "IXElementCP": "class",
    "IXProviderCP": "class",
    "IXProvider": "struct",       # abstract consumer iface (Interfaces.h)
    "CellInfo": "struct",          # TableLayout::GetCellInfo
    "ElementRuntimeId": "struct",  # EventManager::RaiseChildRemovedEvent
    "RectangleChange": "struct",   # EventManager::RaiseGeometryEventWorker
}

# Nested types of generated classes referenced cross-class in signatures:
# 'DirectUI::Schema::Pattern' (enum) or 'DirectUI::AccessibleButton::
# ACCESSIBLEROLE' (enum) etc. The HOST class declares them; referencing
# classes see them qualified. kind: 'enum' | 'struct'
NESTED_TYPE_HOSTS = {
    "Schema": {"Pattern": "enum", "Event": "enum", "RoleMap": "struct",
               "ControlInfo": "struct", "EventInfo": "struct", "EventMap": "struct",
               "PatternInfo": "struct", "PatternMap": "struct", "PropertyInfo": "struct"},
    "Surface": {"EType": "enum"},
    "InvokeHelper": {"InvokeArgs": "struct"},
    "TouchButton": {"ClickDevice": "enum"},
}


def make_banner(pin_hash12: str) -> str:
    return (
        f"// Generated by tools/dui-pipeline — DO NOT EDIT. "
        f"Pin: {pin_hash12}\n"
    )


# ---------------------------------------------------------------------------
# minimal MSVC mangled-type decoder (for static data members whose PDB
# return_type field carries only the RETURN type of a function pointer --
# the full pointer shape lives in the decorated name: 0P6A<ret><args>ZEA)
# ---------------------------------------------------------------------------

_BASIC_TYPE_LETTERS = {
    "H": "int", "I": "unsigned int", "J": "long", "K": "unsigned long",
    "G": "unsigned short", "E": "unsigned char", "F": "unsigned short",
    "M": "float", "N": "double", "X": "void", "_N": "bool", "D": "char",
    "C": "signed char", "_K": "unsigned __int64", "_J": "__int64",
    "_W": "wchar_t", "_S": "char16_t", "_U": "char32_t",
}


class MangledTypeParser:
    """Parses the type portion of an MSVC decorated name (a strict subset:
    basic types, pointers, struct/class/union/enum names with namespace
    nesting and numeric back-references)."""

    def __init__(self, text: str):
        self.s = text
        self.i = 0
        self.fragments: list[str] = []   # back-reference table

    def peek(self, n: int = 1) -> str:
        return self.s[self.i:self.i + n]

    def take(self, n: int = 1) -> str:
        out = self.s[self.i:self.i + n]
        self.i += n
        return out

    def _remember(self, frag: str) -> str:
        self.fragments.append(frag)
        return frag

    def parse_type(self) -> str:
        c = self.peek()
        if c in ("P", "R", "Q"):
            return self._parse_pointer()
        if c == "A":
            self.take()
            inner = self.parse_type()
            return self._remember(inner + "&")
        if c == "_":
            two = self.peek(2)
            if two in _BASIC_TYPE_LETTERS:
                self.take(2)
                return self._remember(_BASIC_TYPE_LETTERS[two])
            return "void*"
        if c in _BASIC_TYPE_LETTERS:
            self.take()
            return self._remember(_BASIC_TYPE_LETTERS[c])
        if c in ("U", "V"):
            self.take()
            name = self._parse_name()
            self._remember(name)   # register the bare name for back-refs
            kw = "struct" if c == "U" else "class"
            return f"{kw} {name}"
        if c == "T":
            self.take()
            name = self._parse_name()
            return self._remember(f"union {name}")
        if c == "W":
            self.take()
            self.take()  # '4'
            name = self._parse_name()
            return self._remember(f"enum {name}")
        if c == "Y":
            self.take()
            digits = ""
            while self.peek().isdigit():
                digits += self.take()
            rank = int(digits) if digits else 0
            for _ in range(rank):
                while self.peek().isdigit():
                    self.take()
            inner = self.parse_type()
            return self._remember(inner)
        if c == "$$":
            self.take(2)
            nxt = self.take()
            if nxt == "C":
                quals = ""
                while self.peek() == "B":
                    self.take()
                    quals += " const"
                inner = self.parse_type()
                return self._remember(inner + quals)
            if nxt == "T":
                return self._remember("void")
            return "void*"
        if c.isdigit():
            n = int(self.take())
            if n < len(self.fragments):
                return self.fragments[n]
            return "void*"
        return "void*"

    def _parse_pointer(self) -> str:
        is_ref = self.peek() == "R"
        self.take()  # P/R/Q
        # pointer qualifiers: E=__ptr64, F=__restrict, G=unaligned(?)
        is_64 = False
        while self.peek() in ("E", "F", "G"):
            if self.peek() == "E":
                is_64 = True
            self.take()
        # pointee cv-qualifier: A=none, B=const, C=volatile, D=const volatile
        cv = self.take()
        const_target = cv == "B"
        inner = self.parse_type()
        ptr = "&" if is_ref else ("*" if is_64 else "* __ptr32")
        if const_target:
            sep = "" if inner.endswith("*") or inner.endswith("&") else " "
            return self._remember(f"{inner}{sep}const{ptr}")
        return self._remember(inner + ptr)

    def _parse_name(self) -> str:
        """Name components until @@ (each component separated by @).
        A bare digit (single or several, one component each) is a numeric
        back-reference into the fragment table built from the whole
        decorated name."""
        parts = []
        while True:
            if self.peek() == "":
                break
            if self.peek() == "@":
                self.take()
                if self.peek() == "@":
                    self.take()
                    break
                continue
            if self.peek().isdigit():
                # back-reference component(s): each digit is one component
                d = self.take()
                if int(d) < len(self.fragments):
                    parts.append(self.fragments[int(d)])
                continue
            comp = ""
            while self.peek() not in ("@", ""):
                comp += self.take()
            if comp:
                parts.append(comp)
            else:
                break
        parts = [p for p in parts if p]
        return "::".join(reversed(parts)) if parts else ""


def fnptr_shape_from_mangled(mang: str):
    """Extract 'ret (__cdecl*)(args)' C++ type text from a static data
    member decorated name whose type is a function pointer (0P6A...ZEA).
    Returns None when the name does not carry a function-pointer type."""
    mm = re.search(r"@@[012]P6A", mang)
    if not mm:
        return None
    body = mang[mm.end():]
    # seed the back-reference table with the symbol's own name components
    # ('?member@Class@DirectUI@@...': numeric name back-refs index this
    # shared fragment list, so '3' after ?x@CallstackTracker@DirectUI@@0P6A
    # PEAUAPI_VERSION@@PEAU3@@ resolves to API_VERSION)
    sm = re.match(r"^(\?\w+@\w+)@DirectUI@@", mang)
    seed = re.findall(r"@(\w+)", sm.group(1)) if sm else []
    p = MangledTypeParser(body)
    p.fragments = [mang[1:].split("@", 1)[0]] + seed + ["DirectUI"]
    ret = p.parse_type()
    args = []
    named_types = []   # struct/class/enum arg types (digits back-ref these)
    if p.peek() == "X":
        p.take()
        if p.peek() == "@":
            p.take()
        if p.peek() != "Z":
            args.append("void")
    while p.peek() and p.peek() not in ("Z", "@"):
        if p.peek().isdigit():
            # argument back-reference: repeats the Nth registered arg type.
            # MSVC registers every arg type EXCEPT basic single-letter
            # types (H/I/J/K/...): pointers and named types get slots.
            n = int(p.take())
            if n < len(named_types):
                args.append(named_types[n])
            else:
                args.append("void*")
        else:
            at = p.parse_type()
            if at == "void" and p.peek() == "Z":
                break
            args.append(at)
            if not re.fullmatch(r"(unsigned )?(char|short|int|long|float|double|bool|void|__int64|unsigned __int64|wchar_t)", at):
                named_types.append(at)
        if p.peek() == "@":
            p.take()
    return f"{ret} (__cdecl*)({', '.join(args) or 'void'})"


def data_type_from_mangled(mang: str):
    """Full C++ type text for a static data member from its decorated name
    (used when the PDB return_type is wrong/incomplete). Handles pointer
    const-ness (PAU vs PEAU) and basic types. Returns None for encodings
    the mini-parser does not understand (templates etc.)."""
    mm = re.match(r"^\?\w+@.+?@DirectUI@@([012])(.+)$", mang)
    if not mm:
        return None
    body = mm.group(2)
    # drop the trailing storage-class encoding: optional E (__ptr64 on the
    # pointer itself) + A(plain)/B(const) -- e.g. '...PEAIEA' -> 'PEAI'
    body = re.sub(r"(?:EA|EB|[AB])$", "", body)
    if "$" in body:
        return None  # template types: mini-parser does not handle them
    # seed back-refs with the symbol's own name components
    # ('?member@Class@DirectUI@@...': '@12@' resolves 1=Class, 2=DirectUI)
    sm = re.match(r"^(\?\w+@\w+)@DirectUI@@", mang)
    seed = re.findall(r"@(\w+)", sm.group(1)) if sm else []
    seed = [mang[1:].split("@", 1)[0]] + seed + ["DirectUI"]
    p = MangledTypeParser(body)
    p.fragments = list(seed)
    ty = p.parse_type()
    if p.i < len(body) and body[p.i:] not in ("", "@"):
        return None  # did not consume the whole type: unknown encoding
    if "void*" in ty and not re.search(r"P[EB]?A?X", body):
        # 'void*' is this parser's bail-out marker; only trust it when the
        # mangled form really is a void pointer
        return None
    return ty


# ---------------------------------------------------------------------------
# undecorated-type-text -> C++ declaration text translation
# ---------------------------------------------------------------------------

FN_PTR_RE = re.compile(
    r"^(?P<ret>.+?)\s*\(__cdecl\s*(?P<class>(?:\w+::)*\w+::)?\*\)\s*\((?P<args>.*)\)$"
)

# Template-id like 'class DirectUI::DynamicArray<class DirectUI::Element *, 0>'
# or 'struct DirectUI::DUIXmlParser::FunctionDefinition<int>'
TEMPLATE_ID_RE = re.compile(
    r"^(?:class|struct|union)\s+DirectUI::(\w+)<(.*)>$"
)


class TypeTranslator:
    """Translates undecorated parameter/return type strings into C++ decl text
    usable inside `namespace DirectUI`. When keep_scope is set (global-scope
    classes), 'DirectUI::' qualifications are PRESERVED."""

    def __init__(self, target_classes, keep_scope: bool = False):
        self.target_classes = set(target_classes)
        self.keep_scope = keep_scope

    # -- helpers ----------------------------------------------------------

    def _strip_scope(self, text: str) -> str:
        """Remove 'DirectUI::' qualifications (we are inside that namespace)."""
        if self.keep_scope:
            return text
        return re.sub(r"\bDirectUI::", "", text)

    @staticmethod
    def _strip_class_kw(text: str) -> str:
        return re.sub(r"^(class|struct|union|enum)\s+", "", text)

    def translate(self, text: str) -> str:
        """Translate one type string to C++ declaration syntax."""
        text = text.strip()
        # anonymous struct/class/union in an undecorated 'struct*' shape:
        # the PDB sometimes loses the tag name (HINSTANCE-style handles).
        # A bare 'struct'/'class'/'union' token renders as void*.
        if re.fullmatch(r"(const\s+)?(struct|class|union)", text):
            return "void*"
        # function pointer: 'ret (__cdecl *)(args)' or member pointer
        # 'ret (__cdecl Class::*)(args)'
        m = FN_PTR_RE.match(text)
        if m:
            ret = self.translate(m.group("ret"))
            cls_qual = m.group("class") or ""
            args = m.group("args").strip()
            if args in ("", "void"):
                arg_list = "void"
            else:
                arg_list = ", ".join(
                    self.translate(a.strip()) for a in self._split_args(args)
                )
            return f"{ret} (__cdecl {cls_qual}*)({arg_list})"
        # template-id: 'class DirectUI::DynamicArray<X, 0>'
        m = TEMPLATE_ID_RE.match(text)
        if m:
            name, raw_args = m.groups()
            args = []
            for a in self._split_args(raw_args):
                a = a.strip()
                if re.fullmatch(r"-?\d+", a):
                    args.append(a)  # non-type parameter
                else:
                    args.append(self.translate(a))
            return f"{name}<{', '.join(args)}>"
        # 'unsigned short const *' etc: normalize to 'unsigned short const*'
        t = self._strip_scope(text)
        t = self._strip_class_kw(t)
        t = re.sub(r"\s*\*", "*", t)
        t = re.sub(r"\s*&", "&", t)
        # normalize 'const X'/'X const' trailing style: keep as-is except
        # pointer-to-const: 'X const*' stays; MSVC accepts both orders.
        return t

    def translate_def(self, text: str, name: str) -> str:
        """Translate one type string for a definition context, binding the
        parameter name. Function pointers get the name inside the (*name)
        declarator. '...' (varargs) never takes a parameter name."""
        text = text.strip()
        if text == "...":
            return "..."
        m = FN_PTR_RE.match(text)
        if m:
            ret = self.translate(m.group("ret"))
            cls_qual = m.group("class") or ""
            args = m.group("args").strip()
            if args in ("", "void"):
                arg_list = "void"
            else:
                arg_list = ", ".join(
                    self.translate(a.strip()) for a in self._split_args(args)
                )
            return f"{ret} (__cdecl {cls_qual}* {name})({arg_list})"
        plain = self.translate(text)
        if plain.endswith("*") or plain.endswith("&"):
            return f"{plain}{name}"
        return f"{plain} {name}"

    @staticmethod
    def _split_args(text: str) -> list:
        """Split a comma-separated argument list, respecting parentheses."""
        parts, depth, cur = [], 0, []
        for ch in text:
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
            if ch == "," and depth == 0:
                parts.append("".join(cur))
                cur = []
            else:
                cur.append(ch)
        if cur:
            parts.append("".join(cur))
        return [p for p in (s.strip() for s in parts) if p]


# ---------------------------------------------------------------------------
# Class-name utilities
# ---------------------------------------------------------------------------

TPL_CLASS_RE = re.compile(r"^(\w+)<(.*)>$")


def is_template_class(cls: str) -> bool:
    """True for explicit-specialization class names like
    'PatternProvider<class DirectUI::InvokeProvider, struct IInvokeProvider, 0>'."""
    return bool(TPL_CLASS_RE.match(cls))


def template_id(cls: str) -> str:
    """C++ template-id text for a specialization class name, e.g.
    'PatternProvider<class DirectUI::InvokeProvider, ...>' ->
    'PatternProvider<InvokeProvider, IInvokeProvider, 0>'."""
    m = TPL_CLASS_RE.match(cls)
    if not m:
        return cls
    name, raw_args = m.group(1), m.group(2)
    args = []
    for a in split_template_args(raw_args):
        a = a.strip()
        if re.fullmatch(r"-?\d+", a):
            args.append(a)  # non-type parameter
        else:
            # 'class DirectUI::Foo *' -> 'Foo*' (we are inside namespace DirectUI)
            t = re.sub(r"^(class|struct|union)\s+DirectUI::", "", a)
            t = re.sub(r"^(class|struct|union)\s+", "", t)
            t = re.sub(r"\s*DirectUI::", "", t)
            t = re.sub(r"\s*\*", "*", t)
            args.append(t)
    return f"{name}<{', '.join(args)}>"


def split_template_args(text: str) -> list:
    """Split template argument list on commas at depth 0 (respecting <>)."""
    parts, depth, cur = [], 0, []
    for ch in text:
        if ch == "<":
            depth += 1
        elif ch == ">":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append("".join(cur))
            cur = []
        else:
            cur.append(ch)
    if cur:
        parts.append("".join(cur))
    return [p.strip() for p in parts if p.strip()]


def safe_name(cls: str) -> str:
    """Filesystem-safe header/stub name for a class. Template
    specializations map to 'Name_arg1_arg2' style identifiers."""
    if not is_template_class(cls):
        return cls
    m = TPL_CLASS_RE.match(cls)
    name, raw_args = m.group(1), m.group(2)
    parts = [name]
    for a in split_template_args(raw_args):
        a = re.sub(r"^(class|struct|union)\s+DirectUI::", "", a.strip())
        a = re.sub(r"^(class|struct|union)\s+", "", a)
        a = re.sub(r"DirectUI::", "", a)
        a = re.sub(r"[^A-Za-z0-9_]", "_", a)
        a = re.sub(r"_+", "_", a).strip("_")
        parts.append(a)
    return "_".join(parts)


# ---------------------------------------------------------------------------
# Symbol model helpers
# ---------------------------------------------------------------------------

# Access recovery from the mangled name: the access letter is ENCODED IN
# the decorated name per the MSVC access-code scheme (it would otherwise
# change: public=Q/E/U, protected=I/K/M, private=A/C/E). The matrix
# (letter x is_virtual x is_static -> access) is the standard encoding:
#   plain:  A=private  I=protected  Q=public
#   static: C=private  K=protected  S=public
#   virt:   E=private  M=protected  U=public
# ('W'/'Y' letters are MI thunks, never present on target classes.)
# The access letter sits between '@DirectUI@@' and the calling convention.
# Non-static member: <access> E [B if const] A <return type>, e.g. QEAA /
# AEBA (private const). Static: <access> A <return type>, e.g. KAX
# (protected static void). Template-class scopes embed '@DirectUI@@' inside
# their arguments, so the calling-convention anchor is required to find
# the OUTER scope's access letter.
MANGLED_ACCESS_RE = re.compile(r"@DirectUI@@([ACEIKMSQU])E?[AB]?A")
ACCESS_FROM_MANGLED = {
    "A": "private", "C": "private", "E": "private",
    "I": "protected", "K": "protected", "M": "protected",
    "Q": "public", "S": "public", "U": "public",
}

# Static data members: ?name@Class@DirectUI@@<0|1|2><type><A|B>
# 0=private 1=protected 2=public; trailing B=const.
MANGLED_DATA_RE = re.compile(r"^\?\w+@\w+@DirectUI@@([012])(.*)$")
DATA_ACCESS_FROM_MANGLED = {"0": "private", "1": "protected", "2": "public"}


def access_of(sym: dict) -> str:
    """Recover the C++ access specifier from the mangled name.

    For members, the letter after the class's @DirectUI@@ scope encodes
    access+virtual/static. For static data, the digit after the scope
    encodes access (0=private 1=protected 2=public)."""
    if sym.get("kind") == "data":
        m = MANGLED_DATA_RE.match(sym["mangled"])
        if m:
            return DATA_ACCESS_FROM_MANGLED.get(m.group(1), "public")
        return "public"
    m = MANGLED_ACCESS_RE.search(sym["mangled"])
    if not m:
        # global-scope classes: ?member@Class@@<letters> (no DirectUI
        # scope component; params may still reference DirectUI types)
        g = re.match(r"^\?\w+@\w+@@([ACEIKMSQU])E?[AB]?A", sym["mangled"])
        if g:
            return ACCESS_FROM_MANGLED.get(g.group(1), "public")
        return "public"
    return ACCESS_FROM_MANGLED.get(m.group(1), "public")


def load_symbols(path: Path) -> list:
    data = json.loads(path.read_text(encoding="utf-8"))
    return data["symbols"]


def load_classes(path: Path) -> tuple[list, dict]:
    """Returns (classes, inheritance) from pinned/classes.json."""
    data = json.loads(path.read_text(encoding="utf-8"))
    return list(data["classes"]), dict(data.get("inheritance") or {})


def classify_dtor(sym: dict) -> bool:
    """True for the real destructor (??1Class...). The 'vector deleting
    dtor' (??_E...) is a compiler-generated entry, not an export."""
    return sym["mangled"].startswith("??1")


def classify_scalar_dtor(sym: dict) -> bool:
    """'vector deleting dtor' ??_E... entries - these are NOT exports (they
    come from the PDB publics) and are compiler-generated; we never emit
    them."""
    return sym["mangled"].startswith("??_E")


def in_directui_scope(sym: dict) -> bool:
    """The PDB 'class' attribution is name-only: symbols of nested
    subsystems (e.g. ??1Movie@SWF@@ -- Flash dtor) carry class='Movie'
    but live in a different scope. Real DirectUI members mangle with the
    immediate parent scope @DirectUI@@; this filter rejects the rest."""
    m = sym.get("mangled") or ""
    cls = sym.get("class") or ""
    if not m.startswith("?"):
        return True
    m2 = re.match(r"^\?\??\w+@" + re.escape(cls) + r"@([^@]+)@", m)
    if not m2:
        return True
    return m2.group(1) == "DirectUI"


def is_synth_member(sym: dict) -> bool:
    """Compiler-synthesized members whose PDB 'member' names carry
    backquotes: `vftable', `scalar deleting dtor', `default ctor closure',
    `RTTI...'. None of them is expressible as a C++ member declaration."""
    m = sym.get("member") or ""
    return m.startswith("`") or (sym.get("mangled") or "").startswith("??_7")


def is_callable(sym: dict) -> bool:
    if is_synth_member(sym):
        return False
    if sym.get("kind") not in CALLABLE_KINDS:
        # plain methods that merely USE template parameter types (e.g.
        # ?CreateElementList@Value@...DynamicArray@...) carry kind='template'
        # in the symbol table but are NOT function templates (no ??$ prefix)
        if sym.get("kind") != "template":
            return False
    if classify_scalar_dtor(sym):
        return False
    # 'default ctor closure' (??_F...): compiler-synthesized, not writable
    # in C++ source. The stub TUs materialize these via a companion MASM
    # object (see emit_stub.py) so the export is still reproduced.
    if sym["mangled"].startswith("??_F"):
        return False
    # True function templates (??$...) are skipped -- their instantiations
    # are compile-time and cannot be re-emitted from a declaration.
    if sym["mangled"].startswith("??$"):
        return False
    return True


def is_data(sym: dict) -> bool:
    if sym["mangled"].startswith("??$"):
        return False
    if is_synth_member(sym):
        return False
    return sym.get("kind") == "data"


# ---------------------------------------------------------------------------
# Declaration rendering
# ---------------------------------------------------------------------------


class MemberDecl:
    def __init__(self, sym: dict, cls: str):
        self.sym = sym
        self.cls = cls
        # ctor/dtor names use the specialization-id ('PatternProvider<...>')
        # for template classes, the plain name otherwise
        self.class_name = template_id(cls) if is_template_class(cls) else cls
        self.is_dtor = classify_dtor(sym)
        self.is_ctor = sym["kind"] == "ctor" and not self.is_dtor

    def fnptr_return(self) -> str | None:
        """Return the raw fn-pointer return-type text if the method returns
        a function pointer, else None.

        return_type stores the complete shape, e.g.:
            'class DirectUI::Value * (__cdecl *)(unsigned short const *, void *)'
        We detect that via the '(__cdecl *)' marker (also member pointers
        '(__cdecl Class::*)')."""
        ret = self.sym.get("return_type") or ""
        if FN_PTR_RE.match(ret.strip()):
            return ret.strip()
        return None

    def signature(self, tr: TypeTranslator) -> str:
        s = self.sym
        name = s["member"]
        if self.is_ctor or self.is_dtor:
            if self.is_dtor:
                name = "~" + self.class_name
            else:
                name = self.class_name
            params = s.get("params") or []
            param_text = ", ".join(tr.translate(p) for p in params) or "void"
            sig = f"{name}({param_text})"
        elif re.match(r"^operator\s+(struct\s+|class\s+|union\s+|enum\s+)?\w+(\s*\*)*\s*$", name) and (
                re.sub(r"^(struct|class|union|enum)\s+", "", (s.get("return_type") or "").strip()) in
                (re.sub(r"^(struct|class|union|enum)\s+", "", name[len("operator"):].strip()),)):
            # conversion operator: 'operator int *' / 'operator struct _PSP *'
            # with matching return_type -- no return type in the declaration
            params = s.get("params") or []
            param_text = ", ".join(tr.translate(p) for p in params) or "void"
            conv = tr.translate(s["return_type"])
            sig = f"operator {conv}({param_text})"
        else:
            params = s.get("params") or []
            param_text = ", ".join(tr.translate(p) for p in params) or "void"
            fpr = self.fnptr_return()
            if fpr:
                # function returning a function pointer -- use trailing
                # return type: the shape is emitted verbatim after '->'.
                # The decorated name is unaffected (it encodes the
                # signature, not the syntax).
                sig = f"auto {name}({param_text}) -> {tr.translate(fpr)}"
            else:
                ret = tr.translate(s["return_type"]) if s.get("return_type") else "void"
                sig = f"{ret} {name}({param_text})"
        if s.get("is_const"):
            sig += " const"
        return sig

    def qualifiers(self) -> str:
        s = self.sym
        q = []
        if s.get("is_virtual"):
            q.append("virtual")
        if s.get("is_static"):
            q.append("static")
        return " ".join(q)

    def is_virtual(self) -> bool:
        return bool(self.sym.get("is_virtual"))

    def full_decl(self, tr: TypeTranslator) -> str:
        q = self.qualifiers()
        sig = self.signature(tr)
        if q:
            return f"{q} {sig};"
        return f"{sig};"


def order_key(sym: dict):
    # keep original order from the symbol table (roughly vtable order for
    # virtuals, which helps readability but is not semantically required)
    return 0


# ---------------------------------------------------------------------------
# Header emission
# ---------------------------------------------------------------------------


# Classes whose exported symbols carry NO '@DirectUI@@' scope component
# (the class lives at global scope in the real DLL, e.g.
# ?Create@AcceleratorBehavior@@SAJ... -- DirectUI types appear as fully
# qualified inside the signature instead). Their headers define the class
# OUTSIDE namespace DirectUI.
GLOBAL_SCOPE_CLASSES = {
    "AcceleratorBehavior",
    "CSafeElementProxy",
}

# Base classes that are ABSTRACT in the real DLL (their derived classes
# export ??_7Derived@...@6B<Base>@@ base-subobject vftables, but the base
# itself exports no vftable or virtuals). Their generated headers need at
# least one pure virtual to make the base polymorphic, else the derived
# classes emit no base-subobject vftable at all.
POLYMORPHIC_BASE_CLASSES = {
    "IProvider",
}

# Classes whose self-referencing mangled names use U (struct) rather than V
# (class): ??0ISBLeak@DirectUI@@QEAA@AEBU01@@Z. Their declarations must use
# the 'struct' tag or every member mangles with the wrong tag letter.
# (Derived from the AEA/AEB/$$QEA + U01 self-references in symbols.json.)
STRUCT_TAG_CLASSES = {
    "IDataEngine",
    "IDataEntry",
    "ISBLeak",
    "NavReference",
    "NavScoring",
}


def is_duixml_nested(cls: str) -> bool:
    """FunctionDefinition<T> specializations are NESTED inside
    DUIXmlParser (mangled ?$FunctionDefinition@...@DUIXmlParser@DirectUI@@).
    They get no separate header; DUIXmlParser.h declares the primary
    template and its TU defines + explicitly instantiates operator=."""
    return bool(re.match(r"^FunctionDefinition<", cls))


def is_nested_pseudo_class(cls: str) -> bool:
    """'Classes' that are really NESTED TYPES of a real class:
    ACCESSIBLEROLE is a struct nested in AccessibleButton whose implicitly
    generated operator= is exported (??4ACCESSIBLEROLE@AccessibleButton@...).
    Such TUs are emitted inside the HOST class's TU, not standalone."""
    return cls == "ACCESSIBLEROLE"


def nested_host_of(cls: str) -> str:
    return "AccessibleButton" if cls == "ACCESSIBLEROLE" else ""


def referenced_class_types(cls: str, members: list, data_members: list,
                           classes: list, base) -> list:
    """DirectUI class names referenced by the member signatures of THIS
    header (for targeted forward declarations). Template specializations
    contribute their primary name; the class itself and its base are
    excluded (base is #included, self is being defined)."""
    names = set()
    texts = []
    for s in members + data_members:
        texts.extend(s.get("params") or [])
        if s.get("return_type"):
            texts.append(s["return_type"])
    for t in texts:
        for m in re.finditer(r"DirectUI::(\w+)", t or ""):
            names.add(m.group(1))
    known = set(classes)
    if base:
        known = known - {base}
    return sorted(n for n in names if n in known)


# External (non-DirectUI-class) base interfaces and where they are
# declared. Inheritance entries pointing here make the class header
# include the provider of the complete interface definition.
EXTERNAL_BASE_INCLUDES = {
    "IElementListener": "Interfaces.h",
    "IXProvider": "Interfaces.h",
    "IDialogElement": "dui_abi_types.h",
    "IRawElementProviderAdviseEvents": "UIAutomationCore.h",
    "IRawElementProviderSimple": "UIAutomationCore.h",
    "IRawElementProviderFragment": "UIAutomationCore.h",
    "IRawElementProviderFragmentRoot": "UIAutomationCore.h",
    "IRawElementProviderSimple2": "UIAutomationCore.h",
    "IAccIdentity": "oleacc.h",
    "IAccessible": "oleacc.h",
    "IEnumVARIANT": "oleauto.h",
    "IOleWindow": "oleidl.h",
    "IServiceProvider": "servprov.h",
}


def nested_type_hosts_used(members: list, data_members: list, base) -> list:
    """Host classes whose nested types are referenced in these signatures
    (e.g. 'enum DirectUI::TouchButton::ClickDevice' by value)."""
    hosts = set()
    texts = []
    for s in members + data_members:
        texts.extend(s.get("params") or [])
        if s.get("return_type"):
            texts.append(s["return_type"])
    for t in texts:
        for m in re.finditer(r"(?:enum|struct|class|union)\s+DirectUI::(\w+)::(\w+)", t or ""):
            host, nested = m.group(1), m.group(2)
            if host in NESTED_TYPE_HOSTS and nested in NESTED_TYPE_HOSTS[host]:
                hosts.add(host)
    return sorted(hosts)


def base_list(inheritance: dict, cls: str) -> list:
    """Base classes of cls as a list (inheritance entries may be a single
    name, a list, or absent)."""
    v = inheritance.get(cls)
    if not v:
        return []
    if isinstance(v, str):
        return [v]
    return [b for b in v if b]


def render_class_header(cls: str, members: list, data_members: list,
                        tr: TypeTranslator, classes: list,
                        inheritance: dict, banner: str,
                        has_own_vftable: bool = False) -> str:
    """Render one class header file content."""
    tpl = is_template_class(cls)
    tid = template_id(cls) if tpl else cls
    bases = base_list(inheritance, cls)
    global_cls = cls in GLOBAL_SCOPE_CLASSES
    if global_cls:
        # members reference DirectUI types fully qualified; the class itself
        # lives at global scope (no @DirectUI@@ in its mangled members)
        tr = TypeTranslator(classes, keep_scope=True)
    lines = []
    lines.append(banner)
    lines.append(f"// DirectUI::{tid} -- declarations derived from the real")
    lines.append("// dui70.dll export table + PDB publics.")
    if global_cls:
        lines.append("// NOTE: this class is exported at GLOBAL scope in the real DLL")
        lines.append("//       (no @DirectUI@@ component in its decorated names).")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <windows.h>")
    lines.append('#include "dui_abi_types.h"')
    lines.append("")
    # include the DirectUI base-class headers (must be complete types)
    for b in bases:
        if b in classes:
            lines.append(f'#include "{safe_name(b)}.h"')
            lines.append("")
    for b in bases:
        if b in EXTERNAL_BASE_INCLUDES:
            provider = EXTERNAL_BASE_INCLUDES[b]
            if provider.endswith(".h") and not provider.startswith("<"):
                lines.append(f'#include "{provider}"')
            else:
                lines.append(f"#include <{provider}>")
            lines.append("")
    # explicit specializations: the template ARGUMENT types must be
    # complete-enough to name (DirectUI provider classes get their header;
    # UIA interfaces come from UIAutomationCore.h via dui_abi_types.h)
    if is_template_class(cls):
        for arg in split_template_args(TPL_CLASS_RE.match(cls).group(2)):
            arg = arg.strip()
            m = re.match(r"(?:class|struct)\s+(?:DirectUI::)?(\w+)$", arg)
            if m and m.group(1) in classes:
                lines.append(f'#include "{safe_name(m.group(1))}.h"')
                lines.append("")
    # headers of classes whose NESTED types this signature set uses by
    # value (enum by value needs the complete host class)
    for host in sorted(nested_type_hosts_used(members, data_members, None)):
        if host != cls and host in classes:
            lines.append(f'#include "{safe_name(host)}.h"')
            lines.append("")
    if cls == "XProvider":
        # XProvider : IXProvider (abstract consumer interface)
        lines.append('#include "Interfaces.h"')
        lines.append("")

    # forward declarations for the DirectUI classes this header actually
    # references (computed from the member signatures), not every sibling
    fwd = referenced_class_types(cls, members, data_members, classes, None)
    fwd = [n for n in fwd if n not in NESTED_TYPE_HOSTS]
    fwd_kw = {n: ("struct" if n in STRUCT_TAG_CLASSES else "class") for n in fwd}
    if global_cls:
        # DirectUI fwd decls in their namespace; the class itself is global
        if fwd:
            lines.append("namespace DirectUI")
            lines.append("{")
            for name in fwd:
                lines.append(f"    {fwd_kw[name]} {name};")
            lines.append("} // namespace DirectUI")
            lines.append("")
    else:
        lines.append("namespace DirectUI")
        lines.append("{")
        for name in fwd:
            lines.append(f"    {fwd_kw[name]} {name};")
        if fwd:
            lines.append("")

    # Access is recovered from the mangled name (access_of); sections are
    # emitted in public -> protected -> private order (matches the old
    # output exactly, keeping the golden diff stable).
    sections = {"public": [], "protected": [], "private": []}
    for sym in members:
        acc = access_of(sym)
        sections.setdefault(acc, []).append(sym)

    if tpl:
        # explicit specialization: declare the primary template with the
        # parameter shape it really has (derived from the specialization
        # arguments), then the specialization itself
        primary = TPL_CLASS_RE.match(cls).group(1)
        n_args = len(split_template_args(TPL_CLASS_RE.match(cls).group(2)))
        if primary == "PatternProvider":
            params = "typename PROVIDER, typename INTERFACE, int ID"
        elif primary == "SafeArrayAccessor":
            params = "typename T"
        else:
            params = ", ".join(f"typename T{i}" for i in range(n_args))
        lines.append(f"    template <{params}>")
        lines.append(f"    class {primary};")
        lines.append("")
        lines.append("    template <>")
    tag = "struct" if cls in STRUCT_TAG_CLASSES else "class"
    lines.append(f"    {tag} {tid}")
    if bases:
        lines.append(f"        : public {', public '.join(bases)}")
    lines.append("    {")
    lines.append("    public:")

    # nested types of this class referenced cross-class in signatures
    # (e.g. Schema::Pattern, Surface::EType): declare them inside the host
    if cls in NESTED_TYPE_HOSTS:
        for nname, kind in sorted(NESTED_TYPE_HOSTS[cls].items()):
            if kind == "enum":
                lines.append(f"        enum {nname} {{ {nname}_None = 0 }};")
            elif cls == "Schema":
                # complete definition: the static lookup tables
                # (g_*Table/_roleMapping) are const ARRAYS of these nested
                # structs and array definitions need a complete type
                lines.append(f"        struct {nname} {{ int _abi; }};")
            else:
                lines.append(f"        struct {nname};")
        lines.append("")

    if cls in POLYMORPHIC_BASE_CLASSES:
        # abstract in the real DLL (derived classes export base-subobject
        # vftables): one pure virtual makes this base polymorphic without
        # adding any export of its own
        lines.append("    public:")
        lines.append("        virtual unsigned long AddRef(void) = 0;")
        lines.append("")

    if has_own_vftable and not any(
        re.search(r"@DirectUI@@[EMU]E", s.get("mangled") or "") for s in members
    ):
        # vftable-only polymorphic class (ISBLeak / FontCache / StyleSheet /
        # IXElementCP / IXProviderCP pattern): no virtual method is exported,
        # so the real class's virtuals are inline (emitted only via the
        # vtable slots). One inline virtual provides the ??_7 symbol.
        lines.append("    public:")
        lines.append(f"        virtual long On{cls[:24]}Virt(void) {{ return 0; }}")
        lines.append("")

    if cls == "CallstackTracker":
        # IMGHLPFN_LOAD is really a dbghelp function-pointer typedef; the
        # PDB reports it as a nested struct holding the loader procs.
        # Define it minimally so the static array member is complete.
        lines.append("        struct IMGHLPFN_LOAD { void* _proc; };")
        lines.append("        struct STACK_SYMBOL_INFO { void* _sym; };")
        lines.append("")

    if cls == "AccessibleButton":
        # ACCESSIBLEROLE is a nested struct whose implicitly-generated
        # operator= (copy + move) IS a real export. Declare + define it
        # out-of-line in the stub TU; the empty body keeps the object
        # trivially copyable so the compiler exports the same operators.
        lines.append("        struct ACCESSIBLEROLE")
        lines.append("        {")
        lines.append("            ACCESSIBLEROLE& operator=(ACCESSIBLEROLE const&);")
        lines.append("            ACCESSIBLEROLE& operator=(ACCESSIBLEROLE&&);")
        lines.append("        };")
        lines.append("")

    if cls == "DUIXmlParser":
        # nested union referenced by ParseArgs/ParseFunction (mangles
        # PEATParsedArg@12@ -- must be nested inside DUIXmlParser)
        lines.append("        union ParsedArg")
        lines.append("        {")
        lines.append("            unsigned __int64 _raw;")
        lines.append("        };")
        lines.append("")
        # nested template struct used by the s_fd* static tables (mangles
        # U?$FunctionDefinition@...@12@ -- nested inside DUIXmlParser).
        # The real DLL exports its operator= for 5 instantiations, so we
        # declare them out-of-line (definitions in the stub TU).
        lines.append("        template <typename T>")
        lines.append("        struct FunctionDefinition")
        lines.append("        {")
        lines.append("            int _abi;")
        lines.append("            FunctionDefinition& operator=(FunctionDefinition const&);")
        lines.append("            FunctionDefinition& operator=(FunctionDefinition&&);")
        lines.append("        };")
        lines.append("")

    data_by_access = {"public": [], "protected": [], "private": []}
    for dsym in data_members:
        data_by_access.setdefault(access_of(dsym), []).append(dsym)

    first = True
    for acc in ("public", "protected", "private"):
        syms = sections.get(acc) or []
        data_syms = data_by_access.get(acc) or []
        if not syms and not data_syms:
            continue
        if not first:
            lines.append("")
            lines.append(f"        {acc}:")
        first = False

        for sym in syms:
            md = MemberDecl(sym, cls)
            decl = md.full_decl(tr)
            lines.append(f"        {decl}")
        for dsym in data_syms:
            lines.append(f"        {render_data_decl(dsym, tr, cls)}")

    lines.append("    };")
    lines.append("")
    if not global_cls:
        lines.append("} // namespace DirectUI")
        lines.append("")
    return "\n".join(lines)


def render_data_decl(sym: dict, tr: TypeTranslator, cls: str = "") -> str:
    """static data member in-class declaration, e.g.
    'static IClassInfo* s_pClassInfo;'

    The type comes from return_type, but for pointer members that field
    loses the pointer (e.g. 'struct DirectUI::IClassInfo' for what is
    really IClassInfo* -- mangled 0PEAU...EA). Pointer-ness is recovered
    from the mangled name."""
    ty = tr.translate(sym.get("return_type") or "")
    name = sym["member"]
    mang = sym["mangled"]
    # function-pointer static members: the full pointer shape comes from
    # the decorated name (PDB return_type holds only the RETURN type for
    # these); bind the name into the declarator.
    fn_shape = fnptr_shape_from_mangled(mang)
    if fn_shape:
        ret_t, rest = fn_shape.split(" (__cdecl*)", 1)
        args = rest.rstrip(")").lstrip("(")
        return f"static {ret_t} (__cdecl* {name})({args});"
    # s_fd* tables and the Schema/AccessibleButton lookup tables: the real
    # symbol 0/1QBU...B encodes a const ARRAY of nested structs
    # (llvm-undname prints 'const *const' for it). Declare as array [1].
    # Normalize the '*const' pointer-const noise away first.
    if re.search(r"@@[012]Q[AB]U", mang):
        ty = re.sub(r"\s*const\s*\*\s*const\s*$", "", ty).strip()
        return f"static {ty} const {name}[1];"
    # multi-dimensional const arrays of built-ins, e.g. HWNDHost's
    # g_rgMouseMap: 0QAY02$$CBIA. Encoding: Y<rank-2><bound-1 for each
    # dimension except the first> -- the FIRST bound is not encoded, so
    # [1][decoded...] reproduces the exact decorated name.
    if re.search(r"@@[012]QAY\d+\$\$CB", mang):
        mm = re.search(r"@@[012]QAY(\d+)", mang)
        digits = mm.group(1)
        bounds = [int(d) + 1 for d in digits[1:]] or [1]
        brk = "[" + "][".join(str(b) for b in [1] + bounds) + "]"
        return f"static {ty} {name}{brk};"
    # pointer-to-struct/class/union: the mangled name is authoritative for
    # BOTH the pointee tag and const-ness (PDB return_type can lose the
    # pointer, change PAU->PEAU or say void* where the real type is a
    # struct pointer). 0PAIA-style built-in pointers are handled below.
    md = data_type_from_mangled(mang)
    if md and (md.endswith("*") or md.endswith("* __ptr32")):
        mty = re.sub(r"^(struct|class|union) ", "", md)
        if mty.startswith("DirectUI::"):
            mty = mty[len("DirectUI::"):]
        # nested types (e.g. CallstackTracker::IMGHLPFN_LOAD): the short
        # name is visible at class scope, where the declaration lives
        if mty.startswith(f"{cls}::"):
            mty = mty[len(cls) + 2:]
        ty = mty
    elif re.search(r"@@[012]P[AEHQ]?[QAUVT]", mang) and not ty.endswith("*"):
        # template-id pointers (UiaArray<...>*) and other encodings the
        # mini-parser skips: recover just the pointer-ness from the mangle
        # (PDB return_type lost the star)
        ty = ty + "*"
    # 'int const' / 'long const' -> 'const int' style is equivalent;
    # keep the source order but put const first for style
    m = re.match(r"^(.*?)\s+const$", ty)
    if m and "*" not in ty:
        ty = f"const {m.group(1)}"
    return f"static {ty} {name};"


def render_abi_types_header(banner: str) -> str:
    """The shared prelude: global-scope declarations + DirectUI forward
    declarations + small complete definitions needed for by-value ABI."""
    lines = [banner]
    lines.append("// Shared ABI prelude for the generated DirectUI headers.")
    lines.append("// Contains only what is required to reproduce the exact")
    lines.append("// decorated names of the real dui70.dll exports:")
    lines.append("//  * global-scope forward declarations (mangled without @2@)")
    lines.append("//  * namespace DirectUI forward declarations")
    lines.append("//  * minimal complete definitions for by-value types")
    lines.append("// NOTE: compiled with /Zc:wchar_t- (the DirectUI ABI), so")
    lines.append("//       'const wchar_t*' == 'const unsigned short*' (UCString).")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <windows.h>")
    lines.append("#include <commctrl.h>       // _TREEITEM, tagNMCUSTOMDRAWINFO, _PSP")
    lines.append("#include <commdlg.h>        // _PROPSHEETPAGEW")
    lines.append("#include <UIAutomationCore.h>  // IRawElementProvider*, UiaRect, enums")
    lines.append("#include <UIAutomationCoreApi.h>  // AutomationIdentifierType enum (Uia* fn-ptr args)")
    lines.append("#include <directmanipulation.h> // IDirectManipulation* interfaces")
    lines.append("#include <dwrite.h>         // DWRITE_TEXT_RANGE, IDWriteFactory, ...")
    lines.append("#include <oleacc.h>         // IAccessible, IAccIdentity")
    lines.append("#include <imagehlp.h>       // STACK_SYMBOL_INFO, API_VERSION, IMGHLPFN_LOAD")
    lines.append("#include <inputscope.h>     // inputscope GUIDs (TouchEdit2)")
    lines.append("#include <richedit.h>       // CHARRANGE (needed before tom.h)")
    lines.append("#include <tom.h>            // ITextDocument (richedit tom)")
    lines.append("")
    lines.append("// UCString: the DirectUI string ABI is 'unsigned short const*'.")
    lines.append("// With /Zc:wchar_t- a 'const wchar_t*' parameter mangles")
    lines.append("// identically (PEBG), so consumers may use either spelling.")
    lines.append("typedef unsigned short const* UCString;")
    lines.append("")
    lines.append("// Global-scope declarations (mangle WITHOUT the DirectUI back-reference)")
    lines.append("struct IDuiBehavior;")
    lines.append("struct ISharedBitmap;")
    lines.append("struct EventMsg;")
    lines.append("struct tagGMSG;         // not in windows.h")
    lines.append("struct HGADGET__;       // DECLARE_HANDLE(HGADGET) in the real headers")
    lines.append("typedef struct HGADGET__* HGADGET;")
    lines.append("struct HDCONTEXT__;     // duser opaquely-declared handle type")
    lines.append("typedef struct HDCONTEXT__* HDCONTEXT;")
    lines.append("struct IXmlReader;      // xmllite reader (fwd suffices: ptr-only ABI)")
    lines.append("class ITextServices;    // richedit (PEAV in the real DLL)")
    lines.append("class ITextHost;        // richedit text host (PEAV)")
    lines.append("struct GMA_ACTIONINFO;  // GraphicMatrixAnimation action (PEAU, GLOBAL)")
    lines.append("struct GMA_ACTIONDESC;  // (PEAU, GLOBAL)")
    lines.append("struct IDUIRichTextCache;  // RichText cache (PEAU, GLOBAL)")
    lines.append("struct IDCompSurface;   // DComp surface (PEAU, GLOBAL)")
    lines.append("")
    lines.append("// DirectUI-private enums that mangle at GLOBAL scope (W4Name@@ without")
    lines.append("// the @2@ namespace back-reference).")
    lines.append("enum SemanticZoomToggleState { SemanticZoomToggleState_None = 0 };")
    lines.append("enum TOUCHTOOLTIP_INPUT { TOUCHTOOLTIP_INPUT_None = 0 };")
    lines.append("enum TOUCHTOOLTIP_OPTION_FLAGS { TOUCHTOOLTIP_OPTION_FLAGS_None = 0 };")
    lines.append("")
    lines.append("// UID: returned by value by several static event-id accessors.")
    lines.append("// Decorated name in the real DLL is VUID@@ (GLOBAL scope), so it is")
    lines.append("// declared here at global scope -- NOT inside namespace DirectUI.")
    lines.append("class UID")
    lines.append("{")
    lines.append("public:")
    lines.append("    UID() {}")
    lines.append("    void* value;")
    lines.append("};")
    lines.append("")
    lines.append("// Compare a UID against an event-id ACCESSOR FUNCTION (called on the")
    lines.append("// spot). Lets consumer code write `ev->type == TouchButton::Click`")
    lines.append("// without call parentheses (DirectUI types.h idiom).")
    lines.append("inline bool operator==(UID id, UID (*ev)(void))")
    lines.append("{")
    lines.append("    UID p = ev();")
    lines.append("    return id.value == p.value;")
    lines.append("}")
    lines.append("")
    lines.append("// DynamicScaleValue: GLOBAL-scope enum (W4DynamicScaleValue@@)")
    lines.append("enum DynamicScaleValue { DynamicScaleValue_None = 0 };")
    lines.append("")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// namespace DirectUI")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("namespace DirectUI")
    lines.append("{")
    lines.append("    // ---- complete definitions required for by-value parameters ----")
    lines.append("    struct LINEINFO { unsigned int line; };")
    lines.append("    struct ScaledSIZE { int w; int h; };")
    lines.append("    struct ScaledRECT { int l; int t; int r; int b; };")
    lines.append("")
    lines.append("    // ---- DirectUI-private enums (by-value ABI; enumerator sets are")
    lines.append("    //      not exported -- single-member bodies keep them complete) ----")
    lines.append("    enum _DUI_PARSE_STATE { DUI_PARSE_STATE_None = 0 };")
    lines.append("    enum DynamicScaleParsing { DynamicScaleParsing_None = 0 };")
    lines.append("    enum ActiveState { ActiveState_None = 0 };")
    lines.append("    enum ClickDevice { ClickDevice_None = 0 };")
    lines.append("    enum IHMState { IHMState_None = 0 };")
    lines.append("    enum TouchEditFilteredKeyComboFlags { TouchEditFilteredKeyComboFlags_None = 0 };")
    lines.append("    enum TouchEditKeyboardNavigationCapture { TouchEditKeyboardNavigationCapture_None = 0 };")
    lines.append("    enum TouchEditPasswordRevealMode { TouchEditPasswordRevealMode_None = 0 };")
    lines.append("    enum TouchEditTextMode { TouchEditTextMode_None = 0 };")
    lines.append("    enum TouchHWNDElementFlags { TouchHWNDElementFlags_None = 0 };")
    lines.append("    enum POPUPCHANGEEVENTTYPE { POPUPCHANGEEVENTTYPE_None = 0 };")
    lines.append("    enum POPUPFIREEVENTTYPE { POPUPFIREEVENTTYPE_None = 0 };")
    lines.append("    enum FUNCMODE { FUNCMODE_None = 0 };")
    lines.append("    enum CheckedStateFlags { CheckedStateFlags_None = 0 };")
    lines.append("")
    lines.append("    // ---- DirectUI-private structs (pointer-only ABI: fwd suffices) ----")
    lines.append("")
    lines.append("    // IDialogElement: abstract mixin interface (real header: DialogElement")
    lines.append("    // idiom); needs a definition because DialogElement/XBaby DERIVE from")
    lines.append("    // it. Pure virtual so the derived class emits the base-subobject")
    lines.append("    // vftable symbol (??_7D@...6BIDialogElement@@).")
    lines.append("    struct __declspec(novtable) IDialogElement")
    lines.append("    {")
    lines.append("    public:")
    lines.append("        virtual long OnDialogEvent(void) = 0;")
    lines.append("    };")
    lines.append("")
    lines.append("    // ---- embedded-subsystem namespaces referenced by exported")
    lines.append("    //      signatures (pointer-only: namespace + class fwd) ----")
    lines.append("    namespace DuiBehaviorFilters { enum Flags { Flags_None = 0 }; }")
    lines.append("    namespace SWF { class Bits; class SWF; class Tag;")
    lines.append("                    class Fluster; class ColorTransformBrush;")
    lines.append("                    class CommandTag; class Definition;")
    lines.append("                    class Movie { public: struct DepthRange; };")
    lines.append("                    namespace Shape { struct Action; struct LineSegment; }")
    lines.append("                    namespace Types { enum BrushType { BrushType_None = 0 }; } }")
    lines.append("    namespace Library { class Stream;")
    lines.append("                        template <typename T> class SimpleVector; }")
    lines.append("    namespace Gdiplus { class Brush; struct ColorMatrix; }")
    lines.append("")
    lines.append("    // ---- class forward declarations ----")
    for name in sorted(DIRECTUI_CLASS_TYPES):
        lines.append(f"    class {name};")
    lines.append("")
    lines.append("    // ---- struct forward declarations ----")
    lines.append("    struct XMLParserCond;")
    for name in sorted(DIRECTUI_STRUCT_TYPES):
        if name in ("LINEINFO", "ScaledSIZE", "ScaledRECT"):
            continue
        lines.append(f"    struct {name};")
    for name, kind in sorted(EXTRA_FWD_TYPES.items()):
        lines.append(f"    {kind} {name};")
    lines.append("")
    lines.append("    // ---- ValueType: consumer-side knowledge (enum members are never")
    lines.append("    // exported; members transcribed from DirectUI Value.h). Used by")
    lines.append("    // UITest in switch statements over Value::GetType(). ----")
    lines.append("    enum class ValueType : int")
    lines.append("    {")
    lines.append("        Unavailable = -2,")
    lines.append("        Unset = -1,")
    lines.append("        Null = 0,")
    lines.append("        Int = 1,")
    lines.append("        Bool = 2,")
    lines.append("        Element = 3,")
    lines.append("        Ellist = 4,")
    lines.append("        String = 5,")
    lines.append("        Point = 6,")
    lines.append("        Size = 7,")
    lines.append("        Rect = 8,")
    lines.append("        Color = 9,")
    lines.append("        Layout = 10,")
    lines.append("        Graphic = 11,")
    lines.append("        Sheet = 12,")
    lines.append("        Expr = 13,")
    lines.append("        Atom = 14,")
    lines.append("        Cursor = 15,")
    lines.append("        Float = 18,")
    lines.append("        DblList = 19,")
    lines.append("    };")
    lines.append("")
    lines.append("    // ---- ParserTools nested namespace ----")
    lines.append("    namespace ParserTools")
    lines.append("    {")
    lines.append("        struct ExprNode;")
    lines.append("        class ValueParser;")
    lines.append("    }")
    lines.append("")
    lines.append("    // ---- generic containers referenced by exported methods ----")
    lines.append("    // DynamicArray<T, N> is used as a plain (non-template) parameter")
    lines.append("    // type by several exported methods (CreateElementList etc.)")
    lines.append("    template <typename T, int N>")
    lines.append("    class DynamicArray;")
    lines.append("")
    lines.append("    // UiaArray<T>: exported static data members hold instances")
    lines.append("    // (g_pArrayPprv, g_pArrayInvokeHelper). Pointer-size object;")
    lines.append("    // the mangled data symbol only needs the template-id.")
    lines.append("    template <typename T>")
    lines.append("    class UiaArray { public: void* _storage; };")
    lines.append("")
    lines.append("} // namespace DirectUI")
    lines.append("")
    return "\n".join(lines)


def render_interfaces_header(banner: str) -> str:
    """Consumer-side pure-abstract interfaces. These produce NO export
    symbols in the real DLL (they are consumed via vtable slots only), so
    they are transcribed from the DirectUI interface shapes with slot order
    preserved -- the //N comments are the vtable indices."""
    lines = [banner]
    lines.append("// Consumer-side interfaces: no exported symbols; vtable slot order")
    lines.append("// mirrors the real dui70.dll consumers (DirectUI Interfaces.h).")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <windows.h>")
    lines.append('#include "dui_abi_types.h"')
    lines.append("")
    lines.append("namespace DirectUI")
    lines.append("{")
    lines.append("")
    lines.append("    // ---- forward declarations (interfaces reference these) ----")
    lines.append("    class Value;")
    lines.append("    class Element;")
    lines.append("    class HWNDElement;")
    lines.append("    class DUIXmlParser;")
    lines.append("")
    lines.append("    // PropertyInfo: property metadata record (pointer-only in ABI).")
    lines.append("    // cap->type is a ValueType bitfield (DirectUI Primitives.h).")
    lines.append("    struct PropertyInfo")
    lines.append("    {")
    lines.append("        UCString name;             // property name")
    lines.append("        unsigned __int64 unk1;")
    lines.append("        struct PropCapability")
    lines.append("        {")
    lines.append("            ValueType type : 6;")
    lines.append("            unsigned other : 26;")
    lines.append("            unsigned unk;")
    lines.append("        } *cap;")
    lines.append("        struct { UCString str_value; int int_value; } *enum_value_map;")
    lines.append("        Value* (*get_default_value)();")
    lines.append("        unsigned __int64 *unk2;")
    lines.append("    };")
    lines.append("")
    lines.append("    // ---- DUSER enums + Event/InputEvent (consumer-side; from DirectUI")
    lines.append("    // misc.h -- Event is dereferenced by UITest listeners) ----")
    lines.append("    enum DUSER_MSG_FLAG : unsigned int")
    lines.append("    {")
    lines.append("        GMF_DIRECT = 0x00000000,      // OnMessage")
    lines.append("        GMF_ROUTED = 0x00000001,      // PreviewMessage")
    lines.append("        GMF_BUBBLED = 0x00000002,     // PostMessage")
    lines.append("        GMF_EVENT = 0x00000003,       // Message -> Event")
    lines.append("        GMF_DESTINATION = 0x00000003, // Message reach dest")
    lines.append("    };")
    lines.append("")
    lines.append("    enum DUSER_INPUT_DEVICE : unsigned int")
    lines.append("    {")
    lines.append("        GINPUT_MOUSE = 0,")
    lines.append("        GINPUT_KEYBOARD = 1,")
    lines.append("        GINPUT_JOYSTICK = 2,")
    lines.append("    };")
    lines.append("")
    lines.append("    enum DUSER_INPUT_CODE : unsigned int")
    lines.append("    {")
    lines.append("        GMOUSE_MOVE = 0,")
    lines.append("        GMOUSE_DOWN = 1,")
    lines.append("        GMOUSE_UP = 2,")
    lines.append("        GMOUSE_DRAG = 3,")
    lines.append("        GMOUSE_HOVER = 4,")
    lines.append("        GMOUSE_WHEEL = 5,")
    lines.append("        GBUTTON_NONE = 0,")
    lines.append("        GBUTTON_LEFT = 1,")
    lines.append("        GBUTTON_RIGHT = 2,")
    lines.append("    };")
    lines.append("")
    lines.append("    enum DUSER_INPUT_MODIFIERS : unsigned int")
    lines.append("    {")
    lines.append("        GMODIFIER_NONE = 0,")
    lines.append("        GMODIFIER_LBUTTON = 0x0001,")
    lines.append("        GMODIFIER_RBUTTON = 0x0002,")
    lines.append("        GMODIFIER_SHIFT = 0x0004,")
    lines.append("        GMODIFIER_CONTROL = 0x0008,")
    lines.append("        GMODIFIER_MIDDLE = 0x0010,")
    lines.append("        GMODIFIER_LALT = 0x0020,")
    lines.append("        GMODIFIER_RALT = 0x0040,")
    lines.append("    };")
    lines.append("")
    lines.append("    struct Event")
    lines.append("    {")
    lines.append("        Element* target;")
    lines.append("        UID type;")
    lines.append("        bool handled;")
    lines.append("        DUSER_MSG_FLAG flag;")
    lines.append("    };")
    lines.append("")
    lines.append("    struct InputEvent")
    lines.append("    {")
    lines.append("        Element* target;")
    lines.append("        bool handled;")
    lines.append("        DUSER_MSG_FLAG flag;")
    lines.append("        DUSER_INPUT_DEVICE device;")
    lines.append("        DUSER_INPUT_CODE code;")
    lines.append("        DUSER_INPUT_MODIFIERS modifiers;")
    lines.append("    };")
    lines.append("")
    lines.append("    // CClassFactory: opaque handle type used by UITest's Register hook")
    lines.append("    // (the real implementation is internal to dui70.dll).")
    lines.append("    struct CClassFactory;")
    lines.append("")
    # Pure abstract consumer interface. novtable (MIDL_INTERFACE semantics;
    # real DLL has NO IElementListener symbols): UITest listener classes
    # derive from this -- their ctors must not emit a base vftable here.
    # NOTE: the ctor is left implicit (NOT declare-only) -- a declared-only
    # ctor would put an UNDEF ??0IElementListener...IEAA into consumer objs
    # (UITest listeners call the base ctor), and the shim lib cannot
    # resolve it. The implicit trivial ctor may appear as a COMDAT inside
    # the DERIVING consumer's own obj, which is self-contained and fine.
    lines.append("    struct __declspec(novtable) IElementListener")
    lines.append("    {")
    lines.append("    public:")
    lines.append("        // slot 0")
    lines.append("        virtual void OnListenerAttach(Element* elem) = 0;")
    lines.append("        // slot 1")
    lines.append("        virtual void OnListenerDetach(Element* elem) = 0;")
    lines.append("        // slot 2 -- returns false to cancel")
    lines.append("        virtual bool OnPropertyChanging(Element* elem, PropertyInfo const* prop, int unk, Value* before, Value* after) = 0;")
    lines.append("        // slot 3")
    lines.append("        virtual void OnListenedPropertyChanged(Element* elem, PropertyInfo const* prop, int type, Value* before, Value* after) = 0;")
    lines.append("        // slot 4")
    lines.append("        virtual void OnListenedInput(Element* elem, InputEvent* event) = 0;")
    lines.append("        // slot 5")
    lines.append("        virtual void OnListenedEvent(Element* elem, Event* event) = 0;")
    lines.append("    };")
    lines.append("")
    # IClassInfo: real DLL has NO ??0/??1/??_7 IClassInfo symbols (only
    # derived ElementClassInfo etc.). novtable prevents a vftable for this
    # interface; the inline empty bodies are never emitted unless odr-used
    # (the stub TUs never instantiate IClassInfo). The non-trivial-ish
    # shape (user-declared ctor/dtor) is kept so consumers stay source-
    # compatible with the DirectUI interface shape.
    lines.append("    struct __declspec(novtable) IClassInfo")
    lines.append("    {")
    lines.append("        IClassInfo() {}")
    lines.append("        IClassInfo(const IClassInfo&) = delete;")
    lines.append("        IClassInfo& operator=(const IClassInfo&) = delete;")
    lines.append("        virtual ~IClassInfo() {}")
    lines.append("")
    lines.append("    public:")
    lines.append("        // slots follow the DirectUI order (AddRef..AssertPIZeroRef,")
    lines.append("        // then the deleting dtor)")
    lines.append("        virtual long AddRef(void) = 0;                                   // 0")
    lines.append("        virtual long Release(void) = 0;                                 // 1")
    lines.append("        virtual long CreateInstance(Element*, unsigned long*, Element**) = 0;  // 2")
    lines.append("        virtual PropertyInfo* EnumPropertyInfo(unsigned int) = 0;       // 3")
    lines.append("        virtual PropertyInfo* GetByClassIndex(unsigned int) = 0;        // 4")
    lines.append("        virtual unsigned int GetPICount(void) = 0;                     // 5")
    lines.append("        virtual unsigned int GetGlobalIndex(void) = 0;                 // 6")
    lines.append("        virtual IClassInfo* GetBaseClass(void) = 0;                    // 7")
    lines.append("        virtual UCString GetName(void) = 0;                            // 8")
    lines.append("        virtual bool IsValidProperty(PropertyInfo const*) = 0;        // 9")
    lines.append("        virtual bool IsSubclassOf(IClassInfo*) = 0;                   // 10")
    lines.append("        virtual void Destroy(void) = 0;                               // 11")
    lines.append("        virtual HINSTANCE GetModule(void) = 0;                        // 12")
    lines.append("        virtual bool IsGlobal(void) = 0;                              // 13")
    lines.append("        virtual void AddChild(void) = 0;                              // 14")
    lines.append("        virtual void RemoveChild(void) = 0;                           // 15")
    lines.append("        virtual unsigned int GetChildren(void) = 0;                   // 16")
    lines.append("        virtual void AssertPIZeroRef(void) = 0;                       // 17")
    lines.append("    };")
    lines.append("")
    lines.append("    // IXProviderCP / IXElementCP are REAL exported classes now --")
    lines.append("    // see their generated headers (IXProviderCP.h / IXElementCP.h).")
    lines.append("")
    lines.append("    // IXProvider: the abstract interface XProvider implements.")
    lines.append("    // Slot order: IUnknown first (QI/AddRef/Release), then the")
    lines.append("    // provider methods in DirectUI order. On x64 the real methods")
    lines.append("    // are all __cdecl; the __stdcall markers in the DirectUI headers are")
    lines.append("    // ignored by the x64 compiler, so we use the default here too.")
    lines.append("    //")
    lines.append("    // MIDL_INTERFACE semantics (struct + novtable + protected ctor with")
    lines.append("    // NO definition): a pure abstract interface must not EMIT any")
    lines.append("    // symbol. Without novtable the compiler synthesizes ??_7IXProvider")
    lines.append("    // (vftable) for the base subobject that XProvider's ctor")
    lines.append("    // initializes; with an implicit public ctor it emits")
    lines.append("    // ??0IXProvider...QEAA as a COMDAT. Neither exists in the real DLL")
    lines.append("    // (A4 precision target). The protected ctor is DECLARED but NOT")
    lines.append("    // DEFINED: the stub obj then carries only an UNDEF reference to it")
    lines.append("    // (never linked; A4 judges defined symbols only). 'struct' matches")
    lines.append("    // the real mangling -- the DLL refers to IXProvider as PEAU")
    lines.append("    // (struct), e.g. ?GetProvider@XElement@DirectUI@@QEAAPEAUIXProvider@2@XZ,")
    lines.append("    // while IXProviderCP/IXElementCP mangle as PEAV (class) and stay 'class'.")
    lines.append("    struct __declspec(novtable) IXProvider : public IUnknown")
    lines.append("    {")
    lines.append("    protected:")
    lines.append("        IXProvider();  // declared only: never defined, never emitted")
    lines.append("    public:")
    lines.append("        virtual long CreateDUI(IXElementCP*, HWND*) = 0;")
    lines.append("        virtual long SetParameter(GUID const&, void*) = 0;")
    lines.append("        virtual long GetDesiredSize(int, int, SIZE*) = 0;")
    lines.append("        virtual long IsDescendent(Element*, bool*) = 0;")
    lines.append("        virtual long SetFocus(Element*) = 0;")
    lines.append("        virtual long Navigate(int, bool*) = 0;")
    lines.append("        virtual long CanSetFocus(bool*) = 0;")
    lines.append("        virtual int FindElementWithShortcutAndDoDefaultAction(unsigned short, int) = 0;")
    lines.append("        virtual long GetHostedElementID(unsigned short*) = 0;")
    lines.append("        virtual long ForceThemeChange(UINT_PTR, LONG_PTR) = 0;")
    lines.append("        virtual long SetDefaultButtonTracking(bool) = 0;")
    lines.append("        virtual int ClickDefaultButton(void) = 0;")
    lines.append("        virtual long SetRegisteredDefaultButton(Element*) = 0;")
    lines.append("        virtual long SetButtonClassAcceptsEnterKey(bool) = 0;")
    lines.append("    };")
    lines.append("")
    lines.append("} // namespace DirectUI")
    lines.append("")
    return "\n".join(lines)


# Complete plain-name C API export table (86 entries, alphabetical).
# The export table carries ONLY the undecorated name; on x64 there is one
# calling convention, so any signature compiles to the same plain symbol.
# Types are chosen to be harmless for stubs (pointer-friendly) and useful
# for consumers: known shapes come from UITest usage and the public DirectUI
# headers; unknown shapes use conservative (void*/int) parameter lists.
C_API_DECLS = [
    # -- color/brush enum helpers (CreateStyle value baking) --
    "unsigned long WINAPI ARGBColorFromEnumI(int e);",
    "unsigned long WINAPI BrushFromEnumI(int e);",
    "unsigned long WINAPI ColorFromEnumI(int e);",
    # -- animation control (UITest experiment consumers) --
    "int  WINAPI IsAnimationsEnabled(void);",
    "void WINAPI EnableAnimations(void);",
    "void WINAPI DisableAnimations(void);",
    "void WINAPI DUIStopPVLAnimation(void* element);",
    # -- callstack tracking --
    "void WINAPI DisableInitCallstackTracking(void);",
    # -- DUI wrapper creation (DUser interop) --
    "void* WINAPI CreateDUIWrapper(void);",
    "void* WINAPI CreateDUIWrapperEx(unsigned short const* name, unsigned short const* info);",
    "void* WINAPI CreateDUIWrapperFromResource(int resId, unsigned short const* name, void* module);",
    # ?CreateDUIWrapperTouchEx@DirectUI@@YAJPEAVElement@1@PEAVIXProviderCP@1@PEAPEAUIUnknown@@@Z
    # (rva 0xD8E10, same address as the export): long(Element*, IXProviderCP*, IUnknown**).
    "long WINAPI CreateDUIWrapperTouchEx(DirectUI::Element* element, DirectUI::IXProviderCP* provider, IUnknown** out);",
    # -- touch tooltip --
    "long WINAPI CreateTouchTooltip(void* element, int flags, void** tooltip);",
    # -- DUI70_* flat C API (scripting interop family) --
    "void* WINAPI DUI70_DUIXmlParserCreate(void);",
    "long  WINAPI DUI70_DUIXmlParserCreateElement(void* parser, void* parent, void** element);",
    # ??$HDelete@VElement@DirectUI@@@DirectUI@@YAXPEAVElement@0@@Z (rva 0x5FF20):
    # loads vtable[0] (vector deleting dtor) and tail-calls the release path --
    # the parameter is the Element to delete, not a parser.
    "void WINAPI DUI70_DUIXmlParserDestroy(DirectUI::Element* element);",
    # Export rva 0x88FD0 is a thunk: movzwl %dx (resId is u16), r8 = L"UIFILE"
    # (resource type), r9 = original r8; callee is
    # DUIXmlParser::SetXMLFromResource(name, type, HINSTANCE, HINSTANCE).
    # Both HINSTANCEs come from the caller (FindResource pattern).
    "long WINAPI DUI70_DUIXmlParserSetXMLFromResource(DirectUI::DUIXmlParser* parser, unsigned short resId, HINSTANCE mod1, HINSTANCE mod2);",
    "long  WINAPI DUI70_ElementAddListener(void* element, void* listener);",
    "void  WINAPI DUI70_ElementDestroy(void* element);",
    "long  WINAPI DUI70_ElementEndDefer(void* element);",
    "void* WINAPI DUI70_ElementFindDescendent(void* element, int atom);",
    "void* WINAPI DUI70_ElementGetChildren(void* element);",
    "void* WINAPI DUI70_ElementGetRoot(void* element);",
    "long  WINAPI DUI70_ElementRemoveListener(void* element, void* listener);",
    "long  WINAPI DUI70_ElementSetAccRole(void* element, int role);",
    "long  WINAPI DUI70_ElementSetAccessible(void* element, void* accessible);",
    "long  WINAPI DUI70_ElementSetContentAlign(void* element, int align);",
    "long  WINAPI DUI70_ElementSetContentString(void* element, unsigned short const* s);",
    "long  WINAPI DUI70_ElementSetFont(void* element, unsigned short const* font);",
    "long  WINAPI DUI70_ElementSetID(void* element, unsigned short const* id);",
    "long  WINAPI DUI70_ElementSetLayoutPos(void* element, int pos);",
    "long  WINAPI DUI70_ElementSetVisible(void* element, int visible);",
    "long  WINAPI DUI70_ElementStartDefer(void* element);",
    "int   WINAPI DUI70_IsTouchButtonClickEqual(int a, int b);",
    # ??$CreateElementT@VRichText@DirectUI@@@@YAJPEAVElement@@PEAKPEAPEAVRichText@@Z
    # (rva 0x600A0): long(Element*, unsigned long*, RichText**). Same shape as
    # DuiCreateObject: first instruction `andq $0,(%r8)` dereferences out.
    "long WINAPI DUI70_RichTextCreate(DirectUI::Element* parent, unsigned long* flags, DirectUI::RichText** out);",
    "long  WINAPI DUI70_RichTextSetConstrainLayout(void* richtext, int constrain);",
    "void  WINAPI DUI70_ValueRelease(void* value);",
    # -- shadow text --
    "long WINAPI DUIDrawShadowText(void* hdc, unsigned short const* s, unsigned int cch, struct _RECT* rect, unsigned int format, unsigned long color, int offsetX, int offsetY, int thickness, unsigned long shadowColor);",
    "long WINAPI DrawShadowTextEx(void* hdc, unsigned short const* s, unsigned int cch, struct _RECT* rect, unsigned int format, unsigned long color, int offsetX, int offsetY, int thickness, unsigned long shadowColor, void* opts);",
    # -- object creation --
    # Signature verified from the DLL's own unexported C++ symbol at the same
    # RVA as the export (?DuiCreateObject@@YAJAEBU_GUID@@0PEAPEAX@Z, both at
    # 0x8B00) and from the disassembly (first instruction `andq $0,(%r8)`
    # dereferences the third parameter). Two-argument calls leave r8 as
    # garbage and access-violate before any GUID comparison runs.
    "long WINAPI DuiCreateObject(struct _GUID const& clsid, struct _GUID const& riid, void** out);",
    "long WINAPI ElementFromGadget(void* gadget, struct DirectUI::Element** out);",
    # -- theme handle cache --
    "void WINAPI FlushThemeHandles(void);",
    "void WINAPI PurgeThemeHandles(void);",
    "void* WINAPI GetThemeHandle(int classId);",
    # -- misc --
    "void WINAPI ForceDebugBreak(void);",
    "unsigned int WINAPI GetDesktopDPI(unsigned int* dpiX, unsigned int* dpiY);",
    "void WINAPI SetDesktopDPIOverride(unsigned int dpiX, unsigned int dpiY);",
    "unsigned int WINAPI GetScaleFactor(void);",
    "long WINAPI GetElementDataEntry(void* gadget, void** out);",
    "long WINAPI GetElementMacro(void* gadget, void** out);",
    "void* WINAPI GetFontCache(void);",
    "long WINAPI HStrDup(unsigned short const* s, unsigned short** out);",
    "long WINAPI HrSysAllocString(unsigned short const* s, unsigned short** out);",
    # -- process/thread init (UITest consumers) --
    "long WINAPI InitProcessPriv(int duiVersion, unsigned short* unk1, char unk2, bool bEnableUIAutomationProvider);",
    "long WINAPI UnInitProcessPriv(unsigned short* unk1);",
    "long WINAPI InitThread(int iDontKnow);",
    "void WINAPI UnInitThread(void);",
    "void WINAPI SkipDLLUnloadInitChecks(void);",
    # -- preprocessor / factories --
    "long WINAPI InitPreprocessor(void);",
    "long WINAPI PreprocessBuffer(void);",
    "void WINAPI RegisterPVLBehaviorFactory(void);",
    # -- string helpers --
    "unsigned short* WINAPI MultiByteToUnicode(char const* s);",
    "char* WINAPI UnicodeToMultiByte(unsigned short const* s);",
    "unsigned short WINAPI StrToID(UCString resId);",
    # -- queries --
    "int WINAPI IsPalette(void);",
    "int WINAPI IsUIAutomationProviderEnabled(void);",
    # -- accessibility --
    "void WINAPI NotifyAccessibilityEvent(void* element, int eventId);",
    # -- message pump (UITest consumers) --
    "int  WINAPI StartMessagePump(void);",
    "void WINAPI StopMessagePump(void);",
    # -- UIA sinks --
    "void WINAPI UiaHideOnGetObject(void* element);",
    "void WINAPI UiaOnDestroySink(void* element);",
    "void* WINAPI UiaOnGetObject(void* element, unsigned int childId, void* riid);",
    "void WINAPI UiaOnToolTip(void* element, int action);",
    # -- control registration (UITest consumer: RegisterAllControls) --
    "int WINAPI RegisterAllControls(void);",
    "int WINAPI RegisterBaseControls(void);",
    "int WINAPI RegisterBrowserControls(void);",
    "int WINAPI RegisterCommonControls(void);",
    "int WINAPI RegisterExtendedControls(void);",
    "int WINAPI RegisterMacroControls(void);",
    "int WINAPI RegisterMiscControls(void);",
    "int WINAPI RegisterStandardControls(void);",
    "int WINAPI RegisterXControls(void);",
    # -- misc setters --
    "void WINAPI SetDefAction(void* element, void* action);",
    "void WINAPI AllowAllScalingPlateaus(void);",
    # -- imaging --
    "long WINAPI BlurBitmap(void* src, void* dst, unsigned int a2, unsigned int a3, unsigned int a4, unsigned int a5, float a6, float a7, void* a8);",
    "long WINAPI ProcessAlphaBitmapI(void* a0, int a1, unsigned int a2, unsigned int a3, unsigned int a4, unsigned int a5, unsigned int a6, unsigned int a7, unsigned int a8, void* a9, void* a10);",
]


def render_extern_c_block() -> str:
    """extern "C" declarations for ALL 86 plain-name C API exports.
    The real DLL exports these as undecorated C symbols; declaring them
    extern "C" produces exactly the same symbol shape for the linker.
    The export table carries only the names, so the parameter lists are
    pipeline-recovered where known (UITest usage, public DirectUI headers)
    and conservative elsewhere. Verification checks the NAME set (dumpbin
    plain names vs declarations), not signatures."""
    lines = []
    lines.append("")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append('// extern "C" API -- the complete plain-name export set of the real')
    lines.append("// dui70.dll (86 entries). Signatures are pipeline-recovered where known")
    lines.append("// and conservative elsewhere; the export table itself only carries the")
    lines.append('// undecorated names, which extern "C" reproduces exactly.')
    lines.append("// ---------------------------------------------------------------------------")
    lines.append('extern "C" {')
    lines.append("")
    for d in C_API_DECLS:
        lines.append(d)
    lines.append("")
    lines.append('} // extern "C"')

    # Decorated free functions (real exports, global scope, C++ mangling).
    # DumpDuiTree is consumed by UITest.
    lines.append("")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// Free functions -- decorated exports of the real dui70.dll")
    lines.append('// (mangled ?Name@@YA...; NOT extern "C").')
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("void __cdecl DumpDuiTree(DirectUI::Element* element, int depth);")
    return "\n".join(lines)


def render_aggregate_header(classes: list, banner: str) -> str:
    lines = [banner]
    n = len(classes)
    lines.append(f"// Aggregate header for the {n} UITest-required classes.")
    lines.append("#pragma once")
    lines.append("")
    lines.append('#include "dui_abi_types.h"')
    lines.append('#include "Interfaces.h"')
    # DuiEnums.h is a handwritten registry file (not emitted by this pipeline):
    # the aggregate header pulls it in so consumers get the enum surface, but the
    # emitter never writes it. A name-collision assertion must guard this exact
    # relationship (generated file set vs. referenced handwritten file).
    lines.append('#include "DuiEnums.h"')
    for cls in classes:
        if is_duixml_nested(cls) or is_nested_pseudo_class(cls):
            # nested in a host class: declared inside the host's header
            continue
        lines.append(f'#include "{safe_name(cls)}.h"')
    # extern "C" API block at the end (needs UCString from dui_abi_types.h)
    lines.append(render_extern_c_block())
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pinned", type=Path, default=DEFAULT_PINNED)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--classes", default=None,
                    help="override the class list from classes.json (comma-separated)")
    args = ap.parse_args(argv)

    # class list + inheritance from pinned/classes.json (axis B made explicit)
    classes, inheritance = load_classes(args.pinned / "classes.json")
    if args.classes:
        classes = [c.strip() for c in args.classes.split(",") if c.strip()]

    out_dir: Path = args.out
    out_dir.mkdir(parents=True, exist_ok=True)

    # pin fingerprint for the banner
    manifest = json.loads((args.pinned / "manifest.json").read_text(encoding="utf-8"))
    pin_hash12 = manifest["dll"]["sha256"][:12]
    banner = make_banner(pin_hash12)

    symbols = load_symbols(args.pinned / "symbols.json")
    tr = TypeTranslator(classes)

    stats = {}
    for cls in classes:
        if is_duixml_nested(cls):
            # nested in DUIXmlParser: emitted by its header/TU, not standalone
            continue
        if is_nested_pseudo_class(cls):
            # nested in a host class (e.g. AccessibleButton::ACCESSIBLEROLE):
            # declared inside the host's header, no standalone file
            continue
        members = [s for s in symbols
                   if s.get("class") == cls
                   and s.get("is_exported")
                   and in_directui_scope(s)
                   and is_callable(s)]
        data_members = [s for s in symbols
                        if s.get("class") == cls
                        and s.get("is_exported")
                        and in_directui_scope(s)
                        and is_data(s)]
        has_own_vftable = any(
            (s.get("mangled") or "").endswith(f"??_7{cls}@DirectUI@@6B@")
            for s in symbols
            if s.get("class") == cls and s.get("is_exported")
        )
        content = render_class_header(cls, members, data_members, tr,
                                      classes, inheritance, banner,
                                      has_own_vftable=has_own_vftable)
        (out_dir / f"{safe_name(cls)}.h").write_text(content, encoding="utf-8", newline="\n")
        stats[cls] = {"methods": len(members), "data": len(data_members)}

    # shared prelude + interfaces + aggregate
    (out_dir / "dui_abi_types.h").write_text(render_abi_types_header(banner), encoding="utf-8", newline="\n")
    (out_dir / "Interfaces.h").write_text(render_interfaces_header(banner), encoding="utf-8", newline="\n")
    (out_dir / "DirectUI.h").write_text(render_aggregate_header(classes, banner), encoding="utf-8", newline="\n")

    print(f"emit_headers: wrote {len(stats) + 3} files to {out_dir}")
    for cls in classes:
        s = stats.get(cls)
        if not s:
            continue
        print(f"  {cls:<16} callables={s['methods']:4d} data={s['data']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
