#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
emit_headers.py -- header emitter of the dui-pipeline.

Generates C++ header files for the target DirectUI classes from
pinned/symbols.json + pinned/classes.json. Output is deterministic:
the same pinned inputs always produce byte-identical files (CI golden).

Contract: tools/dui-pipeline/INTERFACE.md.

Usage:
    python emit_headers.py [--pinned <dir>] [--out <dir>] [--classes a,b,c]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DEFAULT_PINNED = REPO / "pinned"
DEFAULT_OUT = REPO / "DirectUI" / "include"

CALLABLE_KINDS = {"method", "static_method", "ctor", "dtor", "operator"}

# ---------------------------------------------------------------------------
# Type universe
# ---------------------------------------------------------------------------
# Types inside namespace DirectUI. kind -> declaration strategy.
DIRECTUI_CLASS_TYPES = {
    "DeferCycle": "fwd",
    "ElementProvider": "fwd",
    "Expression": "fwd",
    "InvokeHelper": "fwd",
    "Layout": "fwd",
    "StyleSheet": "fwd",
    "Surface": "fwd",
    "TouchHWNDElement": "fwd",
}
DIRECTUI_STRUCT_TYPES = {
    "Cursor": "fwd",
    "DepRecs": "fwd",
    "EnumMap": "fwd",
    "Event": "fwd",
    "Fill": "fwd",
    "Graphic": "fwd",
    "IClassInfo": "fwd",
    "IElementListener": "fwd",
    "InputEvent": "fwd",
    "KeyboardEvent": "fwd",
    "LINEINFO": "define",  # by-value in several DUIXmlParser signatures
    "MouseEvent": "fwd",
    "NavReference": "fwd",
    "PointerEvent": "fwd",
    "PropertyInfo": "fwd",
    "ScaledInt": "fwd",
    "ScaledRECT": "define",  # by-value? no - pointer only, but keep symmetrical
    "ScaledSIZE": "define",  # by-value in Value::CreateGraphic
    "ThemeChangedEvent": "fwd",
    "UpdateCache": "fwd",
}
# extra struct types referenced by the target class set
EXTRA_STRUCT_TYPES = [
    "IDialogElement", "IXBaby", "IXElementCP", "IXProviderCP",
]

def make_banner(pin_hash12: str) -> str:
    return (
        f"// Generated by tools/dui-pipeline — DO NOT EDIT. "
        f"Pin: {pin_hash12}\n"
    )


# ---------------------------------------------------------------------------
# undecorated-type-text -> C++ declaration text translation
# ---------------------------------------------------------------------------

FN_PTR_RE = re.compile(
    r"^(?P<ret>.+?)\s*\(__cdecl\s*\*\)\s*\((?P<args>.*)\)$"
)

# Template-id like 'class DirectUI::DynamicArray<class DirectUI::Element *, 0>'
# or 'struct DirectUI::DUIXmlParser::FunctionDefinition<int>'
TEMPLATE_ID_RE = re.compile(
    r"^(?:class|struct|union)\s+DirectUI::(\w+)<(.*)>$"
)


class TypeTranslator:
    """Translates undecorated parameter/return type strings into C++ decl text
    usable inside `namespace DirectUI`."""

    def __init__(self, target_classes):
        self.target_classes = set(target_classes)

    # -- helpers ----------------------------------------------------------

    @staticmethod
    def _strip_scope(text: str) -> str:
        """Remove 'DirectUI::' qualifications (we are inside that namespace)."""
        return re.sub(r"\bDirectUI::", "", text)

    @staticmethod
    def _strip_class_kw(text: str) -> str:
        return re.sub(r"^(class|struct|union|enum)\s+", "", text)

    def translate(self, text: str) -> str:
        """Translate one type string to C++ declaration syntax."""
        text = text.strip()
        # function pointer: 'ret (__cdecl *)(args)'
        m = FN_PTR_RE.match(text)
        if m:
            ret = self.translate(m.group("ret"))
            args = m.group("args").strip()
            if args in ("", "void"):
                arg_list = "void"
            else:
                arg_list = ", ".join(
                    self.translate(a.strip()) for a in self._split_args(args)
                )
            return f"{ret} (__cdecl*)({arg_list})"
        # template-id: 'class DirectUI::DynamicArray<X, 0>'
        m = TEMPLATE_ID_RE.match(text)
        if m:
            name, raw_args = m.groups()
            args = []
            for a in self._split_args(raw_args):
                a = a.strip()
                if re.fullmatch(r"-?\d+", a):
                    args.append(a)  # non-type parameter
                else:
                    args.append(self.translate(a))
            return f"{name}<{', '.join(args)}>"
        # 'unsigned short const *' etc: normalize to 'unsigned short const*'
        t = self._strip_scope(text)
        t = self._strip_class_kw(t)
        t = re.sub(r"\s*\*", "*", t)
        t = re.sub(r"\s*&", "&", t)
        # normalize 'const X'/'X const' trailing style: keep as-is except
        # pointer-to-const: 'X const*' stays; MSVC accepts both orders.
        return t

    def translate_def(self, text: str, name: str) -> str:
        """Translate one type string for a definition context, binding the
        parameter name. Function pointers get the name inside the (*name)
        declarator."""
        text = text.strip()
        m = FN_PTR_RE.match(text)
        if m:
            ret = self.translate(m.group("ret"))
            args = m.group("args").strip()
            if args in ("", "void"):
                arg_list = "void"
            else:
                arg_list = ", ".join(
                    self.translate(a.strip()) for a in self._split_args(args)
                )
            return f"{ret} (__cdecl* {name})({arg_list})"
        plain = self.translate(text)
        if plain.endswith("*") or plain.endswith("&"):
            return f"{plain}{name}"
        return f"{plain} {name}"

    @staticmethod
    def _split_args(text: str) -> list:
        """Split a comma-separated argument list, respecting parentheses."""
        parts, depth, cur = [], 0, []
        for ch in text:
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
            if ch == "," and depth == 0:
                parts.append("".join(cur))
                cur = []
            else:
                cur.append(ch)
        if cur:
            parts.append("".join(cur))
        return [p for p in (s.strip() for s in parts) if p]


# ---------------------------------------------------------------------------
# Symbol model helpers
# ---------------------------------------------------------------------------

# Access recovery from the mangled name: the access letter is ENCODED IN
# the decorated name per the MSVC access-code scheme (it would otherwise
# change: public=Q/E/U, protected=I/K/M, private=A/C/E). The matrix
# (letter x is_virtual x is_static -> access) is the standard encoding:
#   plain:  A=private  I=protected  Q=public
#   static: C=private  K=protected  S=public
#   virt:   E=private  M=protected  U=public
# ('W'/'Y' letters are MI thunks, never present on target classes.)
MANGLED_ACCESS_RE = re.compile(r"^\?\w+@\w+@DirectUI@@([A-Z])")
ACCESS_FROM_MANGLED = {
    "A": "private", "C": "private", "E": "private",
    "I": "protected", "K": "protected", "M": "protected",
    "Q": "public", "S": "public", "U": "public",
}

# Static data members: ?name@Class@DirectUI@@<0|1|2><type><A|B>
# 0=private 1=protected 2=public; trailing B=const.
MANGLED_DATA_RE = re.compile(r"^\?\w+@\w+@DirectUI@@([012])(.*)$")
DATA_ACCESS_FROM_MANGLED = {"0": "private", "1": "protected", "2": "public"}


def access_of(sym: dict) -> str:
    """Recover the C++ access specifier from the mangled name.

    For members, the letter after ?member@Class@DirectUI@@ encodes
    access+virtual/static. For static data, the digit after the scope
    encodes access (0=private 1=protected 2=public)."""
    if sym.get("kind") == "data":
        m = MANGLED_DATA_RE.match(sym["mangled"])
        if m:
            return DATA_ACCESS_FROM_MANGLED.get(m.group(1), "public")
        return "public"
    m = MANGLED_ACCESS_RE.match(sym["mangled"])
    if not m:
        return "public"
    return ACCESS_FROM_MANGLED.get(m.group(1), "public")


def load_symbols(path: Path) -> list:
    data = json.loads(path.read_text(encoding="utf-8"))
    return data["symbols"]


def load_classes(path: Path) -> tuple[list, dict]:
    """Returns (classes, inheritance) from pinned/classes.json."""
    data = json.loads(path.read_text(encoding="utf-8"))
    return list(data["classes"]), dict(data.get("inheritance") or {})


def classify_dtor(sym: dict) -> bool:
    """True for the real destructor (??1Class...). The 'vector deleting
    dtor' (??_E...) is a compiler-generated entry, not an export."""
    return sym["mangled"].startswith("??1")


def classify_scalar_dtor(sym: dict) -> bool:
    """'vector deleting dtor' ??_E... entries - these are NOT exports (they
    come from the PDB publics) and are compiler-generated; we never emit
    them."""
    return sym["mangled"].startswith("??_E")


def is_callable(sym: dict) -> bool:
    if sym.get("kind") not in CALLABLE_KINDS:
        # plain methods that merely USE template parameter types (e.g.
        # ?CreateElementList@Value@...DynamicArray@...) carry kind='template'
        # in the symbol table but are NOT function templates (no ??$ prefix)
        if sym.get("kind") != "template":
            return False
    if classify_scalar_dtor(sym):
        return False
    # True function templates (??$...) are skipped -- their instantiations
    # are compile-time and cannot be re-emitted from a declaration.
    if sym["mangled"].startswith("??$"):
        return False
    return True


def is_data(sym: dict) -> bool:
    if sym["mangled"].startswith("??$"):
        return False
    return sym.get("kind") == "data"


# ---------------------------------------------------------------------------
# Declaration rendering
# ---------------------------------------------------------------------------


class MemberDecl:
    def __init__(self, sym: dict, cls: str):
        self.sym = sym
        self.cls = cls
        self.is_dtor = classify_dtor(sym)
        self.is_ctor = sym["kind"] == "ctor" and not self.is_dtor

    def fnptr_return(self) -> str | None:
        """Return the raw fn-pointer return-type text if the method returns
        a function pointer, else None.

        return_type stores the complete shape, e.g.:
            'class DirectUI::Value * (__cdecl *)(unsigned short const *, void *)'
        We detect that via the '(__cdecl *)' marker."""
        ret = self.sym.get("return_type") or ""
        if re.match(r"^(.*?)\s*\(__cdecl\s*\*\)\s*\((.*)\)$", ret.strip()):
            return ret.strip()
        return None

    def signature(self, tr: TypeTranslator) -> str:
        s = self.sym
        name = s["member"]
        if self.is_ctor or self.is_dtor:
            if self.is_dtor:
                name = "~" + self.cls
            params = s.get("params") or []
            param_text = ", ".join(tr.translate(p) for p in params) or "void"
            sig = f"{name}({param_text})"
        else:
            params = s.get("params") or []
            param_text = ", ".join(tr.translate(p) for p in params) or "void"
            fpr = self.fnptr_return()
            if fpr:
                # function returning a function pointer -- use trailing
                # return type: the shape is emitted verbatim after '->'.
                # The decorated name is unaffected (it encodes the
                # signature, not the syntax).
                sig = f"auto {name}({param_text}) -> {tr.translate(fpr)}"
            else:
                ret = tr.translate(s["return_type"]) if s.get("return_type") else "void"
                sig = f"{ret} {name}({param_text})"
        if s.get("is_const"):
            sig += " const"
        return sig

    def qualifiers(self) -> str:
        s = self.sym
        q = []
        if s.get("is_virtual"):
            q.append("virtual")
        if s.get("is_static"):
            q.append("static")
        return " ".join(q)

    def is_virtual(self) -> bool:
        return bool(self.sym.get("is_virtual"))

    def full_decl(self, tr: TypeTranslator) -> str:
        q = self.qualifiers()
        sig = self.signature(tr)
        if q:
            return f"{q} {sig};"
        return f"{sig};"


def order_key(sym: dict):
    # keep original order from the symbol table (roughly vtable order for
    # virtuals, which helps readability but is not semantically required)
    return 0


# ---------------------------------------------------------------------------
# Header emission
# ---------------------------------------------------------------------------


def render_class_header(cls: str, members: list, data_members: list,
                        tr: TypeTranslator, classes: list,
                        inheritance: dict, banner: str) -> str:
    """Render one class header file content."""
    lines = []
    lines.append(banner)
    lines.append(f"// DirectUI::{cls} -- declarations derived from the real")
    lines.append("// dui70.dll export table + PDB publics.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <windows.h>")
    lines.append('#include "dui_abi_types.h"')
    lines.append("")
    # include the base-class header (must be a complete type)
    base = inheritance.get(cls)
    if base and base in classes:
        lines.append(f'#include "{base}.h"')
        lines.append("")
    if cls == "XProvider":
        # XProvider : IXProvider (abstract consumer interface)
        lines.append('#include "Interfaces.h"')
        lines.append("")

    lines.append("namespace DirectUI")
    lines.append("{")
    # forward declarations for sibling generated classes
    siblings = [c for c in classes if c != cls and c != base]
    for sib in siblings:
        lines.append(f"    class {sib};")
    lines.append("")

    # Access is recovered from the mangled name (access_of); sections are
    # emitted in public -> protected -> private order (matches the old
    # output exactly, keeping the golden diff stable).
    sections = {"public": [], "protected": [], "private": []}
    for sym in members:
        acc = access_of(sym)
        sections.setdefault(acc, []).append(sym)

    lines.append(f"    class {cls}")
    if base:
        lines.append(f"        : public {base}")
    lines.append("    {")
    lines.append("    public:")

    if cls == "TouchButton":
        lines.append("        enum ClickDevice")
        lines.append("        {")
        lines.append("            ClickDevice_None = 0,")
        lines.append("        };")
        lines.append("")

    if cls == "DUIXmlParser":
        # nested union referenced by ParseArgs/ParseFunction (mangles
        # PEATParsedArg@12@ -- must be nested inside DUIXmlParser)
        lines.append("        union ParsedArg")
        lines.append("        {")
        lines.append("            unsigned __int64 _raw;")
        lines.append("        };")
        lines.append("")
        # nested template struct used by the s_fd* static tables (mangles
        # U?$FunctionDefinition@...@12@ -- nested inside DUIXmlParser).
        # The real DLL exports its operator= for 5 instantiations, so we
        # declare them out-of-line (definitions in the stub TU).
        lines.append("        template <typename T>")
        lines.append("        struct FunctionDefinition")
        lines.append("        {")
        lines.append("            int _abi;")
        lines.append("            FunctionDefinition& operator=(FunctionDefinition const&);")
        lines.append("            FunctionDefinition& operator=(FunctionDefinition&&);")
        lines.append("        };")
        lines.append("")

    data_by_access = {"public": [], "protected": [], "private": []}
    for dsym in data_members:
        data_by_access.setdefault(access_of(dsym), []).append(dsym)

    first = True
    for acc in ("public", "protected", "private"):
        syms = sections.get(acc) or []
        data_syms = data_by_access.get(acc) or []
        if not syms and not data_syms:
            continue
        if not first:
            lines.append("")
            lines.append(f"        {acc}:")
        first = False

        for sym in syms:
            md = MemberDecl(sym, cls)
            decl = md.full_decl(tr)
            lines.append(f"        {decl}")
        for dsym in data_syms:
            lines.append(f"        {render_data_decl(dsym, tr)}")

    lines.append("    };")
    lines.append("")
    lines.append("} // namespace DirectUI")
    lines.append("")
    return "\n".join(lines)


def render_data_decl(sym: dict, tr: TypeTranslator) -> str:
    """static data member in-class declaration, e.g.
    'static IClassInfo* s_pClassInfo;'

    The type comes from return_type, but for pointer members that field
    loses the pointer (e.g. 'struct DirectUI::IClassInfo' for what is
    really IClassInfo* -- mangled 0PEAU...EA). Pointer-ness is recovered
    from the mangled name."""
    ty = tr.translate(sym.get("return_type") or "")
    name = sym["member"]
    mang = sym["mangled"]
    # s_fd* tables: the real symbol 1QBU...B encodes a const ARRAY
    # (llvm-undname prints 'const *const' for it). Declare as array [1].
    # Normalize the '*const' pointer-const noise away first.
    if mang.startswith("?s_fd"):
        ty = re.sub(r"\s*const\s*\*\s*const\s*$", "", ty).strip()
        return f"static {ty} const {name}[1];"
    # pointer-to-struct/class/union: 'PEAU'/'PEAV'/'PEAT' (or 'PEQ' const)
    if re.search(r"@@[012]PE[QAUVT]", mang) and not ty.endswith("*"):
        ty = ty + "*"
    # 'int const' / 'long const' -> 'const int' style is equivalent;
    # keep the source order but put const first for style
    m = re.match(r"^(.*?)\s+const$", ty)
    if m and "*" not in ty:
        ty = f"const {m.group(1)}"
    return f"static {ty} {name};"


def render_abi_types_header(banner: str) -> str:
    """The shared prelude: global-scope declarations + DirectUI forward
    declarations + small complete definitions needed for by-value ABI."""
    lines = [banner]
    lines.append("// Shared ABI prelude for the generated DirectUI headers.")
    lines.append("// Contains only what is required to reproduce the exact")
    lines.append("// decorated names of the real dui70.dll exports:")
    lines.append("//  * global-scope forward declarations (mangled without @2@)")
    lines.append("//  * namespace DirectUI forward declarations")
    lines.append("//  * minimal complete definitions for by-value types")
    lines.append("// NOTE: compiled with /Zc:wchar_t- (the DirectUI ABI), so")
    lines.append("//       'const wchar_t*' == 'const unsigned short*' (UCString).")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <windows.h>")
    lines.append("")
    lines.append("// UCString: the DirectUI string ABI is 'unsigned short const*'.")
    lines.append("// With /Zc:wchar_t- a 'const wchar_t*' parameter mangles")
    lines.append("// identically (PEBG), so consumers may use either spelling.")
    lines.append("typedef unsigned short const* UCString;")
    lines.append("")
    lines.append("// Global-scope declarations (mangle WITHOUT the DirectUI back-reference)")
    lines.append("struct IAccessible;")
    lines.append("struct IDuiBehavior;")
    lines.append("struct ISharedBitmap;")
    lines.append("struct IStream;")
    lines.append("struct IUnknown;")
    lines.append("struct IXmlReader;")
    lines.append("struct EventMsg;")
    lines.append("struct tagGMSG;         // not in windows.h")
    lines.append("struct HGADGET__;       // DECLARE_HANDLE(HGADGET) in the real headers")
    lines.append("typedef struct HGADGET__* HGADGET;")
    lines.append("")
    lines.append("// UID: returned by value by several static event-id accessors.")
    lines.append("// Decorated name in the real DLL is VUID@@ (GLOBAL scope), so it is")
    lines.append("// declared here at global scope -- NOT inside namespace DirectUI.")
    lines.append("class UID")
    lines.append("{")
    lines.append("public:")
    lines.append("    UID() {}")
    lines.append("    void* value;")
    lines.append("};")
    lines.append("")
    lines.append("// Compare a UID against an event-id ACCESSOR FUNCTION (called on the")
    lines.append("// spot). Lets consumer code write `ev->type == TouchButton::Click`")
    lines.append("// without call parentheses (DirectUI types.h idiom).")
    lines.append("inline bool operator==(UID id, UID (*ev)(void))")
    lines.append("{")
    lines.append("    UID p = ev();")
    lines.append("    return id.value == p.value;")
    lines.append("}")
    lines.append("")
    lines.append("// DynamicScaleValue: GLOBAL-scope enum (W4DynamicScaleValue@@)")
    lines.append("enum DynamicScaleValue { DynamicScaleValue_None = 0 };")
    lines.append("")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// namespace DirectUI")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("namespace DirectUI")
    lines.append("{")
    lines.append("    // ---- complete definitions required for by-value parameters ----")
    lines.append("    struct LINEINFO { unsigned int line; };")
    lines.append("    struct ScaledSIZE { int w; int h; };")
    lines.append("    struct ScaledRECT { int l; int t; int r; int b; };")
    lines.append("")
    lines.append("    // ---- enums inside DirectUI ----")
    lines.append("    enum _DUI_PARSE_STATE { DUI_PARSE_STATE_None = 0 };")
    lines.append("    enum DynamicScaleParsing { DynamicScaleParsing_None = 0 };")
    lines.append("")
    lines.append("    // ---- class forward declarations ----")
    for name in sorted(DIRECTUI_CLASS_TYPES):
        lines.append(f"    class {name};")
    lines.append("")
    lines.append("    // ---- struct forward declarations ----")
    lines.append("    struct XMLParserCond;")
    for name in sorted(DIRECTUI_STRUCT_TYPES):
        if name in ("LINEINFO", "ScaledSIZE", "ScaledRECT"):
            continue
        lines.append(f"    struct {name};")
    for name in sorted(EXTRA_STRUCT_TYPES):
        lines.append(f"    struct {name};")
    lines.append("")
    lines.append("    // ---- enum for TouchCheckBox (W4CheckedStateFlags@2@) ----")
    lines.append("    enum CheckedStateFlags { CheckedStateFlags_None = 0 };")
    lines.append("")
    lines.append("    // ---- ValueType: consumer-side knowledge (enum members are never")
    lines.append("    // exported; members transcribed from DirectUI Value.h). Used by")
    lines.append("    // UITest in switch statements over Value::GetType(). ----")
    lines.append("    enum class ValueType : int")
    lines.append("    {")
    lines.append("        Unavailable = -2,")
    lines.append("        Unset = -1,")
    lines.append("        Null = 0,")
    lines.append("        Int = 1,")
    lines.append("        Bool = 2,")
    lines.append("        Element = 3,")
    lines.append("        Ellist = 4,")
    lines.append("        String = 5,")
    lines.append("        Point = 6,")
    lines.append("        Size = 7,")
    lines.append("        Rect = 8,")
    lines.append("        Color = 9,")
    lines.append("        Layout = 10,")
    lines.append("        Graphic = 11,")
    lines.append("        Sheet = 12,")
    lines.append("        Expr = 13,")
    lines.append("        Atom = 14,")
    lines.append("        Cursor = 15,")
    lines.append("        Float = 18,")
    lines.append("        DblList = 19,")
    lines.append("    };")
    lines.append("")
    lines.append("    // ---- ParserTools nested namespace ----")
    lines.append("    namespace ParserTools")
    lines.append("    {")
    lines.append("        struct ExprNode;")
    lines.append("        class ValueParser;")
    lines.append("    }")
    lines.append("")
    lines.append("    // ---- generic containers referenced by exported methods ----")
    lines.append("    // DynamicArray<T, N> is used as a plain (non-template) parameter")
    lines.append("    // type by several exported methods (CreateElementList etc.)")
    lines.append("    template <typename T, int N>")
    lines.append("    class DynamicArray;")
    lines.append("")
    lines.append("} // namespace DirectUI")
    lines.append("")
    return "\n".join(lines)


def render_interfaces_header(banner: str) -> str:
    """Consumer-side pure-abstract interfaces. These produce NO export
    symbols in the real DLL (they are consumed via vtable slots only), so
    they are transcribed from the DirectUI interface shapes with slot order
    preserved -- the //N comments are the vtable indices."""
    lines = [banner]
    lines.append("// Consumer-side interfaces: no exported symbols; vtable slot order")
    lines.append("// mirrors the real dui70.dll consumers (DirectUI Interfaces.h).")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <windows.h>")
    lines.append('#include "dui_abi_types.h"')
    lines.append("")
    lines.append("namespace DirectUI")
    lines.append("{")
    lines.append("")
    lines.append("    // ---- forward declarations (interfaces reference these) ----")
    lines.append("    class Value;")
    lines.append("    class Element;")
    lines.append("    class HWNDElement;")
    lines.append("    class DUIXmlParser;")
    lines.append("")
    lines.append("    // PropertyInfo: property metadata record (pointer-only in ABI).")
    lines.append("    // cap->type is a ValueType bitfield (DirectUI Primitives.h).")
    lines.append("    struct PropertyInfo")
    lines.append("    {")
    lines.append("        UCString name;             // property name")
    lines.append("        unsigned __int64 unk1;")
    lines.append("        struct PropCapability")
    lines.append("        {")
    lines.append("            ValueType type : 6;")
    lines.append("            unsigned other : 26;")
    lines.append("            unsigned unk;")
    lines.append("        } *cap;")
    lines.append("        struct { UCString str_value; int int_value; } *enum_value_map;")
    lines.append("        Value* (*get_default_value)();")
    lines.append("        unsigned __int64 *unk2;")
    lines.append("    };")
    lines.append("")
    lines.append("    // ---- DUSER enums + Event/InputEvent (consumer-side; from DirectUI")
    lines.append("    // misc.h -- Event is dereferenced by UITest listeners) ----")
    lines.append("    enum DUSER_MSG_FLAG : unsigned int")
    lines.append("    {")
    lines.append("        GMF_DIRECT = 0x00000000,      // OnMessage")
    lines.append("        GMF_ROUTED = 0x00000001,      // PreviewMessage")
    lines.append("        GMF_BUBBLED = 0x00000002,     // PostMessage")
    lines.append("        GMF_EVENT = 0x00000003,       // Message -> Event")
    lines.append("        GMF_DESTINATION = 0x00000003, // Message reach dest")
    lines.append("    };")
    lines.append("")
    lines.append("    enum DUSER_INPUT_DEVICE : unsigned int")
    lines.append("    {")
    lines.append("        GINPUT_MOUSE = 0,")
    lines.append("        GINPUT_KEYBOARD = 1,")
    lines.append("        GINPUT_JOYSTICK = 2,")
    lines.append("    };")
    lines.append("")
    lines.append("    enum DUSER_INPUT_CODE : unsigned int")
    lines.append("    {")
    lines.append("        GMOUSE_MOVE = 0,")
    lines.append("        GMOUSE_DOWN = 1,")
    lines.append("        GMOUSE_UP = 2,")
    lines.append("        GMOUSE_DRAG = 3,")
    lines.append("        GMOUSE_HOVER = 4,")
    lines.append("        GMOUSE_WHEEL = 5,")
    lines.append("        GBUTTON_NONE = 0,")
    lines.append("        GBUTTON_LEFT = 1,")
    lines.append("        GBUTTON_RIGHT = 2,")
    lines.append("    };")
    lines.append("")
    lines.append("    enum DUSER_INPUT_MODIFIERS : unsigned int")
    lines.append("    {")
    lines.append("        GMODIFIER_NONE = 0,")
    lines.append("        GMODIFIER_LBUTTON = 0x0001,")
    lines.append("        GMODIFIER_RBUTTON = 0x0002,")
    lines.append("        GMODIFIER_SHIFT = 0x0004,")
    lines.append("        GMODIFIER_CONTROL = 0x0008,")
    lines.append("        GMODIFIER_MIDDLE = 0x0010,")
    lines.append("        GMODIFIER_LALT = 0x0020,")
    lines.append("        GMODIFIER_RALT = 0x0040,")
    lines.append("    };")
    lines.append("")
    lines.append("    struct Event")
    lines.append("    {")
    lines.append("        Element* target;")
    lines.append("        UID type;")
    lines.append("        bool handled;")
    lines.append("        DUSER_MSG_FLAG flag;")
    lines.append("    };")
    lines.append("")
    lines.append("    struct InputEvent")
    lines.append("    {")
    lines.append("        Element* target;")
    lines.append("        bool handled;")
    lines.append("        DUSER_MSG_FLAG flag;")
    lines.append("        DUSER_INPUT_DEVICE device;")
    lines.append("        DUSER_INPUT_CODE code;")
    lines.append("        DUSER_INPUT_MODIFIERS modifiers;")
    lines.append("    };")
    lines.append("")
    lines.append("    // CClassFactory: opaque handle type used by UITest's Register hook")
    lines.append("    // (the real implementation is internal to dui70.dll).")
    lines.append("    struct CClassFactory;")
    lines.append("")
    # Pure abstract consumer interface. novtable (MIDL_INTERFACE semantics;
    # real DLL has NO IElementListener symbols): UITest listener classes
    # derive from this -- their ctors must not emit a base vftable here.
    # NOTE: the ctor is left implicit (NOT declare-only) -- a declared-only
    # ctor would put an UNDEF ??0IElementListener...IEAA into consumer objs
    # (UITest listeners call the base ctor), and the shim lib cannot
    # resolve it. The implicit trivial ctor may appear as a COMDAT inside
    # the DERIVING consumer's own obj, which is self-contained and fine.
    lines.append("    struct __declspec(novtable) IElementListener")
    lines.append("    {")
    lines.append("    public:")
    lines.append("        // slot 0")
    lines.append("        virtual void OnListenerAttach(Element* elem) = 0;")
    lines.append("        // slot 1")
    lines.append("        virtual void OnListenerDetach(Element* elem) = 0;")
    lines.append("        // slot 2 -- returns false to cancel")
    lines.append("        virtual bool OnPropertyChanging(Element* elem, PropertyInfo const* prop, int unk, Value* before, Value* after) = 0;")
    lines.append("        // slot 3")
    lines.append("        virtual void OnListenedPropertyChanged(Element* elem, PropertyInfo const* prop, int type, Value* before, Value* after) = 0;")
    lines.append("        // slot 4")
    lines.append("        virtual void OnListenedInput(Element* elem, InputEvent* event) = 0;")
    lines.append("        // slot 5")
    lines.append("        virtual void OnListenedEvent(Element* elem, Event* event) = 0;")
    lines.append("    };")
    lines.append("")
    # IClassInfo: real DLL has NO ??0/??1/??_7 IClassInfo symbols (only
    # derived ElementClassInfo etc.). novtable prevents a vftable for this
    # interface; the inline empty bodies are never emitted unless odr-used
    # (the stub TUs never instantiate IClassInfo). The non-trivial-ish
    # shape (user-declared ctor/dtor) is kept so consumers stay source-
    # compatible with the DirectUI interface shape.
    lines.append("    struct __declspec(novtable) IClassInfo")
    lines.append("    {")
    lines.append("        IClassInfo() {}")
    lines.append("        IClassInfo(const IClassInfo&) = delete;")
    lines.append("        IClassInfo& operator=(const IClassInfo&) = delete;")
    lines.append("        virtual ~IClassInfo() {}")
    lines.append("")
    lines.append("    public:")
    lines.append("        // slots follow the DirectUI order (AddRef..AssertPIZeroRef,")
    lines.append("        // then the deleting dtor)")
    lines.append("        virtual long AddRef(void) = 0;                                   // 0")
    lines.append("        virtual long Release(void) = 0;                                 // 1")
    lines.append("        virtual long CreateInstance(Element*, unsigned long*, Element**) = 0;  // 2")
    lines.append("        virtual PropertyInfo* EnumPropertyInfo(unsigned int) = 0;       // 3")
    lines.append("        virtual PropertyInfo* GetByClassIndex(unsigned int) = 0;        // 4")
    lines.append("        virtual unsigned int GetPICount(void) = 0;                     // 5")
    lines.append("        virtual unsigned int GetGlobalIndex(void) = 0;                 // 6")
    lines.append("        virtual IClassInfo* GetBaseClass(void) = 0;                    // 7")
    lines.append("        virtual UCString GetName(void) = 0;                            // 8")
    lines.append("        virtual bool IsValidProperty(PropertyInfo const*) = 0;        // 9")
    lines.append("        virtual bool IsSubclassOf(IClassInfo*) = 0;                   // 10")
    lines.append("        virtual void Destroy(void) = 0;                               // 11")
    lines.append("        virtual HINSTANCE GetModule(void) = 0;                        // 12")
    lines.append("        virtual bool IsGlobal(void) = 0;                              // 13")
    lines.append("        virtual void AddChild(void) = 0;                              // 14")
    lines.append("        virtual void RemoveChild(void) = 0;                           // 15")
    lines.append("        virtual unsigned int GetChildren(void) = 0;                   // 16")
    lines.append("        virtual void AssertPIZeroRef(void) = 0;                       // 17")
    lines.append("    };")
    lines.append("")
    lines.append("    // IXProviderCP / IXElementCP: connection-point interfaces used by")
    lines.append("    // XProvider (vtable slot order from the DirectUI interfaces).")
    lines.append("    class IXProviderCP")
    lines.append("    {")
    lines.append("    public:")
    lines.append("        virtual long CreateDUICP(HWNDElement*, HWND, HWND, Element**, DUIXmlParser**) = 0;")
    lines.append("        virtual long CreateParserCP(DUIXmlParser**) = 0;")
    lines.append("        virtual void DestroyCP(void) = 0;")
    lines.append("    };")
    lines.append("")
    lines.append("    class IXElementCP")
    lines.append("    {")
    lines.append("    public:")
    lines.append("        virtual HWND GetNotificationSinkHWND(void) = 0;")
    lines.append("    };")
    lines.append("")
    lines.append("    // IXProvider: the abstract interface XProvider implements.")
    lines.append("    // Slot order: IUnknown first (QI/AddRef/Release), then the")
    lines.append("    // provider methods in DirectUI order. On x64 the real methods")
    lines.append("    // are all __cdecl; the __stdcall markers in the DirectUI headers are")
    lines.append("    // ignored by the x64 compiler, so we use the default here too.")
    lines.append("    //")
    lines.append("    // MIDL_INTERFACE semantics (struct + novtable + protected ctor with")
    lines.append("    // NO definition): a pure abstract interface must not EMIT any")
    lines.append("    // symbol. Without novtable the compiler synthesizes ??_7IXProvider")
    lines.append("    // (vftable) for the base subobject that XProvider's ctor")
    lines.append("    // initializes; with an implicit public ctor it emits")
    lines.append("    // ??0IXProvider...QEAA as a COMDAT. Neither exists in the real DLL")
    lines.append("    // (A4 precision target). The protected ctor is DECLARED but NOT")
    lines.append("    // DEFINED: the stub obj then carries only an UNDEF reference to it")
    lines.append("    // (never linked; A4 judges defined symbols only). 'struct' matches")
    lines.append("    // the real mangling -- the DLL refers to IXProvider as PEAU")
    lines.append("    // (struct), e.g. ?GetProvider@XElement@DirectUI@@QEAAPEAUIXProvider@2@XZ,")
    lines.append("    // while IXProviderCP/IXElementCP mangle as PEAV (class) and stay 'class'.")
    lines.append("    struct __declspec(novtable) IXProvider : public IUnknown")
    lines.append("    {")
    lines.append("    protected:")
    lines.append("        IXProvider();  // declared only: never defined, never emitted")
    lines.append("    public:")
    lines.append("        virtual long CreateDUI(IXElementCP*, HWND*) = 0;")
    lines.append("        virtual long SetParameter(GUID const&, void*) = 0;")
    lines.append("        virtual long GetDesiredSize(int, int, SIZE*) = 0;")
    lines.append("        virtual long IsDescendent(Element*, bool*) = 0;")
    lines.append("        virtual long SetFocus(Element*) = 0;")
    lines.append("        virtual long Navigate(int, bool*) = 0;")
    lines.append("        virtual long CanSetFocus(bool*) = 0;")
    lines.append("        virtual int FindElementWithShortcutAndDoDefaultAction(unsigned short, int) = 0;")
    lines.append("        virtual long GetHostedElementID(unsigned short*) = 0;")
    lines.append("        virtual long ForceThemeChange(UINT_PTR, LONG_PTR) = 0;")
    lines.append("        virtual long SetDefaultButtonTracking(bool) = 0;")
    lines.append("        virtual int ClickDefaultButton(void) = 0;")
    lines.append("        virtual long SetRegisteredDefaultButton(Element*) = 0;")
    lines.append("        virtual long SetButtonClassAcceptsEnterKey(bool) = 0;")
    lines.append("    };")
    lines.append("")
    lines.append("} // namespace DirectUI")
    lines.append("")
    return "\n".join(lines)


def render_extern_c_block() -> str:
    """extern "C" declarations for the plain-named C API exports.
    The real DLL exports these as undecorated C symbols; declaring them
    extern \"C\" produces exactly the same symbol shape for the linker.
    Signatures come from UITest usage + the DirectUI headers (the export
    table only carries the plain name)."""
    lines = []
    lines.append("")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// extern \"C\" API -- plain-name exports of the real dui70.dll.")
    lines.append("// Signatures from UITest usage + the DirectUI headers; the export table")
    lines.append("// itself only carries the undecorated name.")
    lines.append("// TODO: remaining ~80 plain-name exports (incl. DUI70_XXX-prefixed")
    lines.append("// whose signatures are not yet recovered) are not declared here.")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append('extern "C" {')
    lines.append("")
    lines.append("HRESULT WINAPI InitProcessPriv(int duiVersion, unsigned short* unk1, char unk2, bool bEnableUIAutomationProvider);")
    lines.append("HRESULT WINAPI UnInitProcessPriv(unsigned short* unk1);")
    lines.append("HRESULT WINAPI InitThread(int iDontKnow);")
    lines.append("int WINAPI RegisterAllControls();")
    lines.append("int WINAPI StartMessagePump();")
    lines.append("ATOM WINAPI StrToID(UCString resId);")
    lines.append("")
    lines.append("} // extern \"C\"")

    # Decorated free functions (real exports, global scope, C++ mangling).
    # DumpDuiTree is consumed by UITest.
    lines.append("")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// Free functions -- decorated exports of the real dui70.dll")
    lines.append("// (mangled ?Name@@YA...; NOT extern \"C\").")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("void __cdecl DumpDuiTree(DirectUI::Element* element, int depth);")
    return "\n".join(lines)


def render_aggregate_header(classes: list, banner: str) -> str:
    lines = [banner]
    n = len(classes)
    lines.append(f"// Aggregate header for the {n} UITest-required classes.")
    lines.append("#pragma once")
    lines.append("")
    lines.append('#include "dui_abi_types.h"')
    lines.append('#include "Interfaces.h"')
    for cls in classes:
        lines.append(f'#include "{cls}.h"')
    # extern "C" API block at the end (needs UCString from dui_abi_types.h)
    lines.append(render_extern_c_block())
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pinned", type=Path, default=DEFAULT_PINNED)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--classes", default=None,
                    help="override the class list from classes.json (comma-separated)")
    args = ap.parse_args(argv)

    # class list + inheritance from pinned/classes.json (axis B made explicit)
    classes, inheritance = load_classes(args.pinned / "classes.json")
    if args.classes:
        classes = [c.strip() for c in args.classes.split(",") if c.strip()]

    out_dir: Path = args.out
    out_dir.mkdir(parents=True, exist_ok=True)

    # pin fingerprint for the banner
    manifest = json.loads((args.pinned / "manifest.json").read_text(encoding="utf-8"))
    pin_hash12 = manifest["dll"]["sha256"][:12]
    banner = make_banner(pin_hash12)

    symbols = load_symbols(args.pinned / "symbols.json")
    tr = TypeTranslator(classes)

    stats = {}
    for cls in classes:
        members = [s for s in symbols
                   if s.get("class") == cls
                   and is_callable(s)]
        data_members = [s for s in symbols
                        if s.get("class") == cls
                        and is_data(s)]
        content = render_class_header(cls, members, data_members, tr,
                                      classes, inheritance, banner)
        (out_dir / f"{cls}.h").write_text(content, encoding="utf-8", newline="\n")
        stats[cls] = {"methods": len(members), "data": len(data_members)}

    # shared prelude + interfaces + aggregate
    (out_dir / "dui_abi_types.h").write_text(render_abi_types_header(banner), encoding="utf-8", newline="\n")
    (out_dir / "Interfaces.h").write_text(render_interfaces_header(banner), encoding="utf-8", newline="\n")
    (out_dir / "DirectUI.h").write_text(render_aggregate_header(classes, banner), encoding="utf-8", newline="\n")

    print(f"emit_headers: wrote {len(classes) + 3} files to {out_dir}")
    for cls in classes:
        s = stats[cls]
        print(f"  {cls:<16} callables={s['methods']:4d} data={s['data']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
